Repository SuperNewRoles/SuperNewRoles, pull requests merged in 2022-07, with the labels that each got.

#221 Fix/create role.pyのプレイヤーカウントのコード修正及び[//プレイヤーカウント]の復旧
  SNRDevTools/CreateRole.py
  SNRDevTools/CreateRoleAdvanced.py
  SuperNewRoles/AllRoleSetClass.cs
Labels: Other/その他

#185 テキスト修正
  SNRDevTools/trans_00_en.txt
  SNRDevTools/transdate.txt
  SNRDevTools/translatedate.json
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/Resources/translatedate.json
Labels: bug/バグ修正

#224 死後の拡大縮小機能を追加
  SNRDevTools/trans_00_en.txt
  SNRDevTools/trans_11_jp.txt
  SNRDevTools/transdate.txt
  SNRDevTools/translatedate.json
  SNRDevTools/transmoto.txt
  SuperNewRoles/Buttons/ButtonTime.cs
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/MapOptions/MapOption.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleSelectHandler.cs
  SuperNewRoles/Patch/Clairvoyant.cs
  SuperNewRoles/Patch/FixedUpdate.cs
  SuperNewRoles/Patch/Zoom.cs
  SuperNewRoles/Resources/translatedate.json
Labels: feature/新機能

#216 新役職「シークレットリーキラー」
  CreditsData.json
  SNRDevTools/trans_00_en.txt
  SNRDevTools/trans_11_jp.txt
  SNRDevTools/transdate.txt
  SNRDevTools/translatedate.json
  SNRDevTools/transmoto.txt
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Buttons/CustomButton.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/Intro/IntroDate.cs
  SuperNewRoles/Resources/translatedate.json
  SuperNewRoles/Roles/Minimalist.cs
  SuperNewRoles/Roles/RoleClass.cs
  SuperNewRoles/Roles/RoleHelper.cs
  SuperNewRoles/Roles/SecretlyKiller.cs
Labels: NewRole/新役職, SNR/SNR

#210 CRA修正
  SuperNewRoles/AllRoleSetClass.cs
Labels: bug/バグ修正

#225 readmeにスポンサー、クレジット追加
  READMEs/README_en.md
  READMEs/README_jp.md
Labels: documentetion/文書の変更

#230 readmeに役職表・カスタムコスメティックのクレジットを追加
  READMEs/README_en.md
  READMEs/README_jp.md
Labels: documentetion/文書の変更

#232 推奨設定を丸ごと書き換え
  SuperNewRoles/Patch/ChangeRecommendedSettingPatch.cs
Labels: new feature/新機能

#238 ハシゴ修正
  SuperNewRoles/Patch/LadderDead.cs
Labels: bug/バグ修正

#237 Develop => master
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/Main.cs
  SuperNewRoles/MapOptions/MapOption.cs
  SuperNewRoles/Patch/LadderDead.cs
Labels: merge to master/マスターにマージ

#241 千里眼修正
  SuperNewRoles/Buttons/Buttons.cs
Labels: bug/バグ修正

#243 masterにマージ(v1.4.1.4)
  .gitignore
  SNRDevTools/trans_00_en.txt
  SNRDevTools/trans_11_jp.txt
  SNRDevTools/transdate.txt
  SNRDevTools/translatedate.json
  SNRDevTools/transmoto.txt
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/CustomObject/Kunai.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/CustomOption/CustomOptionModel.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/Helpers/RPCHelper.cs
  SuperNewRoles/Intro/IntroDate.cs
  SuperNewRoles/Main.cs
  SuperNewRoles/MapCustoms/Airship/SecretRoom.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Patch/ChatCommand.cs
  SuperNewRoles/Patch/FixedUpdate.cs
  SuperNewRoles/Patch/GameStartPatch.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Patch/SetNames.cs
  SuperNewRoles/Patch/WrapUpPatch.cs
  SuperNewRoles/Resources/KunoichiKunai.png
  SuperNewRoles/Resources/KunoichiKunaiButton.png
  SuperNewRoles/Resources/translatedate.json
  SuperNewRoles/Roles/Kunoichi.cs
  SuperNewRoles/Roles/RoleClass.cs
  SuperNewRoles/Roles/RoleHelper.cs
  SuperNewRoles/Roles/SetTarget.cs
  SuperNewRoles/obj/Debug/netstandard2.1/SuperNewRoles.GeneratedMSBuildEditorConfig.editorconfig
Labels: merge to master/マスターにマージ

#251 配電盤を移動する設定を追加
  SNRDevTools/trans_00_en.txt
  SNRDevTools/trans_11_jp.txt
  SNRDevTools/transdate.txt
  SNRDevTools/translatedate.json
  SNRDevTools/transmoto.txt
  SuperNewRoles/MapCustoms/4_Airship/MoveElecPad.cs
  SuperNewRoles/MapCustoms/MapCustom.cs
  SuperNewRoles/MapCustoms/main.cs
  SuperNewRoles/Resources/translatedate.json
  SuperNewRoles/Roles/RoleClass.cs
Labels: new feature/新機能

#252 配線タスク追加
  READMEs/README_en.md
  READMEs/README_jp.md
  SNRDevTools/trans_00_en.txt
  SNRDevTools/trans_11_jp.txt
  SNRDevTools/transdate.txt
  SNRDevTools/translatedate.json
  SNRDevTools/transmoto.txt
  SuperNewRoles/MapCustoms/4_Airship/AddWireTasks.cs
  SuperNewRoles/MapCustoms/MapCustom.cs
  SuperNewRoles/Resources/translatedate.json
Labels: new feature/新機能

#255 ダブルキラー・スマッシャー完成
  SNRDevTools/trans_00_en.txt
  SNRDevTools/trans_11_jp.txt
  SNRDevTools/transdate.txt
  SNRDevTools/translatedate.json
  SNRDevTools/transmoto.txt
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/Intro/IntroDate.cs
  SuperNewRoles/Resources/translatedate.json
  SuperNewRoles/Roles/DoubleKiller.cs
  SuperNewRoles/Roles/Minimalist.cs
  SuperNewRoles/Roles/RoleClass.cs
  SuperNewRoles/Roles/RoleHelper.cs
  SuperNewRoles/Roles/Smasher.cs
Labels: new Role/新役職, notMerge/マージしないで！

#254 Develop > master
  READMEs/README_en.md
  READMEs/README_jp.md
  SNRDevTools/trans_00_en.txt
  SNRDevTools/trans_11_jp.txt
  SNRDevTools/transdate.txt
  SNRDevTools/translatedate.json
  SNRDevTools/transmoto.txt
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/AutoUpdate.cs
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Config.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/CustomOption/CustomOptionModel.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/CustomRPC/CustomRPCSender.cs
  SuperNewRoles/Debugger.cs
  SuperNewRoles/EndGame/EndGame.cs
  SuperNewRoles/Helpers/DesyncHelpers.cs
  SuperNewRoles/Helpers/RPCHelper.cs
  SuperNewRoles/Intro/IntroDate.cs
  SuperNewRoles/Main.cs
  SuperNewRoles/MapCustoms/00_AllMaps/AdditionalVent.cs
  SuperNewRoles/MapCustoms/1_MiraHQ/AddVital.cs
  SuperNewRoles/MapCustoms/2_Polus/SpecimenVital.cs
  SuperNewRoles/MapCustoms/4_Airship/AddWireTasks.cs
  SuperNewRoles/MapCustoms/4_Airship/MoveElecPad.cs
  SuperNewRoles/MapCustoms/4_Airship/RecordsAdminDestroy.cs
  SuperNewRoles/MapCustoms/4_Airship/SecretRoom.cs
  SuperNewRoles/MapCustoms/MapCustom.cs
  SuperNewRoles/MapCustoms/Patch.cs
  SuperNewRoles/MapCustoms/main.cs
  SuperNewRoles/MapOptions/MapOption.cs
  SuperNewRoles/MapOptions/MapRemodeling/main.cs
  SuperNewRoles/Mode/ModeHandler.cs
  SuperNewRoles/Mode/SuperHostRoles/BlockTool.cs
  SuperNewRoles/Mode/SuperHostRoles/FixedUpdate.cs
  SuperNewRoles/Mode/SuperHostRoles/Helpers.cs
  SuperNewRoles/Mode/SuperHostRoles/MorePatch.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleSelectHandler.cs
  SuperNewRoles/Patch/ChatCommand.cs
  SuperNewRoles/Patch/ChatHandler.cs
  SuperNewRoles/Patch/DevicesPatch/AdminPatch.cs
  SuperNewRoles/Patch/DevicesPatch/CameraPatch.cs
  SuperNewRoles/Patch/DevicesPatch/VitalPatch.cs
  SuperNewRoles/Patch/FixedUpdate.cs
  SuperNewRoles/Patch/GameStartPatch.cs
  SuperNewRoles/Patch/LogoAndStamp.cs
  SuperNewRoles/Patch/SabotagePatch.cs
  SuperNewRoles/Patch/SelectTask.cs
  SuperNewRoles/Resources/translatedate.json
  SuperNewRoles/Roles/DoubleKiller.cs
  SuperNewRoles/Roles/Minimalist.cs
  SuperNewRoles/Roles/RoleClass.cs
  SuperNewRoles/Roles/RoleHelper.cs
  SuperNewRoles/Roles/Smasher.cs
Labels: merge to master/マスターにマージ

#261 SHRモードでSNRが名前に入ってしまっているときに公開部屋にできないようにする機能を追加
  SuperNewRoles/Mode/SuperHostRoles/FixedUpdate.cs
  SuperNewRoles/Patch/GameStartPatch.cs
Labels: new feature/新機能

#265 赤ずきんちゃん修正
  SuperNewRoles/Helpers/RPCHelper.cs
  SuperNewRoles/Main.cs
  SuperNewRoles/Mode/CopsRobbers/main.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Roles/MeetingSheriff_Patch.cs
  SuperNewRoles/Roles/RedRidingHood.cs
Labels: bug/バグ修正

#263 refact/EndGame
  SuperNewRoles/EndGame/EndGame.cs
  SuperNewRoles/Roles/RoleHelper.cs
Labels: refactoring/リファクタリング

#260 ジャッカルフレンズ作れる設定
  SNRDevTools/trans_00_en.txt
  SNRDevTools/trans_11_jp.txt
  SNRDevTools/transdate.txt
  SNRDevTools/translatedate.json
  SNRDevTools/transmoto.txt
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Resources/translatedate.json
  SuperNewRoles/Roles/RoleClass.cs
Labels: new feature/新機能

#267 Feature/Invalid_toggleInfoOverlay
  SuperNewRoles/Patch/CustomOverlay.cs
Labels: new feature/新機能

#271 readme更新
  READMEs/README_en.md
  READMEs/README_jp.md
Labels: documentetion/文書の変更

#273 タスク個別設定の翻訳でロングタスクとショートタスクが逆転していた問題を修正
  SNRDevTools/trans_00_en.txt
  SNRDevTools/trans_11_jp.txt
  SNRDevTools/transdate.txt
  SNRDevTools/translatedate.json
  SuperNewRoles/Resources/translatedate.json
Labels: bug/バグ修正

#279 会議強制終了コマンド
  SuperNewRoles/Patch/FixedUpdate.cs
Labels: new feature/新機能

#280 日本語ReadMeへの役職及び追加機能の設定追記_英語のReadMeを機能する状態に変更
  READMEs/README_en.md
  READMEs/README_jp.md
Labels: documentetion/文書の変更

#282 公開部屋にできないとき通達するチャットを送る機能
  SuperNewRoles/Patch/GameStartPatch.cs
Labels: new feature/新機能

#286 AddOption/Tuna
  .vs/SuperNewRoles/FileContentIndex/merges/26c6030c-f6c6-4bac-8adf-556783d43d12.vsidx
  .vs/SuperNewRoles/FileContentIndex/merges/26caf334-7bd9-482f-ae44-92307780491b.vsidx
  .vs/SuperNewRoles/FileContentIndex/merges/69754324-59f6-44e4-8af4-3dcf8f439525.vsidx
  .vs/SuperNewRoles/FileContentIndex/merges/b4dbe8cd-ee91-4862-a6f7-d9d11a287e62.vsidx
  .vs/SuperNewRoles/FileContentIndex/merges/cb54ad50-f564-40fe-a6ac-77ef107781b3.vsidx
  .vs/SuperNewRoles/v17/.suo
  SNRDevTools/trans_00_en.txt
  SNRDevTools/trans_11_jp.txt
  SNRDevTools/transdate.txt
  SNRDevTools/translatedate.json
  SNRDevTools/transmoto.txt
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/EndGame/EndGame.cs
  SuperNewRoles/Resources/translatedate.json
  SuperNewRoles/Roles/RoleClass.cs
Labels: new feature/新機能

#291 公開部屋にできない条件を追加
  SuperNewRoles/Patch/GameStartPatch.cs
Labels: new feature/新機能

#294 イビル猫又と黒猫がインポスターを道連れにしない設定の追加&SNR猫又制御を「isRole」形式に変更
  SNRDevTools/trans_00_en.txt
  SNRDevTools/trans_11_jp.txt
  SNRDevTools/transdate.txt
  SNRDevTools/translatedate.json
  SNRDevTools/transmoto.txt
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/Intro/IntroPatch.cs
  SuperNewRoles/Mode/SuperHostRoles/Roles/Nekomata.cs
  SuperNewRoles/Resources/translatedate.json
  SuperNewRoles/Roles/Nekomata.cs
  SuperNewRoles/Roles/RoleClass.cs
Labels: new feature/新機能

#292 ブラックリストを追加
  SuperNewRoles/Patch/Blacklist.cs
Labels: new feature/新機能

#290 ポーラスランダムスポーン
  .vs/SuperNewRoles/FileContentIndex/merges/26c6030c-f6c6-4bac-8adf-556783d43d12.vsidx
  .vs/SuperNewRoles/FileContentIndex/merges/26caf334-7bd9-482f-ae44-92307780491b.vsidx
  .vs/SuperNewRoles/FileContentIndex/merges/69754324-59f6-44e4-8af4-3dcf8f439525.vsidx
  .vs/SuperNewRoles/FileContentIndex/merges/b4dbe8cd-ee91-4862-a6f7-d9d11a287e62.vsidx
  .vs/SuperNewRoles/FileContentIndex/merges/cb54ad50-f564-40fe-a6ac-77ef107781b3.vsidx
  .vs/SuperNewRoles/FileContentIndex/read.lock
  .vs/SuperNewRoles/v17/.suo
  READMEs/README_jp.md
  SNRDevTools/trans_00_en.txt
  SNRDevTools/trans_11_jp.txt
  SNRDevTools/transdate.txt
  SNRDevTools/translatedate.json
  SNRDevTools/transmoto.txt
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/MapCustoms/2_Polus/RandomSpawn.cs
  SuperNewRoles/MapCustoms/MapCustom.cs
  SuperNewRoles/MapCustoms/main.cs
  SuperNewRoles/MapOptions/MapOption.cs
  SuperNewRoles/Resources/translatedate.json
Labels: new feature/新機能

#293 トイレファン
  SNRDevTools/trans_00_en.txt
  SNRDevTools/trans_11_jp.txt
  SNRDevTools/transdate.txt
  SNRDevTools/translatedate.json
  SNRDevTools/transmoto.txt
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/Intro/IntroDate.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleSelectHandler.cs
  SuperNewRoles/Mode/SuperHostRoles/SyncSetting.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Resources/ToiletFanButton.png
  SuperNewRoles/Resources/translatedate.json
  SuperNewRoles/Roles/RoleClass.cs
  SuperNewRoles/Roles/RoleHelper.cs
Labels: new Role/新役職

#298 Devlopで(Masterでも)[Jsonエラー]によりSNRが起動しない問題の修正
  SNRDevTools/trans_00_en.txt
  SNRDevTools/trans_11_jp.txt
  SNRDevTools/transdate.txt
  SNRDevTools/translatedate.json
  SNRDevTools/transmoto.txt
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleSelectHandler.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Resources/translatedate.json
Labels: bug/バグ修正, emergencyFix/緊急バグ修正

#306 Change/PythonTools
  SNRDevTools/CreateRole.py
  SNRDevTools/CreateRoleAdvanced.py
  SuperNewRoles/Roles/RoleClass.cs
Labels: refactoring/リファクタリング, python

#310 サブマージドダウンロードボタンをコメントアウトして隠した。
  SuperNewRoles/Patch/LogoAndStamp.cs
Labels: other/その他

#307 デバッグモードで即開始オプション追加
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/Patch/GameStartPatch.cs
Labels: developmental change/開発的変更

#314 create role advance.pyの修正_インデント修正及びリファクタ後のコード対応
  SNRDevTools/CreateRoleAdvanced.py
  SuperNewRoles/Roles/RoleHelper.cs
Labels: python

#315 トイレファンからインポスターとしての能力を奪っていなかった部分の修正
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/Mode/SuperHostRoles/CoEnterVent.cs
  SuperNewRoles/Mode/SuperHostRoles/EndGameCheck.cs
  SuperNewRoles/Mode/SuperHostRoles/MorePatch.cs
  SuperNewRoles/Mode/SuperHostRoles/SyncSetting.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Roles/RoleHelper.cs
Labels: bug/バグ修正

#318 守護メッセージスケジューラの修正
  SNRDevTools/CreateRole.py
  SNRDevTools/CreateRoleAdvanced.py
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/Mode/SuperHostRoles/CoEnterVent.cs
  SuperNewRoles/Mode/SuperHostRoles/EndGameCheck.cs
  SuperNewRoles/Mode/SuperHostRoles/MorePatch.cs
  SuperNewRoles/Mode/SuperHostRoles/SyncSetting.cs
  SuperNewRoles/Modules/ProctedMessager.cs
  SuperNewRoles/Patch/GameStartPatch.cs
  SuperNewRoles/Patch/Harmony/Meeting/MeetinIntroAnimation.cs
  SuperNewRoles/Patch/Harmony/ShipStatus.cs
  SuperNewRoles/Patch/LogoAndStamp.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Roles/RoleClass.cs
  SuperNewRoles/Roles/RoleHelper.cs
Labels: bug/バグ修正

#320 NEUTRALイントロ
  SNRDevTools/trans_00_en.txt
  SNRDevTools/trans_11_jp.txt
  SNRDevTools/transdate.txt
  SNRDevTools/translatedate.json
  SNRDevTools/transmoto.txt
  SuperNewRoles/Intro/IntroPatch.cs
  SuperNewRoles/Resources/translatedate.json
Labels: change/仕様変更

#321 FastMakerがマッドを作ると同時にキルしてしまう問題の修正
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Roles/Impostor/Minimalist.cs
Labels: bug/バグ修正, change/仕様変更

#323 純正ボタン削除リストを追加
  BotManager.cs
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/Buttons/NormalButtonDestroy.cs
  SuperNewRoles/Buttons/VentAndSabo.cs
  SuperNewRoles/CustomCosmetics/CustomCosmeticsMenus/Patch/AwakePatch.cs
  SuperNewRoles/CustomCosmetics/CustomCosmeticsMenus/Patch/ObjectData.cs
  SuperNewRoles/CustomCosmetics/CustomCosmeticsMenus/Patch/SelectPatch.cs
  SuperNewRoles/CustomCosmetics/CustomCosmeticsMenus/Patch/UpdatePatch.cs
  SuperNewRoles/CustomCosmetics/CustomPet.cs
  SuperNewRoles/CustomCosmetics/ShareCosmetics/DownLoadVisor.cs
  SuperNewRoles/CustomCosmetics/ShareCosmetics/ShareNamePlate.cs
  SuperNewRoles/CustomCosmetics/ShareCosmetics/SharePatch.cs
  SuperNewRoles/CustomOption/CustomOptionModel.cs
  SuperNewRoles/EndGame/CustomEndReason.cs
  SuperNewRoles/EndGame/EndGame.cs
  SuperNewRoles/Helpers/PolygonColliderHelper.cs
  SuperNewRoles/Map/Agartha/ImageManager.cs
  SuperNewRoles/Map/Agartha/Patch/ExileCutscenePatch.cs
  SuperNewRoles/Map/Agartha/Patch/MiniMapPatch.cs
  SuperNewRoles/Map/Agartha/Patch/SetPosition.cs
  SuperNewRoles/Map/Agartha/Patch/SetSprite.cs
  SuperNewRoles/Map/Agartha/main.cs
  SuperNewRoles/Map/ImageManager.cs
  SuperNewRoles/Map/Patch.cs
  SuperNewRoles/Map/SetPosition.cs
  SuperNewRoles/Map/main.cs
  SuperNewRoles/Mode/BattleRoyal/main.cs
  SuperNewRoles/Mode/Detective/Intro.cs
  SuperNewRoles/Mode/Detective/Task.cs
  SuperNewRoles/Mode/Detective/WinCheckPatch.cs
  SuperNewRoles/Mode/LevelUp/main.cs
  SuperNewRoles/Mode/ModeHandler.cs
  SuperNewRoles/Mode/SuperHostRoles/Roles/Jackal.cs
  SuperNewRoles/Mode/Zombie/MurderPlayer.cs
  SuperNewRoles/Modules/ProctedMessager.cs
  SuperNewRoles/Patch/Blacklist.cs
  SuperNewRoles/Patch/ChangeRecommendedSettingPatch.cs
  SuperNewRoles/Patch/ChatCommand.cs
  SuperNewRoles/Patch/DebugMode.cs
  SuperNewRoles/Patch/Fastboot.cs
  SuperNewRoles/Patch/FixedUpdate.cs
  SuperNewRoles/Patch/NeutralTask.cs
  SuperNewRoles/Roles/CrewMate/Seer.cs
  SuperNewRoles/Roles/Impostor/Minimalist.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: refactoring/リファクタリング

#340 ClientOptionを分別
  .gitignore
  SuperNewRoles/ExcelTranslate.cs
  SuperNewRoles/Patch/ClientOptionsPatch/ModOptions.cs
  SuperNewRoles/Patch/ClientOptionsPatch/VanillaOptions.cs
  SuperNewRoles/Patch/HorseModePatch.cs
  SuperNewRoles/Resources/TranslateFile.json
  TranslateData.xlsx
Labels: change/仕様変更

#342 CreateRoleAdvanced.pyを復讐
  SNRDevTools/CreateRoleAdvanced.py
Labels: bug/バグ修正, emergencyFix/緊急バグ修正, change/仕様変更, python, developmental change/開発的変更

#341 革命家と独裁者
  .gitignore
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Buttons/CustomButton.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/CustomOption/CustomOptionModel.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/EndGame/EndGame.cs
  SuperNewRoles/Intro/IntroDate.cs
  SuperNewRoles/Mode/BattleRoyal/Button.cs
  SuperNewRoles/Patch/FixedUpdate.cs
  SuperNewRoles/Patch/MeetingHud.cs
  SuperNewRoles/Patch/WrapUpPatch.cs
  SuperNewRoles/Resources/TranslateFile.json
  SuperNewRoles/Roles/CrewMate/Bakery.cs
  SuperNewRoles/Roles/Neutral/Revolutionist.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  TranslateData.xlsx
Labels: new Role/新役職

#346 NormalButtonDestroyをリファクタ
  SuperNewRoles/Buttons/NormalButtonDestroy.cs
Labels: refactoring/リファクタリング

#347 BotanerをButtonerに変更
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/Intro/IntroDate.cs
  SuperNewRoles/Mode/SuperHostRoles/CoEnterVent.cs
  SuperNewRoles/Mode/SuperHostRoles/EndGameCheck.cs
  SuperNewRoles/Mode/SuperHostRoles/MorePatch.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleHelper.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleSelectHandler.cs
  SuperNewRoles/Mode/SuperHostRoles/SyncSetting.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Resources/TranslateFile.json
  SuperNewRoles/Roles/Impostor/EvilBotaner.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  TranslateData.xlsx
Labels: change/仕様変更

#349 スーサイドウィッシャー‌、トイレファン、ボタナーのアビリティボタンのキーコードがQになっていた問題の修正
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
Labels: bug/バグ修正

#352 (int)GetFloatをGetIntに置き換え
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/Mode/SuperHostRoles/RPCSetTask.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Patch/SelectTask.cs
  SuperNewRoles/Roles/Neutral/Workperson.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
Labels: refactoring/リファクタリング

#350 シェリフの設定追加
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/Roles/CrewMate/Sheriff.cs
Labels: new feature/新機能

#354 新役職 自殺願望者
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/EndGame/EndGame.cs
  SuperNewRoles/Intro/IntroDate.cs
  SuperNewRoles/Patch/FixedUpdate.cs
  SuperNewRoles/Patch/LadderDead.cs
  SuperNewRoles/Patch/SelectTask.cs
  SuperNewRoles/Resources/SuicidalIdeationButton.png
  SuperNewRoles/Resources/TranslateFile.json
  SuperNewRoles/Roles/Neutral/SuicidalIdeation.cs
  SuperNewRoles/Roles/Neutral/Workperson.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  TranslateData.xlsx
Labels: bug/バグ修正, new Role/新役職

#355 新役職「スペランカー」
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/EndGame/EndGame.cs
  SuperNewRoles/Intro/IntroDate.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Patch/FixedUpdate.cs
  SuperNewRoles/Patch/LadderDead.cs
  SuperNewRoles/Patch/WrapUpPatch.cs
  SuperNewRoles/Resources/TranslateFile.json
  SuperNewRoles/Roles/Neutral/Spelunker.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  TranslateData.xlsx
Labels: new Role/新役職

#336 ハット系の軽量化
  SuperNewRoles/CustomCosmetics/CustomHats.cs
  SuperNewRoles/Patch/LogoAndStamp.cs
  SuperNewRoles/Resources/TranslateFile.json
  TranslateData.xlsx
Labels: new feature/新機能, change/仕様変更

#361 カスタムハット以外の「名前つけルール違反」の修正
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/CustomCosmetics/CustomHats.cs
  SuperNewRoles/CustomCosmetics/DownLoadCustomPlate.cs
  SuperNewRoles/CustomCosmetics/DownLoadCustomVisor.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/EndGame/EndGame.cs
  SuperNewRoles/Intro/IntroPatch.cs
  SuperNewRoles/MapCustoms/4_Airship/SecretRoom.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Mode/SuperHostRoles/FixedUpdate.cs
  SuperNewRoles/Mode/SuperHostRoles/RPCSetTask.cs
  SuperNewRoles/Mode/Werewolf/main.cs
  SuperNewRoles/Mode/Zombie/FixedUpdate.cs
  SuperNewRoles/Patch/LadderDead.cs
  SuperNewRoles/Patch/MeetingHud.cs
  SuperNewRoles/Patch/WrapUpPatch.cs
  SuperNewRoles/PlayerControlHepler.cs
  SuperNewRoles/Roles/CrewMate/MeetingSheriff_Patch.cs
  SuperNewRoles/Roles/CrewMate/SoothSayer_Patch.cs
  SuperNewRoles/Roles/Impostor/CountChanger.cs
  SuperNewRoles/Roles/Impostor/PositionSwapper.cs
  SuperNewRoles/Roles/Neutral/FalseCharges.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: developmental change/開発的変更

#363 新役職「ぬーん」
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/Intro/IntroDate.cs
  SuperNewRoles/Patch/DebugMode.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Resources/NunButton.png
  SuperNewRoles/Resources/TranslateFile.json
  SuperNewRoles/Roles/Impostor/Nun.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  TranslateData.xlsx
Labels: new Role/新役職

#364 新役職「フリーター」
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/EndGame/EndGame.cs
  SuperNewRoles/Intro/IntroDate.cs
  SuperNewRoles/Patch/SetNames.cs
  SuperNewRoles/Patch/WrapUpPatch.cs
  SuperNewRoles/Resources/PartTimerButton.png
  SuperNewRoles/Resources/TranslateFile.json
  SuperNewRoles/Roles/Neutral/PartTimer.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  TranslateData.xlsx
Labels: new Role/新役職

#359 新役職「マトリョーシカ」
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/Intro/IntroDate.cs
  SuperNewRoles/Patch/FixedUpdate.cs
  SuperNewRoles/Patch/WrapUpPatch.cs
  SuperNewRoles/Resources/MatryoshkaPutOnButton.png
  SuperNewRoles/Resources/MatryoshkaTakeOffButton.png
  SuperNewRoles/Resources/TranslateFile.json
  SuperNewRoles/Roles/Impostor/Matryoshka.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  TranslateData.xlsx
Labels: new Role/新役職

#362 クリパイの修正(baseurl及び相対パスの修正&新コードに対応)&idの修正
  SNRDevTools/CreateRole.py
  SuperNewRoles/CustomOption/CustomOptionDate.cs
Labels: python, developmental change/開発的変更
