Repository SuperNewRoles/SuperNewRoles, pull requests merged in 2022-10, with the labels that each got.

#543 生き残っていたLevelUpModeの消去
  SuperNewRoles/Mode/ModeHandler.cs
  SuperNewRoles/Resources/TranslateFile.json
  TranslateData.xlsx
Labels: Developmental/開発的

#550 ビルドできない問題を修正
  SuperNewRoles/Roles/Neutral/Jackal.cs
Labels: Developmental/開発的

#552 Refa/setup custom role option
  SuperNewRoles/Modules/CustomOptionDate.cs
  SuperNewRoles/Patch/CustomOptionModel.cs
Labels: Refactoring/リファクタリング

#553 SidekickSeerPromotesをSidekickPromotesに統合
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Roles/Neutral/Jackal.cs
  SuperNewRoles/Roles/Neutral/JackalSeer.cs
Labels: Refactoring/リファクタリング

#562 ドッペルゲンガーのキルクールの修正
  SuperNewRoles/Roles/Impostor/Doppelganger.cs
Labels: Fix/バグ修正

#560 バトロワとゾンビで名前を隠すように変更
  SuperNewRoles/Mode/BattleRoyal/main.cs
  SuperNewRoles/Mode/CopsRobbers/main.cs
  SuperNewRoles/Mode/ModeHandler.cs
  SuperNewRoles/Mode/Zombie/FixedUpdate.cs
Labels: Change/変更

#558 会議終了コマンドバグ修正
  SuperNewRoles/Patch/FixedUpdate.cs
Labels: Fix/バグ修正

#556 フリーターバグ修正
  SuperNewRoles/Patch/FixedUpdate.cs
  SuperNewRoles/Roles/Neutral/PartTimer.cs
Labels: Fix/バグ修正

#551 マッドメイトがベント移動できなくなるように
  SuperNewRoles/Modules/CustomOptionDate.cs
  SuperNewRoles/Modules/VentData.cs
  SuperNewRoles/Patch/FixedUpdate.cs
  SuperNewRoles/Resources/TranslateFile.json
  TranslateData.xlsx
Labels: New feature/新機能

#566 イビルハッカー修正
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/MapOptions/DeviceClass.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
Labels: Fix/バグ修正

#565 マトリョーシカ修正
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Buttons/CustomButton.cs
Labels: Fix/バグ修正

#569 YJさんのハットを一時的に読み込みしないよう変更
  SuperNewRoles/CustomCosmetics/CustomHats.cs
Labels: Fix/バグ修正

#568 クローゼットのタブ画像置き換え
  SuperNewRoles/Resources/Cosmetics/ClosetButton.png
Labels: Change/変更

#578 村長タスク修正
  SuperNewRoles/Modules/CustomRPC.cs
Labels: Fix/バグ修正

#576 マトリョーシカサイドキックバグ修正
  SuperNewRoles/Roles/Impostor/Matryoshka.cs
Labels: Fix/バグ修正

#571 さつまといもが正常に勝利できない問題を修正
  SuperNewRoles/Patch/EndGame.cs
Labels: Fix/バグ修正

#574 RandomSpawnが正常に動作しない問題を修正
  SuperNewRoles/Patch/RandomSpawn.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
Labels: Fix/バグ修正

#572 バグ修正「聖職者」
  SuperNewRoles/Buttons/ButtonTime.cs
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Buttons/CustomButton.cs
  SuperNewRoles/CustomMsg.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Patch/ShipStatus.cs
  SuperNewRoles/Roles/CrewMate/Clergyman.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
Labels: Fix/バグ修正

#579 ボタナーが正常に動作しない問題を修正
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Roles/Impostor/EvilButtoner.cs
Labels: Fix/バグ修正, Refactoring/リファクタリング

#580 殺し屋のエンドゲームのログにtagが存在しなかった為buildでき無かった問題を修正
  SuperNewRoles/Patch/EndGame.cs
Labels: Fix/バグ修正, EmergencyFix/緊急バグ修正

#564 スラッガーの修正
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/CustomObject/PlayerAnimation.cs
  SuperNewRoles/Modules/CustomOptionDate.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
Labels: Fix/バグ修正

#583 SNRでジャッカルフレンズを作れるように変更
  SuperNewRoles/Buttons/Buttons.cs
Labels: Fix/バグ修正, Change/変更

#561 Fix/conjurer beacon
  SuperNewRoles/CustomObject/Beacon.cs
  SuperNewRoles/Modules/CustomAnimation.cs
  SuperNewRoles/Resources/ConjurerBeaconButton.png
  SuperNewRoles/Resources/ConjurerStartButton.png
  SuperNewRoles/Roles/Conjurer.cs
Labels: Fix/バグ修正

#466 一部ハットを削除
  SuperNewRoles/Config.cs
  SuperNewRoles/CustomCosmetics/CustomHats.cs
Labels: EmergencyFix/緊急バグ修正, Other/その他

#588 SHRの場合シェイプシフトが持続する問題の修正
  SuperNewRoles/Mode/SuperHostRoles/ReportDeadBody.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Roles/Impostor/Doppelganger.cs
Labels: Fix/バグ修正

#570 イビルギャンブラーが正常に動作しない問題を修正
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Roles/Impostor/EvilGambler.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: Fix/バグ修正

#516 新役職「波動砲」&「波動砲ジャッカル」
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Buttons/CustomButton.cs
  SuperNewRoles/CustomObject/WaveCannonObject.cs
  SuperNewRoles/Helpers/Il2CppHelpers.cs
  SuperNewRoles/Mode/SuperHostRoles/MorePatch.cs
  SuperNewRoles/Modules/CustomAnimation.cs
  SuperNewRoles/Modules/CustomOptionDate.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/IntroDate.cs
  SuperNewRoles/Patch/EndGame.cs
  SuperNewRoles/Patch/FixedUpdate.cs
  SuperNewRoles/Patch/HorseMode.cs
  SuperNewRoles/Patch/HudManagerPatch.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Patch/SetNames.cs
  SuperNewRoles/Patch/WrapUp.cs
  SuperNewRoles/Resources/Cosmetics/BackGround.png
  SuperNewRoles/Resources/HorseModeButtonOn.png
  SuperNewRoles/Resources/ModStamp.png
  SuperNewRoles/Resources/TranslateFile.json
  SuperNewRoles/Resources/WaveCannon/Cannon.png
  SuperNewRoles/Resources/WaveCannon/ChargeSound.raw
  SuperNewRoles/Resources/WaveCannon/Charge_0001.png
  SuperNewRoles/Resources/WaveCannon/Charge_0002.png
  SuperNewRoles/Resources/WaveCannon/Charge_0003.png
  SuperNewRoles/Resources/WaveCannon/Charge_0004.png
  SuperNewRoles/Resources/WaveCannon/Charge_0005.png
  SuperNewRoles/Resources/WaveCannon/ShootSound.raw
  SuperNewRoles/Resources/WaveCannon/Shoot_0001.png
  SuperNewRoles/Resources/WaveCannon/Shoot_0002.png
  SuperNewRoles/Resources/WaveCannon/Shoot_0003.png
  SuperNewRoles/Resources/WaveCannon/Shoot_0004.png
  SuperNewRoles/Resources/WaveCannon/Shoot_0005.png
  SuperNewRoles/Resources/WaveCannon/Shoot_0006.png
  SuperNewRoles/Resources/WaveCannon/Shoot_0007.png
  SuperNewRoles/Resources/WaveCannon/Shoot_0008.png
  SuperNewRoles/Resources/WaveCannon/Shoot_0009.png
  SuperNewRoles/Resources/WaveCannon/Shoot_0010.png
  SuperNewRoles/Resources/WaveCannon/Shoot_0011.png
  SuperNewRoles/Resources/WaveCannon/Shoot_0012.png
  SuperNewRoles/Resources/WaveCannonButton.png
  SuperNewRoles/Roles/Conjurer.cs
  SuperNewRoles/Roles/CrewMate/MeetingSheriff_Patch.cs
  SuperNewRoles/Roles/Impostor/Freezer.cs
  SuperNewRoles/Roles/Neutral/Jackal.cs
  SuperNewRoles/Roles/Neutral/JackalSeer.cs
  SuperNewRoles/Roles/Neutral/TeleportingJackal.cs
  SuperNewRoles/Roles/Neutral/Vulture.cs
  SuperNewRoles/Roles/Neutral/WaveCannonJackal.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  TranslateData.xlsx
Labels: New Role/新役職

#590 シフトアクターバグ修正
  SuperNewRoles/Patch/FixedUpdate.cs
  SuperNewRoles/Roles/Impostor/ShiftActor.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: Fix/バグ修正

#563 ドアーリファクタリング&ドアーが正常に動作しない問題を修正
  SuperNewRoles/Buttons/ButtonTime.cs
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Buttons/CustomButton.cs
  SuperNewRoles/Roles/CrewMate/Doorr.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
Labels: Fix/バグ修正, Refactoring/リファクタリング

#594 不要なセミコロンを削除
  SuperNewRoles/CustomCosmetics/CustomCosmeticsMenus/Patch/AwakePatch.cs
  SuperNewRoles/Patch/ChatCommand.cs
  SuperNewRoles/Roles/Impostor/Kunoichi.cs
Labels: Refactoring/リファクタリング

#595 RoleTypes版IsRoleメソッド
  SuperNewRoles/Buttons/VentAndSabo.cs
  SuperNewRoles/Roles/Impostor/ShiftActor.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: Refactoring/リファクタリング

#473 新役職「クラッカー」
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Helpers/RPCHelper.cs
  SuperNewRoles/MapOptions/DeviceClass.cs
  SuperNewRoles/Modules/CustomOptionDate.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/IntroDate.cs
  SuperNewRoles/Patch/EndGame.cs
  SuperNewRoles/Patch/WrapUp.cs
  SuperNewRoles/Resources/CrackerButton.png
  SuperNewRoles/Resources/TranslateFile.json
  SuperNewRoles/Roles/CrewMate/Clergyman.cs
  SuperNewRoles/Roles/Impostor/Cracker.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  TranslateData.xlsx
Labels: New Role/新役職

#575 新役職「GM」
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Buttons/CustomButton.cs
  SuperNewRoles/Main.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Modules/CustomOptionDate.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/IntroDate.cs
  SuperNewRoles/PVCreator.cs
  SuperNewRoles/Patch/EndGame.cs
  SuperNewRoles/Patch/IntroPatch.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Patch/SelectTask.cs
  SuperNewRoles/Resources/GMZoomIn.png
  SuperNewRoles/Resources/GMZoomOut.png
  SuperNewRoles/Roles/CrewMate/MeetingSheriff_Patch.cs
  SuperNewRoles/Roles/Neutral/GM.cs
  SuperNewRoles/Roles/Neutral/PartTimer.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: New Role/新役職

#592 メイヤーなどの票数を辞書に格納
  SuperNewRoles/Patch/MeetingHud.cs
Labels: Refactoring/リファクタリング

#491 カモフラージャー
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/Buttons/ButtonTime.cs
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Mode/SuperHostRoles/FixedUpdate.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleSelectHandler.cs
  SuperNewRoles/Mode/SuperHostRoles/SyncSetting.cs
  SuperNewRoles/Modules/CustomOptionDate.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/IntroDate.cs
  SuperNewRoles/Modules/SetNames.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/FixedUpdatePatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Resources/CamouflagerButton.png
  SuperNewRoles/Resources/TranslateFile.json
  SuperNewRoles/Roles/Impostor/Camouflager.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  TranslateData.xlsx
Labels: New Role/新役職, WIP/開発途中, Not Merge/マージしないで！

#598 ButtonクリックでCanMoveが条件だった問題を修正
  SuperNewRoles/Buttons/CustomButton.cs
Labels: Fix/バグ修正

#600 イビルギャンブラーに三項演算子を使う
  SuperNewRoles/Roles/Impostor/EvilGambler.cs
Labels: Refactoring/リファクタリング

#483 ナイスゲッサー/イビルゲッサーを作成
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Modules/CustomOptionDate.cs
  SuperNewRoles/Modules/CustomOptionModel.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/IntroDate.cs
  SuperNewRoles/Resources/TargetIcon.png
  SuperNewRoles/Resources/TranslateFile.json
  SuperNewRoles/Roles/Attribute/Guesser.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  TranslateData.xlsx
Labels: New Role/新役職, WIP/開発途中

#602 カモフラバグ修正
  SuperNewRoles/Buttons/ButtonTime.cs
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Modules/CustomOptionDate.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Roles/Impostor/Camouflager.cs
Labels: Fix/バグ修正, Change/変更

#601 Feature/info log mode
  SuperNewRoles/Patches/IntroPatch.cs
Labels: Developmental/開発的

#559 ケイドロ役職実装
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/Mode/CopsRobbers/CheckEndGame.cs
  SuperNewRoles/Mode/CopsRobbers/RoleSelectHandler.cs
  SuperNewRoles/Mode/CopsRobbers/RoleSystem.cs
  SuperNewRoles/Mode/CopsRobbers/main.cs
  SuperNewRoles/Mode/ModeHandler.cs
  SuperNewRoles/Mode/SuperHostRoles/FixedUpdate.cs
  SuperNewRoles/Mode/SuperHostRoles/SyncSetting.cs
  SuperNewRoles/Patches/ChatHandlerPatch.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/SelectTaskPatch.cs
  SuperNewRoles/Patches/TaskCountPatch.cs
  SuperNewRoles/Resources/TranslateFile.json
  TranslateData.xlsx
Labels: New feature/新機能

#445 バトロワ新機能「キルカウント」
  SuperNewRoles/Mode/BattleRoyal/BROption.cs
  SuperNewRoles/Mode/BattleRoyal/main.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Resources/TranslateFile.json
  TranslateData.xlsx
Labels: New feature/新機能

#604 Version get by csproj
  SuperNewRoles/AutoUpdate.cs
  SuperNewRoles/Main.cs
  SuperNewRoles/Patches/LogoAndStampPatch.cs
  SuperNewRoles/Patches/ShareGameVersionPatch.cs
  SuperNewRoles/SuperNewRoles.csproj
  SuperNewRoles/packages.lock.json
Labels: Developmental/開発的

#605 SHRが正常に動作しない問題を修正
  SuperNewRoles/Buttons/OldModeButtons.cs
  SuperNewRoles/Buttons/VentAndSabo.cs
  SuperNewRoles/Mode/SuperHostRoles/FixedUpdate.cs
Labels: Fix/バグ修正, EmergencyFix/緊急バグ修正, Support SHR/SHR対応

#606 アガルタの新仕様に対応
  SuperNewRoles/AutoUpdate.cs
Labels: EmergencyFix/緊急バグ修正

#534 新役職「パブロフの犬」
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Mode/ModeHandler.cs
  SuperNewRoles/Modules/CustomOptionDate.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/IntroDate.cs
  SuperNewRoles/Modules/SetNames.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/FixedUpdatePatch.cs
  SuperNewRoles/Resources/PavlovsownerCreatedogButton.png
  SuperNewRoles/Resources/TranslateFile.json
  SuperNewRoles/Roles/Neutral/Pavlovsdogs.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  TranslateData.xlsx
Labels: New Role/新役職, Not Merge/マージしないで！

#497 人狼レギュレーション
  READMEs/README_en.md
  READMEs/README_jp.md
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Mode/ModeHandler.cs
  SuperNewRoles/Mode/Werewolf/Intro.cs
  SuperNewRoles/Mode/Werewolf/RoleSelectHandler.cs
  SuperNewRoles/Mode/Werewolf/main.cs
  SuperNewRoles/Modules/CustomOptionDate.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/IntroDate.cs
  SuperNewRoles/Patches/ChatHandlerPatch.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/MeetingHudPatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Resources/ProtectAbilityButton.png
  SuperNewRoles/Resources/TranslateFile.json
  SuperNewRoles/Roles/CrewMate/Knight.cs
  SuperNewRoles/Roles/CrewMate/SoothSayer_Patch.cs
  SuperNewRoles/Roles/Role/IntroHandler.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  TranslateData.xlsx
Labels: New Role/新役職

#619 SHRのカモフラが正常に動作しない問題を修正
  SuperNewRoles/Patches/PlayerControlPatch.cs
Labels: Fix/バグ修正

#614 パブロフの犬バグ修正
  SuperNewRoles/Buttons/Buttons.cs
Labels: Fix/バグ修正

#617 ジャッカルが他人の役職を見ることができてしまう問題を修正
  SuperNewRoles/Modules/SetNames.cs
Labels: Fix/バグ修正

#620 ShowGuardEffectでProtectPlayerに足りなかったcolorIdを追加
  SuperNewRoles/Modules/CustomRPC.cs
Labels: EmergencyFix/緊急バグ修正

#621 ネコカボチャバグ修正
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Roles/Impostor/NekoKabocha.cs
Labels: Fix/バグ修正

#622 追放処理時に対象のObjectがない場合、追放者がいないものとして処理するように変更
  SuperNewRoles/Patches/WrapUpPatch.cs
Labels: Fix/バグ修正

#623 ナイス赤ずきん：設定追加+暗転対策
  SuperNewRoles/Modules/CustomOptionDate.cs
  SuperNewRoles/Roles/CrewMate/RedRidingHood.cs
Labels: Fix/バグ修正

#625 Feature/new translation csv
  StartTranslate.py
  SuperNewRoles/ExcelTranslate.cs
  SuperNewRoles/Main.cs
  SuperNewRoles/Modules/ModTranslation.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Resources/TranslateFile.json
  SuperNewRoles/SuperNewRoles.csproj
  TranslateData.xlsx
Labels: Refactoring/リファクタリング, Change/変更

#631 Follow-up and correction of SChinese translation
  TranslateData.xlsx
Labels: Documentetion/文書の変更

#633 SHRでゲーム終了時にエラーが発生する問題を修正
  SuperNewRoles/Roles/Role/RoleClass.cs
Labels: Fix/バグ修正, EmergencyFix/緊急バグ修正

#635 SChinese csv update
  SuperNewRoles/Resources/Translate.csv
Labels: Translation/翻訳

#638 事故が多いため再びサブマDownloadのボタンを消した
  SuperNewRoles/Patches/LogoAndStampPatch.cs
Labels: Change/変更

#639 最終結果の未翻訳を修正
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Resources/Translate.csv
Labels: Documentetion/文書の変更

#642 Refa/fixed update
  SuperNewRoles/Patches/FixedUpdatePatch.cs
Labels: Refactoring/リファクタリング

#653 バージョン変更1.4.2.4
  SuperNewRoles/SuperNewRoles.csproj
Labels: Version upgrade/バージョンアップ

#652 Develop fix
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/CustomCosmetics/CustomColors.cs
  SuperNewRoles/CustomCosmetics/CustomCosmeticsMenus/Patch/ObjectData.cs
  SuperNewRoles/CustomCosmetics/CustomCosmeticsMenus/Patch/SelectPatch.cs
  SuperNewRoles/CustomCosmetics/CustomCosmeticsMenus/Patch/UpdatePatch.cs
  SuperNewRoles/CustomCosmetics/CustomHats.cs
  SuperNewRoles/Main.cs
  SuperNewRoles/MapOptions/DeviceClass.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Modules/CustomOptionModel.cs
  SuperNewRoles/Patches/ChatCommandPatch.cs
  SuperNewRoles/Patches/ChatPastePatch.cs
  SuperNewRoles/Patches/FixedUpdatePatch.cs
  SuperNewRoles/Patches/FreeNamePatch.cs
  SuperNewRoles/Patches/GameStartPatch.cs
  SuperNewRoles/Roles/Neutral/Arsonist.cs
  SuperNewRoles/Roles/Neutral/Fox.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: Merge to master/マスターにマージ

#657 develop←Master
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/CustomCosmetics/CustomColors.cs
  SuperNewRoles/CustomCosmetics/CustomCosmeticsMenus/Patch/ObjectData.cs
  SuperNewRoles/CustomCosmetics/CustomCosmeticsMenus/Patch/SelectPatch.cs
  SuperNewRoles/CustomCosmetics/CustomCosmeticsMenus/Patch/UpdatePatch.cs
  SuperNewRoles/CustomCosmetics/CustomHats.cs
  SuperNewRoles/Main.cs
  SuperNewRoles/MapOptions/DeviceClass.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Modules/CustomOptionModel.cs
  SuperNewRoles/Patches/ChatCommandPatch.cs
  SuperNewRoles/Patches/ChatPastePatch.cs
  SuperNewRoles/Patches/FixedUpdatePatch.cs
  SuperNewRoles/Patches/FreeNamePatch.cs
  SuperNewRoles/Patches/GameStartPatch.cs
  SuperNewRoles/Roles/Neutral/Arsonist.cs
  SuperNewRoles/Roles/Neutral/Fox.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: Merge to Dev/開発版にマージ

#654 名前関係のコードをコメントアウトした。
  SuperNewRoles/Patches/GameStartPatch.cs
Labels: EmergencyFix/緊急バグ修正

#658 GetStringが日本語になってしまう問題を修正
  SuperNewRoles/Modules/ModTranslation.cs
Labels: Fix/バグ修正

#659 Fix/no trans
  SuperNewRoles/Modules/CustomOptionDate.cs
  SuperNewRoles/Resources/Translate.csv
Labels: Translation/翻訳

#660 IsDebugModeをリファクタリング
  SuperNewRoles/Patches/DebugModePatch.cs
Labels: Refactoring/リファクタリング

#661 シェリフのリセクールにtry-catch
  SuperNewRoles/Roles/CrewMate/Sheriff.cs
Labels: Fix/バグ修正

#663 Refa/fast destroyable singleton
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/CustomCosmetics/CustomHats.cs
  SuperNewRoles/CustomObject/SluggerDeadbody.cs
  SuperNewRoles/Helpers/AntiHackingBan.cs
  SuperNewRoles/Logger.cs
  SuperNewRoles/MapCustoms/4_Airship/SecretRoom.cs
  SuperNewRoles/MapCustoms/main.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Mode/BattleRoyal/main.cs
  SuperNewRoles/Mode/NotImpostorCheck/SelectRolePatch.cs
  SuperNewRoles/Modules/CustomOptionModel.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/CustomServer.cs
  SuperNewRoles/Patches/BanParticularPlayerPatch.cs
  SuperNewRoles/Patches/ChatCommandPatch.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/IntroPatch.cs
  SuperNewRoles/Patches/LogoAndStampPatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/SabotagePatch.cs
  SuperNewRoles/Roles/Attribute/Guesser.cs
  SuperNewRoles/Roles/Impostor/Doppelganger.cs
  SuperNewRoles/Roles/Impostor/ShiftActor.cs
Labels: Refactoring/リファクタリング

#670 CustomOptionHolderとするべき場所がCustomOptionsとなっていた為buildできない問題を修正
  SuperNewRoles/Patches/DebugModePatch.cs
Labels: Fix/バグ修正, EmergencyFix/緊急バグ修正

#671 デバッグモードで[MurderPlayer]が発生したらメッセージで通知を行う設定を追加
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Patches/DebugModePatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
Labels: New feature/新機能

#684 VentPatchをVentAndSaboに移動
  SuperNewRoles/Buttons/VentAndSabo.cs
  SuperNewRoles/Patches/VentPatch.cs
Labels: Refactoring/リファクタリング

#685 NormalButtonDestroyを辞書に格納
  SuperNewRoles/Buttons/NormalButtonDestroy.cs
  SuperNewRoles/Patches/FixedUpdatePatch.cs
Labels: Refactoring/リファクタリング

#686 vanila-->vanilla
  SuperNewRoles/Helpers/RPCHelper.cs
  SuperNewRoles/Mode/ModeHandler.cs
  SuperNewRoles/Modules/CustomOptionModel.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Resources/Translate.csv
Labels: Documentetion/文書の変更

#682 Update SChinese Translation
  SuperNewRoles/Resources/Translate.csv
Labels: Translation/翻訳

#690 ドッペルゲンガーが役職変更時にリセットされるように変更
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: Fix/バグ修正

#692 Feature/rpc log
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Modules/CustomRPC.cs
Labels: Developmental/開発的

#667 特定のmodが入っているときにSNRのロードをブロックするように
  SuperNewRoles/Main.cs
Labels: New feature/新機能

#693 Change/buttons
  SuperNewRoles/Resources/ArsonistDouse.png
  SuperNewRoles/Resources/ArsonistIgnite.png
  SuperNewRoles/Resources/ClergymanLightOutButton.png
  SuperNewRoles/Resources/DemonButton.png
  SuperNewRoles/Resources/DoorrDoorButton.png
  SuperNewRoles/Resources/EvilScientistButton.png
  SuperNewRoles/Resources/FreezerButton.png
  SuperNewRoles/Resources/HawkHawkEye.png
  SuperNewRoles/Resources/JackalSidekickButton.png
  SuperNewRoles/Resources/LighterLightOnButton.png
  SuperNewRoles/Resources/MagazinerAddButton.png
  SuperNewRoles/Resources/MagazinerGetButton.png
  SuperNewRoles/Resources/MovingLocationSetButton.png
  SuperNewRoles/Resources/MovingTpButton.png
  SuperNewRoles/Resources/NiceScientistButton.png
  SuperNewRoles/Resources/PoisonerButton.png
  SuperNewRoles/Resources/PositionSwapperButton.png
  SuperNewRoles/Resources/SamuraiButton.png
  SuperNewRoles/Resources/SelfBomberBomButton.png
  SuperNewRoles/Resources/Setting_Neutral.png
  SuperNewRoles/Resources/SheriffKillButton.png
  SuperNewRoles/Resources/ShielderButton.png
  SuperNewRoles/Resources/SoothSayerButton.png
  SuperNewRoles/Resources/SpeedDownButton.png
  SuperNewRoles/Resources/SpeedUpButton.png
  SuperNewRoles/Resources/VultureButton.png
  SuperNewRoles/Resources/trueloverloveButton.png
Labels: Change/変更

#695 配線タスクランダムの翻訳にカンマが足りない問題修正
  SuperNewRoles/Resources/Translate.csv
Labels: Fix/バグ修正

#699 EvilSeerがMadmateを作ることができる設定を追加
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Resources/CreateMadmateButton.png
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/Role/RoleClass.cs
Labels: New feature/新機能

#688 ShowFlash後Airshipのスポーン時に追放画面が透ける問題及びFlashが復活しない問題の修正
  SuperNewRoles/Roles/CrewMate/Seer.cs
Labels: Fix/バグ修正

#696 Fix/no trans3
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/ModTranslation.cs
  SuperNewRoles/Resources/Translate.csv
Labels: Fix/バグ修正

#703 ヴァンパイアリワーク
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/CustomObject/BloodStain.cs
  SuperNewRoles/MapOptions/DeviceClass.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/IntroData.cs
  SuperNewRoles/Modules/SetNames.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/FixedUpdatePatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/ShipStatusPatch.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Resources/BloodStain.png
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Resources/VampireCreateDependentsButton.png
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/Impostor/Vampire.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  SuperNewRoles/Roles/Role/SetTarget.cs
Labels: Change/変更

#700 キューピットとハンバーガーとペンギンとアガルタランダムスポーン
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/IntroData.cs
  SuperNewRoles/Modules/ModTranslation.cs
  SuperNewRoles/Modules/SetNames.cs
  SuperNewRoles/Patches/DebugModePatch.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/FixedUpdatePatch.cs
  SuperNewRoles/Patches/IntroPatch.cs
  SuperNewRoles/Patches/SelectTaskPatch.cs
  SuperNewRoles/Resources/PenguinButton_1.png
  SuperNewRoles/Resources/PenguinButton_2.png
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/CrewMate/HamburgerShop.cs
  SuperNewRoles/Roles/Impostor/Nun.cs
  SuperNewRoles/Roles/Impostor/Penguin.cs
  SuperNewRoles/Roles/Neutral/Cupid.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  SuperNewRoles/Roles/Role/SetTarget.cs
Labels: New Role/新役職, New feature/新機能

#632 アガルタ「ランダムスポーン」
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Patches/DebugModePatch.cs
  SuperNewRoles/Resources/Translate.csv
Labels: New feature/新機能
