Repository SuperNewRoles/SuperNewRoles, pull requests merged in 2022-05, with the labels that each got.

#49 New role/evil seer&Fix/Seer
  .vs/SuperNewRoles/v17/.suo
  SNRDevTools/trans_00_en.txt
  SNRDevTools/trans_11_jp.txt
  SNRDevTools/transdate.txt
  SNRDevTools/translatedate.json
  SNRDevTools/transmoto.txt
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/Intro/IntroDate.cs
  SuperNewRoles/Properties/launchSettings.json
  SuperNewRoles/Resources/translatedate.json
  SuperNewRoles/Roles/RoleClass.cs
  SuperNewRoles/Roles/RoleHelper.cs
  SuperNewRoles/Roles/Seer.cs
Labels: bug/バグ修正, NewRole/新役職

#51 New role/fox
  .vs/MODD/v17/.suo
  SNRDevTools/trans_00_en.txt
  SNRDevTools/trans_11_jp.txt
  SNRDevTools/transdate.txt
  SNRDevTools/translatedate.json
  SNRDevTools/transmoto.txt
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/EndGame/CustomEndReason.cs
  SuperNewRoles/EndGame/EndGame.cs
  SuperNewRoles/Intro/IntroDate.cs
  SuperNewRoles/Intro/IntroPatch.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Mode/SuperHostRoles/FixedUpdate.cs
  SuperNewRoles/Mode/SuperHostRoles/ReportDeadBody.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleSelectHandler.cs
  SuperNewRoles/Mode/SuperHostRoles/Roles/Fox.cs
  SuperNewRoles/Mode/SuperHostRoles/SyncSetting.cs
  SuperNewRoles/Patch/FixedUpdate.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Patch/SetNames.cs
  SuperNewRoles/Resources/translatedate.json
  SuperNewRoles/Roles/EvilEraser.cs
  SuperNewRoles/Roles/Fox.cs
  SuperNewRoles/Roles/RoleClass.cs
  SuperNewRoles/Roles/RoleHelper.cs
  SuperNewRoles/obj/Debug/netstandard2.1/SuperNewRoles.GeneratedMSBuildEditorConfig.editorconfig
  SuperNewRoles/obj/Debug/netstandard2.1/SuperNewRoles.assets.cache
Labels: NewRole/新役職, SHR/SHR

#56 Fix/妖狐name
  SuperNewRoles/Mode/SuperHostRoles/FixedUpdate.cs
  SuperNewRoles/Patch/LightPatch.cs
  SuperNewRoles/Patch/NeutralTask.cs
  SuperNewRoles/Patch/SetNames.cs
  SuperNewRoles/Roles/Fox.cs
  SuperNewRoles/Roles/RoleHelper.cs
Labels: bug/バグ修正, emergency/緊急

#72 Revert "Scavenger完成"
  .vs/SuperNewRoles/FileContentIndex/21809c3f-d2d9-4277-a53a-7ac82768559b.vsidx
  .vs/SuperNewRoles/FileContentIndex/2cd97cf5-12e3-4668-aea5-17d63a7bb39f.vsidx
  .vs/SuperNewRoles/FileContentIndex/48a1ed53-1ef3-492f-8a84-cbeacda69d58.vsidx
  .vs/SuperNewRoles/FileContentIndex/92f0c82b-fd83-4237-b3ea-50b714e4c725.vsidx
  .vs/SuperNewRoles/FileContentIndex/merges/e83a5b25-7f02-4f9f-9b9a-bbf39d476d98.vsidx
  .vs/SuperNewRoles/FileContentIndex/read.lock
  .vs/SuperNewRoles/v17/.futdcache.v1
  .vs/SuperNewRoles/v17/.suo
  .vs/VSWorkspaceState.json
  .vs/slnx.sqlite
  SNRDevTools/trans_00_en.txt
  SNRDevTools/trans_11_jp.txt
  SNRDevTools/transdate.txt
  SNRDevTools/translatedate.json
  SNRDevTools/transmoto.txt
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/EndGame/CustomEndReason.cs
  SuperNewRoles/EndGame/EndGame.cs
  SuperNewRoles/Intro/IntroDate.cs
  SuperNewRoles/Mode/SuperHostRoles/EndGameCheck.cs
  SuperNewRoles/Mode/SuperHostRoles/FixedUpdate.cs
  SuperNewRoles/Mode/SuperHostRoles/ReportDeadBody.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleSelectHandler.cs
  SuperNewRoles/Mode/SuperHostRoles/SyncSetting.cs
  SuperNewRoles/Patch/SetNames.cs
  SuperNewRoles/Resources/translatedate.json
  SuperNewRoles/Roles/RoleClass.cs
  SuperNewRoles/Roles/RoleHelper.cs
  SuperNewRoles/obj/Debug/netstandard2.1/SuperNewRoles.GeneratedMSBuildEditorConfig.editorconfig
  SuperNewRoles/obj/Debug/netstandard2.1/SuperNewRoles.assets.cache
Labels: bug/バグ修正, emergency/緊急

#74 タスクマネージャー/TaskManager
  .vs/SuperNewRoles/FileContentIndex/0816a51a-c74c-4463-8010-363e6e57e94f.vsidx
  .vs/SuperNewRoles/FileContentIndex/1408a116-ca22-4a49-b86d-b23260a24431.vsidx
  .vs/SuperNewRoles/FileContentIndex/1ab06318-323b-468c-859e-53e14c7d1bce.vsidx
  .vs/SuperNewRoles/FileContentIndex/23600153-a144-4d2c-930d-dfc15e11ffc6.vsidx
  .vs/SuperNewRoles/FileContentIndex/4491880e-a8c3-45d7-883f-44e002b699b7.vsidx
  .vs/SuperNewRoles/FileContentIndex/7032d095-aa03-4fa1-9c79-f1d32b973c2f.vsidx
  .vs/SuperNewRoles/FileContentIndex/92b0a941-d4bb-49cd-88a2-6d2306d5fc87.vsidx
  .vs/SuperNewRoles/FileContentIndex/read.lock
  SNRDevTools/trans_00_en.txt
  SNRDevTools/trans_11_jp.txt
  SNRDevTools/transdate.txt
  SNRDevTools/translatedate.json
  SNRDevTools/transmoto.txt
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/Intro/IntroDate.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleSelectHandler.cs
  SuperNewRoles/Patch/SelectTask.cs
  SuperNewRoles/Resources/translatedate.json
  SuperNewRoles/Roles/RoleClass.cs
  SuperNewRoles/Roles/RoleHelper.cs
Labels: NewRole/新役職

#65 Feature/random map
  .vs/SuperNewRoles/FileContentIndex/70a06e48-da8f-4c90-9239-efa5e98144ad.vsidx
  .vs/SuperNewRoles/FileContentIndex/e0685b7f-db73-4814-9429-8f1108f33d2d.vsidx
  .vs/SuperNewRoles/v17/.suo
  SNRDevTools/trans_00_en.txt
  SNRDevTools/trans_11_jp.txt
  SNRDevTools/transdate.txt
  SNRDevTools/translatedate.json
  SNRDevTools/transmoto.txt
  SuperNewRoles/MapOptions/MapOption.cs
  SuperNewRoles/MapOptions/RandomMap.cs
  SuperNewRoles/Resources/translatedate.json
  SuperNewRoles/obj/Debug/netstandard2.1/SuperNewRoles.GeneratedMSBuildEditorConfig.editorconfig
  SuperNewRoles/obj/Debug/netstandard2.1/SuperNewRoles.assets.cache
Labels: feature/新機能

#87 Fix/MadMayor&SeerFriends
  .vs/SuperNewRoles/v17/.suo
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/Mode/SuperHostRoles/FixedUpdate.cs
  SuperNewRoles/Roles/Madmate.cs
  SuperNewRoles/obj/Debug/netstandard2.1/SuperNewRoles.GeneratedMSBuildEditorConfig.editorconfig
  SuperNewRoles/obj/Debug/netstandard2.1/SuperNewRoles.assets.cache
Labels: bug/バグ修正
