Repository SuperNewRoles/SuperNewRoles, pull requests merged in 2022-08, with the labels that each got.

#357 新役職 ステファインダー
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/EndGame/EndGame.cs
  SuperNewRoles/Intro/IntroDate.cs
  SuperNewRoles/Patch/SetNames.cs
  SuperNewRoles/Roles/CrewMate/Sheriff.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: new Role/新役職

#374 ファイル名変更
  SuperNewRoles/Roles/Impostor/EvilButtoner.cs
Labels: documentetion/文書の変更

#386 サブマージドダウンロードボタン復元
  SuperNewRoles/Patch/LogoAndStamp.cs
Labels: change/仕様変更

#384 配線タスクランダム
  SuperNewRoles/MapOptions/MapOption.cs
  SuperNewRoles/Patch/TaskCount.cs
Labels: new feature/新機能

#388 名前関連の警告に「AmHost」を追加
  SuperNewRoles/Patch/GameStartPatch.cs
Labels: bug/バグ修正

#377 新役職「写真屋」&[EndGame.cs]のリファクタ
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/CustomCosmetics/CustomHats.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/EndGame/EndGame.cs
  SuperNewRoles/Intro/IntroDate.cs
  SuperNewRoles/Patch/FixedUpdate.cs
  SuperNewRoles/Patch/GameStartPatch.cs
  SuperNewRoles/Patch/WrapUpPatch.cs
  SuperNewRoles/Resources/PhotographerButton.png
  SuperNewRoles/Resources/TranslateFile.json
  SuperNewRoles/Roles/Neutral/Jackal.cs
  SuperNewRoles/Roles/Neutral/Photographer.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  SuperNewRoles/SuperNewRoles.csproj
  TranslateData.xlsx
Labels: refactoring/リファクタリング, new Role/新役職, developmental change/開発的変更

#395 てるてるのサボ設定をSHRで出さないように変更&[,]不足の修正
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: bug/バグ修正, emergencyFix/緊急バグ修正, developmental change/開発的変更

#394 ReadMeの誤情報を修正(「全員シェリフ」&Eisbisonさんの名前)&不足分の記載
  READMEs/README_en.md
  READMEs/README_jp.md
Labels: documentetion/文書の変更

#389 ジャッカルのキルボタンのデフォルト状態をキルに変更&キルができた理由のログを細分化
  SuperNewRoles/Patch/PlayerControlPatch.cs
Labels: bug/バグ修正, notMerge/マージしないで！

#387 くノ一の透明化を[待機&ボタン動作]にする設定の追加
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/Resources/KunoichiHideButton.png
  SuperNewRoles/Roles/Impostor/Kunoichi.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
Labels: change/仕様変更, developmental change/開発的変更

#379 めちゃめちゃ細かいリファクタ
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/EndGame/EndGame.cs
  SuperNewRoles/Roles/Impostor/EvilButtoner.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
Labels: refactoring/リファクタリング

#345 自動レギュレーション変更
  SuperNewRoles/CustomOption/CustomOptionModel.cs
  SuperNewRoles/CustomOption/CustomRegulation.cs
  SuperNewRoles/Patch/LogoAndStamp.cs
  TranslateData.xlsx
Labels: new feature/新機能

#358 新役職「殺し屋」
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/EndGame/EndGame.cs
  SuperNewRoles/Intro/IntroDate.cs
  SuperNewRoles/Intro/IntroPatch.cs
  SuperNewRoles/MapOptions/MapOption.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Patch/FixedUpdate.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Patch/WrapUpPatch.cs
  SuperNewRoles/Resources/TranslateFile.json
  SuperNewRoles/Roles/Neutral/Hitman.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  TranslateData.xlsx
Labels: new Role/新役職

#365 新役職「透視者」
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/Intro/IntroDate.cs
  SuperNewRoles/Intro/IntroPatch.cs
  SuperNewRoles/MapOptions/MapOption.cs
  SuperNewRoles/Patch/FixedUpdate.cs
  SuperNewRoles/Resources/TranslateFile.json
  SuperNewRoles/Roles/CrewMate/SeeThroughPerson.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  TranslateData.xlsx
Labels: new Role/新役職

#366 新役職「サイコメトラー」&さつまといものBAG修正
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Buttons/CustomButton.cs
  SuperNewRoles/CustomObject/Footprint.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/EndGame/EndGame.cs
  SuperNewRoles/EndGame/FinalStatus.cs
  SuperNewRoles/Intro/IntroDate.cs
  SuperNewRoles/Patch/FixedUpdate.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Patch/ReportDeadBody.cs
  SuperNewRoles/Patch/SetNames.cs
  SuperNewRoles/Resources/Footprint.png
  SuperNewRoles/Resources/PsychometristButton.png
  SuperNewRoles/Resources/TranslateFile.json
  SuperNewRoles/Roles/CrewMate/Psychometrist.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  TranslateData.xlsx
Labels: bug/バグ修正, new Role/新役職

#370 新役職「ぺインター/painter」
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/CustomObject/Footprint.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/EndGame/EndGame.cs
  SuperNewRoles/Intro/IntroDate.cs
  SuperNewRoles/MapOptions/DeviceClass.cs
  SuperNewRoles/Mode/BattleRoyal/main.cs
  SuperNewRoles/Mode/SuperHostRoles/EndGameCheck.cs
  SuperNewRoles/Mode/SuperHostRoles/FixedUpdate.cs
  SuperNewRoles/Mode/SuperHostRoles/Roles/Jester.cs
  SuperNewRoles/Patch/MeetingHud.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Patch/SetNames.cs
  SuperNewRoles/Patch/WrapUpPatch.cs
  SuperNewRoles/Resources/PainterButton.png
  SuperNewRoles/Resources/TranslateFile.json
  SuperNewRoles/Roles/CrewMate/Painter.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  TranslateData.xlsx
Labels: new Role/新役職

#385 ランダムスポーン完成
  SuperNewRoles/MapOptions/MapOption.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Patch/RandomSpawn.cs
Labels: new feature/新機能

#382 キルクールタイム設定
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/Patch/FixedUpdate.cs
  SuperNewRoles/Patch/SabotagePatch.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
Labels: new feature/新機能

#376 完成「ドクター」
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/Patch/DeadPlayer.cs
  SuperNewRoles/Patch/FixedUpdate.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Resources/TranslateFile.json
  SuperNewRoles/Roles/CrewMate/Doctor.cs
  SuperNewRoles/Roles/Impostor/Matryoshka.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  TranslateData.xlsx
Labels: new Role/新役職, change/仕様変更

#396 エラー修正
  SuperNewRoles/Patch/FixedUpdate.cs
Labels: bug/バグ修正, emergencyFix/緊急バグ修正

#398 新マップ「アガルタ」
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/CustomMap/LoadedHandle.cs
  SuperNewRoles/CustomMap/新しいテキスト ドキュメント.txt
  SuperNewRoles/CustomObject/PlayerAnimation.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/Helpers/CachedPlayer.cs
  SuperNewRoles/Helpers/RPCHelper.cs
  SuperNewRoles/Intro/IntroPatch.cs
  SuperNewRoles/LateTask.cs
  SuperNewRoles/Main.cs
  SuperNewRoles/MapCustoms/1_MiraHQ/AddVital.cs
  SuperNewRoles/Mode/CopsRobbers/main.cs
  SuperNewRoles/PVCreator.cs
  SuperNewRoles/Patch/DebugMode.cs
  SuperNewRoles/Patch/Fastboot.cs
  SuperNewRoles/Patch/FixedUpdate.cs
  SuperNewRoles/Patch/MeetingHud.cs
  SuperNewRoles/Patch/SetNames.cs
  SuperNewRoles/Patch/WrapUpPatch.cs
  SuperNewRoles/Resources/TranslateFile.json
  SuperNewRoles/Roles/CrewMate/Bakery.cs
  SuperNewRoles/Roles/Neutral/Spelunker.cs
  SuperNewRoles/Roles/Neutral/Vulture.cs
  SuperNewRoles/Roles/Role/IntroHandler.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  SuperNewRoles/SubmergedCompatibility.cs
  SuperNewRoles/SuperNewRoles.csproj
  SuperNewRoles/TasksArrows.cs
  TranslateData.xlsx
Labels: new feature/新機能

#399 シェリフキルの役職個別設定を一階層深くした
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/MapOptions/MapOption.cs
  SuperNewRoles/Roles/CrewMate/Sheriff.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
Labels: change/仕様変更, developmental change/開発的変更

#400 修正
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Config.cs
  SuperNewRoles/CustomCosmetics/CustomHats.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/Intro/IntroPatch.cs
  SuperNewRoles/MapOptions/MapOption.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Mode/SuperHostRoles/SyncSetting.cs
  SuperNewRoles/Modules/ProctedMessager.cs
  SuperNewRoles/PVCreator.cs
  SuperNewRoles/Patch/DebugMode.cs
  SuperNewRoles/Resources/TranslateFile.json
  SuperNewRoles/Roles/CrewMate/Sheriff.cs
  TranslateData.xlsx
Labels: bug/バグ修正

#405 SHRかつMOD導入者の場合ボタンが表示されないバグ修正
  SuperNewRoles/Buttons/Buttons.cs
Labels: bug/バグ修正

#406 さつまといものタスク問題の修正&サブマージドの反転コード消去&人狼モードとdleks ehtのコードをコメントアウト
  SuperNewRoles/CustomCosmetics/CustomCosmeticsMenus/Patch/UpdatePatch.cs
  SuperNewRoles/CustomOption/CustomOptionModel.cs
  SuperNewRoles/Helpers/AntiHackingBan.cs
  SuperNewRoles/Main.cs
  SuperNewRoles/MapOptions/MapOption.cs
  SuperNewRoles/Mode/ModeHandler.cs
  SuperNewRoles/Mode/Werewolf/RoleSelectHandler.cs
  SuperNewRoles/Mode/Werewolf/WerewolfOptions.cs
  SuperNewRoles/OutfitManager.cs
  SuperNewRoles/Patch/InversionMap.cs
  SuperNewRoles/Patch/RandomSpawn.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: bug/バグ修正, help/助けて, change/仕様変更

#413 ケイドロのプレイヤー名の修正及び仕様変更
  SuperNewRoles/Main.cs
  SuperNewRoles/Mode/CopsRobbers/CROptions.cs
  SuperNewRoles/Mode/CopsRobbers/main.cs
  SuperNewRoles/Mode/HideAndSeek/HASOptions.cs
  SuperNewRoles/Mode/HideAndSeek/Task.cs
  SuperNewRoles/Mode/ModeHandler.cs
  SuperNewRoles/Resources/TranslateFile.json
  TranslateData.xlsx
Labels: bug/バグ修正, change/仕様変更, developmental change/開発的変更

#419 Remove/not use files
  SuperNewRoles/CustomMap/新しいテキスト ドキュメント.txt
  SuperNewRoles/DiscordStatus/Patch.cs
  SuperNewRoles/DiscordStatus/main.cs
  SuperNewRoles/Mode/LevelUp/main.cs
  SuperNewRoles/Mode/SuperHostRoles/Blackoutfix.cs
  SuperNewRoles/Mode/SuperHostRoles/BlockTool.cs
  SuperNewRoles/Mode/SuperHostRoles/RPCSetTask.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Patch/ReportDeadBody.cs
  SuperNewRoles/TranslateDate.cs
  translatedate.jsonjp.txt
Labels: documentetion/文書の変更, developmental change/開発的変更
