Repository SuperNewRoles/SuperNewRoles, pull requests merged in 2022-12, with the labels that each got.

#823 Dev_Feature&Dev_Fix=>develop (Ver1.3.4.1_流石に最後のはず!!)
  SuperNewRoles/CustomObject/BloodStain.cs
  SuperNewRoles/Modules/Config.cs
  SuperNewRoles/Patches/ClientOptionsPatch/ModOptions.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/Impostor/Vampire.cs
Labels: Dev_fix&fea to develop/開発版にマージ

#824 develop => master (Ver1.3.4.1_流石に最後のはず!!)
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/CustomObject/BloodStain.cs
  SuperNewRoles/Modules/Config.cs
  SuperNewRoles/Patches/ClientOptionsPatch/ModOptions.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/Impostor/Vampire.cs
Labels: develop to master/マスターにマージ

#828 master=>Develop_fix
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Resources/Translate.csv
Labels: master to Dev_fix&fea/リリース版の反映

#827 master=>Dev_feature
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/CustomObject/BloodStain.cs
  SuperNewRoles/Modules/Config.cs
  SuperNewRoles/Patches/ClientOptionsPatch/ModOptions.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/Impostor/Vampire.cs
Labels: master to Dev_fix&fea/リリース版の反映

#826 スピードブースターのスピード倍率の初期値を変更
  SuperNewRoles/Modules/CustomOptionHolder.cs
Labels: Change/変更

#825 インポスター役職のDescription(日本語のみ)を追加
  SuperNewRoles/Resources/Translate.csv
Labels: Documentetion/文書の変更

#820 自爆魔のクールダウン設定を追加
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/Impostor/SelfBomber.cs
Labels: Change/変更, Adjustment/調整

#833 "Preset"の翻訳を簡略化
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Resources/Translate.csv
Labels: Refactoring/リファクタリング

#835 PlayerByIdをキャッシュ化
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
Labels: Refactoring/リファクタリング

#837 ，を,にReplace
  SuperNewRoles/Modules/ModTranslation.cs
Labels: Change/変更

#832 会議後にエアーシップの電気室のドアをシャッフルする設定を追加
  SuperNewRoles/MapCustoms/MapCustom.cs
  SuperNewRoles/MapCustoms/main.cs
  SuperNewRoles/Resources/Translate.csv
Labels: New feature/新機能

#834 LoadCsvにtry-catch
  SuperNewRoles/Modules/ModTranslation.cs
Labels: Change/変更

#831 自爆魔と犠牲者の翻訳が逆だった問題を修正
  SuperNewRoles/Resources/Translate.csv
Labels: Adjustment/調整

#830 霊界で役職を見れる設定がSHRで表示されていなかった為修正
  SuperNewRoles/Modules/CustomOptionHolder.cs
Labels: Fix/バグ修正

#840 ゲスト参加時ホストとSNR導入状態が異なる場合自己退出するように修正
  SuperNewRoles/Patches/ShareGameVersionPatch.cs
  SuperNewRoles/Resources/Translate.csv
Labels: Change/変更

#841 サイドキラーがサイドキックされると、マッドキラーが昇格出来ないバグを修正
  SuperNewRoles/Buttons/Buttons.cs
Labels: Fix/バグ修正

#843 Fix/no translate texts
  SuperNewRoles/MapCustoms/4_Airship/SecretRoom.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/Attribute/Guesser.cs
Labels: Fix/バグ修正

#844 マッドキラー / 眷属をシェリフでキルできない問題を修正
  SuperNewRoles/Roles/CrewMate/Sheriff.cs
Labels: Fix/バグ修正

#845 警告を修正
  SuperNewRoles/Mode/SuperHostRoles/BlockTool.cs
Labels: Developmental/開発的

#847 versionup v1.4.3.2
  SuperNewRoles/SuperNewRoles.csproj
Labels: Version upgrade/バージョンアップ

#848 PlayerByIdのエラーを修正
  SuperNewRoles/ModHelpers.cs
Labels: Fix/バグ修正

#849 master <-- develop [v1.4.3.2]
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/CustomCosmetics/CustomColors.cs
  SuperNewRoles/MapCustoms/4_Airship/SecretRoom.cs
  SuperNewRoles/MapCustoms/MapCustom.cs
  SuperNewRoles/MapCustoms/main.cs
  SuperNewRoles/MapOptions/MapOption.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Mode/SuperHostRoles/BlockTool.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/FinalStatus.cs
  SuperNewRoles/Modules/ModTranslation.cs
  SuperNewRoles/Patches/ShareGameVersionPatch.cs
  SuperNewRoles/Patches/TaskCountPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/Attribute/Guesser.cs
  SuperNewRoles/Roles/CrewMate/Sheriff.cs
  SuperNewRoles/Roles/Impostor/SelfBomber.cs
  SuperNewRoles/Roles/Neutral/Hitman.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: develop to master/マスターにマージ

#852 Update for SChinese Translation
  SuperNewRoles/Resources/Translate.csv
Labels: Translation/翻訳

#853 ゲストのModの導入状態に問題がある場合、開始できないように変更した
  SuperNewRoles/CustomCosmetics/CustomColors.cs
  SuperNewRoles/MapCustoms/MapCustom.cs
  SuperNewRoles/MapCustoms/main.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Patches/ShareGameVersionPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/SuperNewRoles.csproj
Labels: Fix/バグ修正, Change/変更

#850 master=>Develop_features
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/MapCustoms/4_Airship/SecretRoom.cs
  SuperNewRoles/MapOptions/MapOption.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Mode/SuperHostRoles/BlockTool.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/FinalStatus.cs
  SuperNewRoles/Modules/ModTranslation.cs
  SuperNewRoles/Patches/ShareGameVersionPatch.cs
  SuperNewRoles/Patches/TaskCountPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/Attribute/Guesser.cs
  SuperNewRoles/Roles/CrewMate/Sheriff.cs
  SuperNewRoles/Roles/Impostor/SelfBomber.cs
  SuperNewRoles/Roles/Neutral/Hitman.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: master to Dev_fix&fea/リリース版の反映

#854 一部役職で縁取りされていないのを修正
  SuperNewRoles/Buttons/Buttons.cs
Labels: Adjustment/調整

#829 "Mode"フォルダーのnamespaceの書き方を修正
  SuperNewRoles/Mode/BattleRoyal/BROption.cs
  SuperNewRoles/Mode/BattleRoyal/Intro.cs
  SuperNewRoles/Mode/BattleRoyal/main.cs
  SuperNewRoles/Mode/CopsRobbers/CROptions.cs
  SuperNewRoles/Mode/CopsRobbers/CheckEndGame.cs
  SuperNewRoles/Mode/CopsRobbers/RoleSelectHandler.cs
  SuperNewRoles/Mode/CopsRobbers/RoleSystem.cs
  SuperNewRoles/Mode/CopsRobbers/main.cs
  SuperNewRoles/Mode/Detective/DetectiveOptions.cs
  SuperNewRoles/Mode/Detective/Intro.cs
  SuperNewRoles/Mode/Detective/Task.cs
  SuperNewRoles/Mode/Detective/WinCheckPatch.cs
  SuperNewRoles/Mode/Detective/main.cs
  SuperNewRoles/Mode/HideAndSeek/main.cs
  SuperNewRoles/Mode/ModeHandler.cs
  SuperNewRoles/Mode/NotImpostorCheck/NameSet.cs
  SuperNewRoles/Mode/NotImpostorCheck/SelectRolePatch.cs
  SuperNewRoles/Mode/NotImpostorCheck/WinCheck.cs
  SuperNewRoles/Mode/NotImpostorCheck/main.cs
  SuperNewRoles/Mode/PlusMode/Options.cs
  SuperNewRoles/Mode/PlusModeHandler.cs
  SuperNewRoles/Mode/RandomColor/FixedUpdate.cs
  SuperNewRoles/Mode/RandomColor/RandomColorOptions.cs
  SuperNewRoles/Mode/RandomColor/main.cs
  SuperNewRoles/Mode/SuperHostRoles/BlockTool.cs
  SuperNewRoles/Mode/SuperHostRoles/Chat.cs
  SuperNewRoles/Mode/SuperHostRoles/CoEnterVent.cs
  SuperNewRoles/Mode/SuperHostRoles/EndGameCheck.cs
  SuperNewRoles/Mode/SuperHostRoles/FixedUpdate.cs
  SuperNewRoles/Mode/SuperHostRoles/Helpers.cs
  SuperNewRoles/Mode/SuperHostRoles/Intro.cs
  SuperNewRoles/Mode/SuperHostRoles/MorePatch.cs
  SuperNewRoles/Mode/SuperHostRoles/MurderPlayer.cs
  SuperNewRoles/Mode/SuperHostRoles/NotBlackOut.cs
  SuperNewRoles/Mode/SuperHostRoles/ReportDeadBody.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleChat.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleHelper.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleSelectHandler.cs
  SuperNewRoles/Mode/SuperHostRoles/Roles/Bait.cs
  SuperNewRoles/Mode/SuperHostRoles/Roles/BestFalseCharge.cs
  SuperNewRoles/Mode/SuperHostRoles/Roles/Fox.cs
  SuperNewRoles/Mode/SuperHostRoles/Roles/GetRoleText.cs
  SuperNewRoles/Mode/SuperHostRoles/Roles/Jester.cs
  SuperNewRoles/Mode/SuperHostRoles/Roles/Minimalist.cs
  SuperNewRoles/Mode/SuperHostRoles/Roles/Nekomata.cs
  SuperNewRoles/Mode/SuperHostRoles/Roles/Samurai.cs
  SuperNewRoles/Mode/SuperHostRoles/SyncSetting.cs
  SuperNewRoles/Mode/SuperHostRoles/WrapUp.cs
  SuperNewRoles/Mode/SuperHostRoles/main.cs
  SuperNewRoles/Mode/Werewolf/main.cs
  SuperNewRoles/Mode/Zombie/FixedUpdate.cs
  SuperNewRoles/Mode/Zombie/Intro.cs
  SuperNewRoles/Mode/Zombie/ZombieOptions.cs
  SuperNewRoles/Mode/Zombie/main.cs
Labels: Refactoring/リファクタリング

#858 コマンド「/ar」と「/gr」の仕様変更
  SuperNewRoles/Patches/ChatHandlerPatch.cs
  SuperNewRoles/Resources/Translate.csv
Labels: Change/変更

#857 kickingTimerが同じ部屋にいる場合試合をまたいでもリセットされなかった問題を修正
  SuperNewRoles/Patches/ShareGameVersionPatch.cs
Labels: Fix/バグ修正

#862 v1.5.0.0
  SuperNewRoles/SuperNewRoles.csproj
Labels: Other/その他, Change/変更, Version upgrade/バージョンアップ

#865 自爆魔のid重複により自爆クールが設定できなかった問題を修正
  SuperNewRoles/Modules/CustomOptionHolder.cs
Labels: Fix/バグ修正

#866 HnS報告済みバグ修正
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/MapCustoms/4_Airship/SecretRoom.cs
  SuperNewRoles/MapCustoms/main.cs
  SuperNewRoles/MapOption/MapOption.cs
  SuperNewRoles/MapOption/RandomMap.cs
  SuperNewRoles/Mode/CopsRobbers/RoleSelectHandler.cs
  SuperNewRoles/Mode/CopsRobbers/main.cs
  SuperNewRoles/Mode/ModeHandler.cs
  SuperNewRoles/Mode/SuperHostRoles/BlockTool.cs
  SuperNewRoles/Mode/SuperHostRoles/Helpers.cs
  SuperNewRoles/Mode/SuperHostRoles/NotBlackOut.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleSelectHandler.cs
  SuperNewRoles/Mode/SuperHostRoles/SyncSetting.cs
  SuperNewRoles/Mode/Werewolf/main.cs
  SuperNewRoles/Mode/Zombie/ZombieOptions.cs
  SuperNewRoles/Mode/Zombie/main.cs
  SuperNewRoles/Modules/CustomOptionModel.cs
  SuperNewRoles/Modules/CustomOverlay.cs
  SuperNewRoles/Modules/CustomRegulation.cs
  SuperNewRoles/Modules/VentData.cs
  SuperNewRoles/Patches/ChatCommandPatch.cs
  SuperNewRoles/Patches/ControllerManagerPatch.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/IntroPatch.cs
  SuperNewRoles/Patches/LadderDeadPatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/SNROnlySearch.cs
  SuperNewRoles/Patches/ShareGameVersionPatch.cs
  SuperNewRoles/Patches/ShipStatusPatch.cs
  SuperNewRoles/Patches/TaskCountPatch.cs
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/CrewMate/Bakery.cs
  SuperNewRoles/Roles/CrewMate/HamburgerShop.cs
  SuperNewRoles/Roles/Neutral/Pavlovsdogs.cs
  SuperNewRoles/Roles/Role/IntroHandler.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  SuperNewRoles/Sabotage/CognitiveDeficit/Patch.cs
  SuperNewRoles/Sabotage/CognitiveDeficit/main.cs
  SuperNewRoles/Sabotage/SabotageManager.cs
Labels: Fix/バグ修正, EmergencyFix/緊急バグ修正

#869 Version up 1.5.1.0
  SuperNewRoles/SuperNewRoles.csproj
Labels: Version upgrade/バージョンアップ

#870 Develop fix
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Helpers/RPCHelper.cs
  SuperNewRoles/MapCustoms/4_Airship/SecretRoom.cs
  SuperNewRoles/MapCustoms/main.cs
  SuperNewRoles/MapOption/MapOption.cs
  SuperNewRoles/MapOption/RandomMap.cs
  SuperNewRoles/Mode/CopsRobbers/RoleSelectHandler.cs
  SuperNewRoles/Mode/CopsRobbers/main.cs
  SuperNewRoles/Mode/ModeHandler.cs
  SuperNewRoles/Mode/SuperHostRoles/BlockTool.cs
  SuperNewRoles/Mode/SuperHostRoles/Helpers.cs
  SuperNewRoles/Mode/SuperHostRoles/NotBlackOut.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleSelectHandler.cs
  SuperNewRoles/Mode/SuperHostRoles/SyncSetting.cs
  SuperNewRoles/Mode/Werewolf/main.cs
  SuperNewRoles/Mode/Zombie/ZombieOptions.cs
  SuperNewRoles/Mode/Zombie/main.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomOptionModel.cs
  SuperNewRoles/Modules/CustomOverlay.cs
  SuperNewRoles/Modules/CustomRegulation.cs
  SuperNewRoles/Modules/VentData.cs
  SuperNewRoles/Patches/ChatCommandPatch.cs
  SuperNewRoles/Patches/ControllerManagerPatch.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/IntroPatch.cs
  SuperNewRoles/Patches/LadderDeadPatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/SNROnlySearch.cs
  SuperNewRoles/Patches/ShareGameVersionPatch.cs
  SuperNewRoles/Patches/ShipStatusPatch.cs
  SuperNewRoles/Patches/TaskCountPatch.cs
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/CrewMate/Bakery.cs
  SuperNewRoles/Roles/CrewMate/HamburgerShop.cs
  SuperNewRoles/Roles/Neutral/Pavlovsdogs.cs
  SuperNewRoles/Roles/Role/IntroHandler.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  SuperNewRoles/Sabotage/CognitiveDeficit/Patch.cs
  SuperNewRoles/Sabotage/CognitiveDeficit/main.cs
  SuperNewRoles/Sabotage/SabotageManager.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: develop to master/マスターにマージ, Dev_fix&fea to develop/開発版にマージ

#875 master=>Develop_fix
  SuperNewRoles/Main.cs
  SuperNewRoles/Mode/SuperHostRoles/SyncSetting.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Patches/FixedUpdatePatch.cs
  SuperNewRoles/Patches/SNROnlySearch.cs
Labels: master to Dev_fix&fea/リリース版の反映

#859 remove developer "Sakurander"
  CreditsData.json
  READMEs/README_en.md
  READMEs/README_jp.md
Labels: Documentetion/文書の変更

#883 Develop_fix&Develop_feature => develop (v1511)
  CreditsData.json
  READMEs/README_en.md
  READMEs/README_jp.md
  SuperNewRoles/CustomCosmetics/CustomColors.cs
  SuperNewRoles/Modules/CustomOptionModel.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/Role/RoleClass.cs
Labels: Dev_fix&fea to develop/開発版にマージ

#884 Develop
  CreditsData.json
  READMEs/README_en.md
  READMEs/README_jp.md
  SuperNewRoles/CustomCosmetics/CustomColors.cs
  SuperNewRoles/Modules/CustomOptionModel.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/Role/RoleClass.cs
Labels: develop to master/マスターにマージ

#886 設定同期の異常の修正
  SNRDevTools/CreateRoleAdvanced.py
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Helpers/PlayerControlHepler.cs
  SuperNewRoles/Modules/ChacheManager.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomOptionModel.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/IntroData.cs
  SuperNewRoles/Modules/SetNames.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/HudManagerPatch.cs
  SuperNewRoles/Patches/IntroPatch.cs
  SuperNewRoles/Resources/LoversBreakerButton.png
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/Attribute/Jumbo.cs
  SuperNewRoles/Roles/Neutral/LoversBreaker.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: Fix/バグ修正

#887 Develop_fix&Develop_feature=>develop
  SNRDevTools/CreateRoleAdvanced.py
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Helpers/PlayerControlHepler.cs
  SuperNewRoles/Modules/ChacheManager.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomOptionModel.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/IntroData.cs
  SuperNewRoles/Modules/SetNames.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/HudManagerPatch.cs
  SuperNewRoles/Patches/IntroPatch.cs
  SuperNewRoles/Resources/LoversBreakerButton.png
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/Attribute/Jumbo.cs
  SuperNewRoles/Roles/Neutral/LoversBreaker.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: Version upgrade/バージョンアップ, Dev_fix&fea to develop/開発版にマージ

#888 develop=>master (v1.5.2.1)
  SNRDevTools/CreateRoleAdvanced.py
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Helpers/PlayerControlHepler.cs
  SuperNewRoles/Modules/ChacheManager.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomOptionModel.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/IntroData.cs
  SuperNewRoles/Modules/SetNames.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/HudManagerPatch.cs
  SuperNewRoles/Patches/IntroPatch.cs
  SuperNewRoles/Resources/LoversBreakerButton.png
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/Attribute/Jumbo.cs
  SuperNewRoles/Roles/Neutral/LoversBreaker.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: develop to master/マスターにマージ

#889 master=>Develop_feature (v1.5.1.2)
  CreditsData.json
  READMEs/README_en.md
  READMEs/README_jp.md
  SNRDevTools/CreateRoleAdvanced.py
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Helpers/PlayerControlHepler.cs
  SuperNewRoles/Modules/ChacheManager.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomOptionModel.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/IntroData.cs
  SuperNewRoles/Modules/SetNames.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/HudManagerPatch.cs
  SuperNewRoles/Patches/IntroPatch.cs
  SuperNewRoles/Resources/LoversBreakerButton.png
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/Attribute/Jumbo.cs
  SuperNewRoles/Roles/Neutral/LoversBreaker.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: master to Dev_fix&fea/リリース版の反映

#890 master=>Develop_fix (v1.5.1.2)
  SuperNewRoles/CustomCosmetics/CustomColors.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/SuperNewRoles.csproj
Labels: master to Dev_fix&fea/リリース版の反映

#899 Jumboを隠した
  SuperNewRoles/Modules/CustomOptionModel.cs
  SuperNewRoles/Resources/Translate.csv
Labels: Other/その他

#900 Develop_fix=>develop & VersionUp 1.5.2.0
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/MapOption/MapOption.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomOptionModel.cs
  SuperNewRoles/Modules/LateTask.cs
  SuperNewRoles/Modules/SetNames.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Resources/JumboWalkSound.raw
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/Attribute/Jumbo.cs
  SuperNewRoles/Roles/Neutral/LoversBreaker.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: Version upgrade/バージョンアップ, Dev_fix&fea to develop/開発版にマージ

#901 develop=>master (1.5.2.0)
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/MapOption/MapOption.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomOptionModel.cs
  SuperNewRoles/Modules/LateTask.cs
  SuperNewRoles/Modules/SetNames.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Resources/JumboWalkSound.raw
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/Attribute/Jumbo.cs
  SuperNewRoles/Roles/Neutral/LoversBreaker.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: develop to master/マスターにマージ

#902 master=>Dev_feature (v1.5.2.0)
  SuperNewRoles/SuperNewRoles.csproj
Labels: master to Dev_fix&fea/リリース版の反映

#903 master=>Dev_fix (v1.5.2.0)
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/MapOption/MapOption.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomOptionModel.cs
  SuperNewRoles/Modules/LateTask.cs
  SuperNewRoles/Modules/SetNames.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Resources/JumboWalkSound.raw
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/Attribute/Jumbo.cs
  SuperNewRoles/Roles/Neutral/LoversBreaker.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: master to Dev_fix&fea/リリース版の反映

#908 一部役職で縁取りされていないのを修正第二弾
  SuperNewRoles/Buttons/Buttons.cs
Labels: Adjustment/調整

#911 Version Change v1.5.2.1
  SuperNewRoles/SuperNewRoles.csproj
Labels: Version upgrade/バージョンアップ

#914 master=>develop(v1.5.1.2)
  SuperNewRoles/SuperNewRoles.csproj
Labels: master to Dev_fix&fea/リリース版の反映

#913 master=>Develop_fix(ver1.5.2.1)
  SuperNewRoles/SuperNewRoles.csproj
Labels: master to Dev_fix&fea/リリース版の反映

#912 master=>Develop_feature(ver1.5.2.1)
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: master to Dev_fix&fea/リリース版の反映
