Repository SuperNewRoles/SuperNewRoles, pull requests merged in 2022-09, with the labels that each got.

#422 SNRでナイス猫又がインポスターを道連れにせず、イビル猫又がインポスターを道連れにしていた問題の修正
  SuperNewRoles/Mode/SuperHostRoles/Roles/Nekomata.cs
  SuperNewRoles/Roles/CrewMate/Nekomata.cs
Labels: bug/バグ修正

#429 Mod本体のgithubのURLを統合
  SuperNewRoles/AutoUpdate.cs
  SuperNewRoles/Main.cs
  SuperNewRoles/Patch/LogoAndStamp.cs
Labels: developmental change/開発的変更

#431 masterブランチをMainに集約
  SuperNewRoles/Main.cs
  SuperNewRoles/Patch/LogoAndStamp.cs
Labels: developmental change/開発的変更

#433 Refact/buttons
  SuperNewRoles/Buttons/NormalButtonDestroy.cs
  SuperNewRoles/Buttons/OnGameEndTimeReset.cs
  SuperNewRoles/Buttons/VentAndSabo.cs
Labels: refactoring/リファクタリング

#430 Refact/RpcShowGuardEffect
  SuperNewRoles/Mode/SuperHostRoles/Helpers.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
Labels: refactoring/リファクタリング, documentetion/文書の変更, developmental change/開発的変更

#435 Remove/old translation
  SNRDevTools/OldTranslation/trans_00_en.txt
  SNRDevTools/OldTranslation/trans_11_jp.txt
  SNRDevTools/OldTranslation/trans_xx to json.bat
  SNRDevTools/OldTranslation/trans_xx to transdate.py
  SNRDevTools/OldTranslation/transdate to json.py
  SNRDevTools/OldTranslation/transdate.txt
  SNRDevTools/OldTranslation/translatedate.json
  SNRDevTools/OldTranslation/transmoto.txt
  SuperNewRoles/Resources/translatedate.json
Labels: refactoring/リファクタリング, other/その他

#437 dllファイル詳細のバージョンを変更
  SuperNewRoles/SuperNewRoles.csproj
Labels: documentetion/文書の変更

#436 ゲーム起動時にブランチ名などをログに出力
  SuperNewRoles/Main.cs
Labels: new feature/新機能, change/仕様変更, developmental change/開発的変更

#421 クラッシュする可能性がある問題を修正
  SuperNewRoles/CustomCosmetics/DownLoadCustomPlate.cs
Labels: bug/バグ修正, emergencyFix/緊急バグ修正

#426 New role/shift actor
  SNRDevTools/CreateRoleAdvanced.bat
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/Intro/IntroDate.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Resources/TranslateFile.json
  SuperNewRoles/Roles/Impostor/ShiftActor.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  TranslateData.xlsx
Labels: new Role/新役職

#420 Refact/desync and set role
  SuperNewRoles/Mode/SuperHostRoles/RoleSelectHandler.cs
Labels: developmental change/開発的変更

#446 ゲーム起動時にログにアモアス本体のバージョンを出力
  SuperNewRoles/Main.cs
Labels: new feature/新機能, change/仕様変更, developmental change/開発的変更

#447 Feature/late task log
  SuperNewRoles/BotManager.cs
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Main.cs
  SuperNewRoles/MapCustoms/4_Airship/SecretRoom.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Mode/SuperHostRoles/MurderPlayer.cs
  SuperNewRoles/Modules/LateTask.cs
  SuperNewRoles/Patch/ChatHandler.cs
  SuperNewRoles/Patch/DebugMode.cs
  SuperNewRoles/Patch/LadderDead.cs
  SuperNewRoles/Patch/MeetingHud.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Roles/CrewMate/Doctor.cs
  SuperNewRoles/Roles/CrewMate/SeeThroughPerson.cs
  SuperNewRoles/Roles/Impostor/Assassin.cs
  SuperNewRoles/Roles/Impostor/EvilButtoner.cs
Labels: new feature/新機能

#448 Feature/CustomRpcSenderLog
  SuperNewRoles/Patch/ChatHandler.cs
Labels: new feature/新機能

#451 Refact/select task
  SuperNewRoles/Patch/SelectTask.cs
Labels: refactoring/リファクタリング, developmental change/開発的変更

#428 特殊モードで,「PC以外キック」とDebugモードがオフ, アガルタが有効でなおかつMiraが選択されている場合、警告を表示するように変更
  SuperNewRoles/Patch/ShareGameVersion.cs
  SuperNewRoles/Resources/TranslateFile.json
  TranslateData.xlsx
Labels: change/仕様変更

#425 /renameをゲストの時に使用できないようにし、警告文を表示するように変更した
  SuperNewRoles/Patch/ChatCommand.cs
  SuperNewRoles/Resources/TranslateFile.json
  TranslateData.xlsx
Labels: change/仕様変更

#458 fix/bug/サイドキックを作れる設定が取得されていない問題 #24(KuratoIssueNo.)
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
Labels: bug/バグ修正

#463 Refact/end game check
  SuperNewRoles/Mode/SuperHostRoles/EndGameCheck.cs
Labels: refactoring/リファクタリング

#464 MadRoleがサボを直せる関連の翻訳をExcelに追加&ドッペルゲンガーの翻訳を先に追加
  SuperNewRoles/Resources/TranslateFile.json
  TranslateData.xlsx
Labels: bug/バグ修正

#465 SubmergedとRPC番号が干渉していた問題を修正(Dekokiyoさんのコミット)
  SuperNewRoles/Modules/CustomRPC.cs
Labels: bug/バグ修正

#476 READMEにフォーマッター
  READMEs/README_en.md
  READMEs/README_jp.md
Labels: documentetion/文書の変更

#470 不要な変数削除
  SuperNewRoles/Mode/Zombie/FixedUpdate.cs
Labels: refactoring/リファクタリング, developmental change/開発的変更

#472 Refact/CustomOptionDate
  SuperNewRoles/Modules/CustomOptionDate.cs
Labels: refactoring/リファクタリング, developmental change/開発的変更

#478 Refact/not use if
  SuperNewRoles/Buttons/ButtonTime.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleChat.cs
  SuperNewRoles/Patch/MeetingHud.cs
  SuperNewRoles/Roles/CrewMate/Scientist.cs
  SuperNewRoles/Roles/Impostor/Hawk.cs
  SuperNewRoles/Roles/Impostor/MadRole/MadHawk.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
Labels: refactoring/リファクタリング

#479 Refact/url
  SuperNewRoles/Main.cs
  SuperNewRoles/Patch/ChatHandler.cs
  SuperNewRoles/Patch/TitleMenu.cs
Labels: refactoring/リファクタリング

#486 Refact/object init
  SuperNewRoles/Modules/CustomRegulation.cs
Labels: refactoring/リファクタリング

#492 Refact/custom color
  SuperNewRoles/CustomCosmetics/CustomColors.cs
Labels: refactoring/リファクタリング

#485 Refact/SetTarget
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Roles/Impostor/DoubleKiller.cs
  SuperNewRoles/Roles/Impostor/SecretlyKiller.cs
  SuperNewRoles/Roles/Impostor/Smasher.cs
  SuperNewRoles/Roles/Neutral/Fox.cs
  SuperNewRoles/Roles/Neutral/Jackal.cs
  SuperNewRoles/Roles/Neutral/JackalSeer.cs
  SuperNewRoles/Roles/Neutral/Revolutionist.cs
  SuperNewRoles/Roles/Neutral/TeleportingJackal.cs
Labels: refactoring/リファクタリング

#489 Refact/samurai
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Buttons/NormalButtonDestroy.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Roles/Impostor/Samurai.cs
  SuperNewRoles/Roles/Impostor/SelfBomber.cs
Labels: refactoring/リファクタリング

#482 エンドゲームの処理変更
  SuperNewRoles/Modules/CustomOptionDate.cs
  SuperNewRoles/Patch/EndGame.cs
  SuperNewRoles/Resources/TranslateFile.json
  SuperNewRoles/Roles/Role/RoleClass.cs
  TranslateData.xlsx
Labels: change/仕様変更, developmental change/開発的変更

#503 ビルドできない問題修正
  SuperNewRoles/Patch/PlayerControlPatch.cs
Labels: bug/バグ修正

#506 Logの時間表示を細かく
  SuperNewRoles/Debugger.cs
Labels: developmental change/開発的変更

#510 ReadMe公式鯖URL変更
  READMEs/README_en.md
  READMEs/README_jp.md
Labels: documentetion/文書の変更

#501 マトリョーシカで死体をかぶっている時に会議が開始した場合、被り先の状態が維持される問題を修正
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Roles/Impostor/Matryoshka.cs
Labels: bug/バグ修正

#512 フリーザーが正常に動作しない問題を修正
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Roles/Impostor/Freezer.cs
  SuperNewRoles/Roles/Impostor/Speeder.cs
Labels: bug/バグ修正, emergencyFix/緊急バグ修正

#515 ReadMeの変更をmaster直プルリクで行った為、master⇒developプルリク
  READMEs/README_en.md
  READMEs/README_jp.md
Labels: other/その他, documentetion/文書の変更

#513 Feature/player info
  SuperNewRoles/Patch/IntroPatch.cs
Labels: new feature/新機能

#514 Remove/no using log
  SuperNewRoles/CustomCosmetics/CustomPlate.cs
  SuperNewRoles/CustomCosmetics/CustomVisor.cs
  SuperNewRoles/Modules/CustomRegulation.cs
  SuperNewRoles/Modules/LateTask.cs
Labels: developmental change/開発的変更

#502 超リファクタリング
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Buttons/CustomButton.cs
  SuperNewRoles/Buttons/NormalButtonDestroy.cs
  SuperNewRoles/CustomCosmetics/CustomCosmeticsMenus/Patch/ObjectData.cs
  SuperNewRoles/CustomCosmetics/CustomHats.cs
  SuperNewRoles/CustomCosmetics/CustomPlate.cs
  SuperNewRoles/CustomCosmetics/DownLoadCustomPlate.cs
  SuperNewRoles/CustomCosmetics/DownLoadCustomVisor.cs
  SuperNewRoles/CustomObject/Arrow.cs
  SuperNewRoles/CustomObject/PlayerAnimation.cs
  SuperNewRoles/CustomObject/SluggerDeadbody.cs
  SuperNewRoles/Helpers/CachedPlayer.cs
  SuperNewRoles/Mode/Zombie/FixedUpdate.cs
  SuperNewRoles/PVCreator.cs
  SuperNewRoles/Patch/CustomOptionModel.cs
  SuperNewRoles/Patch/EndGame.cs
  SuperNewRoles/Patch/FixedUpdate.cs
  SuperNewRoles/Patch/HudManagerPatch.cs
  SuperNewRoles/Patch/IntroPatch.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Patch/Sabotage.cs
  SuperNewRoles/Patch/SetNames.cs
  SuperNewRoles/Patch/ShareGameVersion.cs
  SuperNewRoles/Patch/WallHack.cs
  SuperNewRoles/Patch/Zoom.cs
  SuperNewRoles/Roles/CrewMate/Psychometrist.cs
  SuperNewRoles/Roles/CrewMate/Shielder.cs
  SuperNewRoles/Roles/Impostor/DoubleKiller.cs
  SuperNewRoles/Roles/Impostor/Freezer.cs
  SuperNewRoles/Roles/Impostor/Matryoshka.cs
  SuperNewRoles/Roles/Impostor/Speeder.cs
  SuperNewRoles/Roles/Neutral/Arsonist.cs
  SuperNewRoles/Roles/Neutral/Hitman.cs
  SuperNewRoles/Roles/Neutral/SuicidalIdeation.cs
  SuperNewRoles/Roles/Neutral/Tuna.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: refactoring/リファクタリング, midway/開発途中, notMerge/マージしないで！, change/仕様変更, developmental change/開発的変更

#517 Refact/get many key down
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Patch/ChatPaste.cs
  SuperNewRoles/Patch/FixedUpdate.cs
Labels: refactoring/リファクタリング

#518 Remove/not used files
  build.cake
  nuget.config
Labels: refactoring/リファクタリング, developmental change/開発的変更

#519 Refa/debug manager
  SuperNewRoles/Patch/FixedUpdate.cs
Labels: refactoring/リファクタリング

#520 Refa/toilet open
  READMEs/README_jp.md
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Helpers/RPCHelper.cs
  SuperNewRoles/Patch/FixedUpdate.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
Labels: refactoring/リファクタリング, new feature/新機能

#521 ログに呼び出し元メソッドを出力
  SuperNewRoles/Debugger.cs
Labels: developmental change/開発的変更

#522 Refactoring/CreateMadMate[MadとFriendsを作るコードのメソッド化]
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Helpers/RPCHelper.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Roles/Impostor/MadRole/Madmate.cs
  SuperNewRoles/Roles/Neutral/Jackal.cs
Labels: Refactoring/リファクタリング, Developmental/開発的

#525 イビルハッカーがマッドを作るボタンの修正(不要なコードの消去&キーコードの変更)
  SuperNewRoles/Buttons/Buttons.cs
Labels: Fix/バグ修正

#528 カスタムオプションの表示がおかしい設定の修正
  SuperNewRoles/MapOptions/MapOption.cs
  SuperNewRoles/Modules/CustomOptionDate.cs
Labels: Fix/バグ修正

#487 Feature/seer support shr
  SuperNewRoles/Mode/SuperHostRoles/CoEnterVent.cs
  SuperNewRoles/Mode/SuperHostRoles/Helpers.cs
  SuperNewRoles/Mode/SuperHostRoles/MorePatch.cs
  SuperNewRoles/Mode/SuperHostRoles/NotBlackOut.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleHelper.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleSelectHandler.cs
  SuperNewRoles/Modules/CustomOptionDate.cs
  SuperNewRoles/Patch/DebugMode.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Roles/CrewMate/Seer.cs
Labels: Support SHR/SHR対応

#507 refa DarkKiller
  SuperNewRoles/Patch/FixedUpdate.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Roles/Impostor/DarkKiller.cs
Labels: Refactoring/リファクタリング

#530 Fix/connect killer
  SuperNewRoles/Patch/FixedUpdate.cs
  SuperNewRoles/Patch/ShipStatus.cs
  SuperNewRoles/Roles/Impostor/ConnectKiller.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: EmergencyFix/緊急バグ修正

#539 Refa/excel translate
  SuperNewRoles/ExcelTranslate.cs
Labels: Refactoring/リファクタリング

#538 refa/KunoichiKunaiButton
  SuperNewRoles/Buttons/Buttons.cs
Labels: Refactoring/リファクタリング

#537 Refa/photographer button
  SuperNewRoles/Buttons/Buttons.cs
Labels: Refactoring/リファクタリング

#536 Refa/doctor button
  SuperNewRoles/Buttons/Buttons.cs
Labels: Refactoring/リファクタリング

#540 新死因追加とか
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Helpers/RPCHelper.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Patch/EndGame.cs
  SuperNewRoles/Patch/FinalStatus.cs
  SuperNewRoles/Patch/LadderDead.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Resources/TranslateFile.json
  SuperNewRoles/Roles/CrewMate/Bestfalsecharge.cs
  SuperNewRoles/Roles/CrewMate/MeetingSheriff_Patch.cs
  SuperNewRoles/Roles/CrewMate/Nekomata.cs
  SuperNewRoles/Roles/Impostor/Samurai.cs
  SuperNewRoles/Roles/Impostor/SelfBomber.cs
  SuperNewRoles/Roles/Neutral/Spelunker.cs
  SuperNewRoles/Roles/Neutral/Tuna.cs
  TranslateData.xlsx
Labels: New feature/新機能

#535 Refa/string option enable patch
  SuperNewRoles/Patch/CustomOptionModel.cs
Labels: Refactoring/リファクタリング

#529 Fix/rpc show guard effect
  SuperNewRoles/Mode/SuperHostRoles/Helpers.cs
Labels: Fix/バグ修正

#504 Refa/ShapeshiftPatch
  SuperNewRoles/Patch/PlayerControlPatch.cs
Labels: Refactoring/リファクタリング

#541 Refa/role helper
  SNRDevTools/CreateRoleAdvanced.py
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: Refactoring/リファクタリング

#488 Refact/light patch and Inversion patch
  SuperNewRoles/Patch/InversionMap.cs
  SuperNewRoles/Patch/LightPatch.cs
  SuperNewRoles/Patch/ShipStatus.cs
Labels: Refactoring/リファクタリング

#533 マトリョーシカ修正
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Roles/Impostor/Matryoshka.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
Labels: EmergencyFix/緊急バグ修正

#493 冤罪師が正常に動作しない問題を修正&エラー表示が正常に動作しない問題を修正&殺し屋の勝利判定を変更
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Main.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Patch/EndGame.cs
  SuperNewRoles/Patch/LogoAndStamp.cs
  SuperNewRoles/Patch/ShareGameVersion.cs
  SuperNewRoles/Patch/WrapUp.cs
  SuperNewRoles/Roles/Neutral/FalseCharges.cs
Labels: Fix/バグ修正

#524 新役職「タスカー」
  SuperNewRoles/Buttons/NormalButtonDestroy.cs
  SuperNewRoles/MapCustoms/4_Airship/SecretRoom.cs
  SuperNewRoles/Modules/CustomOptionDate.cs
  SuperNewRoles/Patch/EndGame.cs
  SuperNewRoles/Patch/FixedUpdate.cs
  SuperNewRoles/Patch/SelectTask.cs
  SuperNewRoles/Patch/TaskCount.cs
  SuperNewRoles/Resources/TranslateFile.json
  SuperNewRoles/Roles/Role/RoleHelper.cs
  TranslateData.xlsx
Labels: New Role/新役職

#523 デフォルトキルクールより上だとデフォルトキルクールになってしまう問題を修正
  SuperNewRoles/Patch/PlayerControlPatch.cs
Labels: Fix/バグ修正

#542 Id変更
  SuperNewRoles/Modules/CustomOptionDate.cs
Labels: Fix/バグ修正

#462 NewRole/NekoKabocha
  READMEs/README_jp.md
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/Modules/CustomOptionDate.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/IntroDate.cs
  SuperNewRoles/Patch/FinalStatus.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Roles/CrewMate/Nekomata.cs
  SuperNewRoles/Roles/Impostor/NekoKabocha.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: New Role/新役職

#547 ジャッカルフレンズ作成時にアサシンだとアサシン会議が開始してしまう問題を修正
  SuperNewRoles/Patch/PlayerControlPatch.cs
Labels: Fix/バグ修正

#549 ドアーのドア状況をRpcで共有するように
  SuperNewRoles/Roles/CrewMate/Doorr.cs
Labels: Fix/バグ修正

#544 dotnet formatを使用
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/Buttons/ButtonTime.cs
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/CustomCosmetics/CustomCosmeticsMenus/Patch/ObjectData.cs
  SuperNewRoles/CustomCosmetics/CustomHats.cs
  SuperNewRoles/CustomCosmetics/CustomPlate.cs
  SuperNewRoles/CustomObject/Beacon.cs
  SuperNewRoles/CustomObject/Footprint.cs
  SuperNewRoles/CustomObject/PlayerAnimation.cs
  SuperNewRoles/CustomObject/SluggerDeadbody.cs
  SuperNewRoles/ExcelTranslate.cs
  SuperNewRoles/Helpers/RPCHelper.cs
  SuperNewRoles/MapCustoms/4_Airship/SecretRoom.cs
  SuperNewRoles/Mode/CopsRobbers/main.cs
  SuperNewRoles/Mode/SuperHostRoles/BlockTool.cs
  SuperNewRoles/Mode/SuperHostRoles/MurderPlayer.cs
  SuperNewRoles/Mode/SuperHostRoles/WrapUp.cs
  SuperNewRoles/Mode/Zombie/ZombieOptions.cs
  SuperNewRoles/Modules/CustomAnimation.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/CustomRegulation.cs
  SuperNewRoles/Modules/LateTask.cs
  SuperNewRoles/Modules/VentData.cs
  SuperNewRoles/PVCreator.cs
  SuperNewRoles/Patch/ChatCommand.cs
  SuperNewRoles/Patch/ClientOptionsPatch/ModOptions.cs
  SuperNewRoles/Patch/ClientOptionsPatch/VanillaOptions.cs
  SuperNewRoles/Patch/EndGame.cs
  SuperNewRoles/Patch/Fastboot.cs
  SuperNewRoles/Patch/FinalStatus.cs
  SuperNewRoles/Patch/HudManagerPatch.cs
  SuperNewRoles/Patch/KillOverlay.cs
  SuperNewRoles/Patch/LadderDead.cs
  SuperNewRoles/Patch/MeetingHud.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Patch/RandomSpawn.cs
  SuperNewRoles/Patch/SelectTask.cs
  SuperNewRoles/Patch/ShareGameVersion.cs
  SuperNewRoles/Patch/ShipStatus.cs
  SuperNewRoles/Roles/CrewMate/Bakery.cs
  SuperNewRoles/Roles/CrewMate/Nekomata.cs
  SuperNewRoles/Roles/CrewMate/Psychometrist.cs
  SuperNewRoles/Roles/CrewMate/SeeThroughPerson.cs
  SuperNewRoles/Roles/Impostor/Assassin.cs
  SuperNewRoles/Roles/Impostor/Doppelganger.cs
  SuperNewRoles/Roles/Impostor/EvilButtoner.cs
  SuperNewRoles/Roles/Impostor/MadRole/Madmate.cs
  SuperNewRoles/Roles/Impostor/NekoKabocha.cs
  SuperNewRoles/Roles/Impostor/Nun.cs
  SuperNewRoles/Roles/Impostor/Samurai.cs
  SuperNewRoles/Roles/Impostor/SelfBomber.cs
  SuperNewRoles/Roles/Impostor/ShiftActor.cs
  SuperNewRoles/Roles/Neutral/Arsonist.cs
  SuperNewRoles/Roles/Neutral/FalseCharges.cs
  SuperNewRoles/Roles/Neutral/Hitman.cs
  SuperNewRoles/Roles/Neutral/Revolutionist.cs
  SuperNewRoles/Roles/Neutral/Spelunker.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: Refactoring/リファクタリング
