Repository SuperNewRoles/SuperNewRoles, pull requests merged in 2022-06, with the labels that each got.

#97 (Fix/jackal seer)&(Fix/MadMaker)
  SuperNewRoles/Roles/RoleClass.cs
  SuperNewRoles/Roles/RoleHelper.cs
Labels: bug/バグ修正

#102 アーソニスト/Arsonist
  SNRDevTools/trans_00_en.txt
  SNRDevTools/trans_11_jp.txt
  SNRDevTools/transdate.txt
  SNRDevTools/translatedate.json
  SNRDevTools/transmoto.txt
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/EndGame/CustomEndReason.cs
  SuperNewRoles/EndGame/EndGame.cs
  SuperNewRoles/EndGame/FinalStatus.cs
  SuperNewRoles/Intro/IntroDate.cs
  SuperNewRoles/Mode/SuperHostRoles/CoEnterVent.cs
  SuperNewRoles/Mode/SuperHostRoles/EndGameCheck.cs
  SuperNewRoles/Mode/SuperHostRoles/FixedUpdate.cs
  SuperNewRoles/Mode/SuperHostRoles/MorePatch.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleSelectHandler.cs
  SuperNewRoles/Mode/SuperHostRoles/SyncSetting.cs
  SuperNewRoles/Mode/SuperHostRoles/WrapUp.cs
  SuperNewRoles/Patch/FixedUpdate.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Patch/SetNames.cs
  SuperNewRoles/Resources/ArsonistDouse.png
  SuperNewRoles/Resources/ArsonistIgnite.png
  SuperNewRoles/Resources/translatedate.json
  SuperNewRoles/Roles/Arsonist.cs
  SuperNewRoles/Roles/RoleClass.cs
  SuperNewRoles/Roles/RoleHelper.cs
Labels: NewRole/新役職, SNR/SNR, SHR/SHR

#113 [新モード]ケイドロ
  SNRDevTools/trans_00_en.txt
  SNRDevTools/trans_11_jp.txt
  SNRDevTools/transmoto.txt
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/CustomOption/CustomOptionModel.cs
  SuperNewRoles/EndGame/EndGame.cs
  SuperNewRoles/Helpers/AntiHackingBan.cs
  SuperNewRoles/Helpers/RPCHelper.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Mode/BattleRoyal/main.cs
  SuperNewRoles/Mode/CopsRobbers/RoleSelectHandler.cs
  SuperNewRoles/Mode/CopsRobbers/main.cs
  SuperNewRoles/Mode/ModeHandler.cs
  SuperNewRoles/Mode/SuperHostRoles/FixedUpdate.cs
  SuperNewRoles/Mode/SuperHostRoles/SyncSetting.cs
  SuperNewRoles/Mode/Zombie/FixedUpdate.cs
  SuperNewRoles/Mode/Zombie/ZombieOptions.cs
  SuperNewRoles/Patch/ChatCommand.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Patch/ReportDeadBody.cs
  SuperNewRoles/Roles/IntroHandler.cs
Labels: feature/新機能

#118 イビルハッカー/EvilHacker
  .vs/SuperNewRoles/v17/.suo
  SNRDevTools/trans_00_en.txt
  SNRDevTools/trans_11_jp.txt
  SNRDevTools/transdate.txt
  SNRDevTools/translatedate.json
  SNRDevTools/transmoto.txt
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/Intro/IntroDate.cs
  SuperNewRoles/Properties/launchSettings.json
  SuperNewRoles/Resources/translatedate.json
  SuperNewRoles/Roles/RoleClass.cs
  SuperNewRoles/Roles/RoleHelper.cs
Labels: NewRole/新役職, SNR/SNR

#119 侍SHR対応
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/Intro/IntroPatch.cs
  SuperNewRoles/Mode/SuperHostRoles/CoEnterVent.cs
  SuperNewRoles/Mode/SuperHostRoles/MorePatch.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleChat.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleSelectHandler.cs
  SuperNewRoles/Mode/SuperHostRoles/Roles/Samurai.cs
  SuperNewRoles/Mode/SuperHostRoles/SyncSetting.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Roles/RoleClass.cs
  SuperNewRoles/Roles/Samurai.cs
Labels: SHR/SHR

#125 3種端末時間制限
  SNRDevTools/trans_00_en.txt
  SNRDevTools/trans_11_jp.txt
  SNRDevTools/transdate.txt
  SNRDevTools/translatedate.json
  SNRDevTools/transmoto.txt
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/MapOptions/MapOption.cs
  SuperNewRoles/MapOptions/ReatrictDevices/AdminPatch.cs
  SuperNewRoles/MapOptions/ReatrictDevices/CameraPatch.cs
  SuperNewRoles/MapOptions/ReatrictDevices/VitalPatch.cs
  SuperNewRoles/Resources/translatedate.json
Labels: feature/新機能

#92 Feature/create role advance
  .vs/SuperNewRoles/v17/.suo
  SNRDevTools/CreateRoleAdvance -InstallLibrary.bat
  SNRDevTools/CreateRoleAdvance.py
  SNRDevTools/CreateRoleAdvance/Config.ini
  SNRDevTools/CreateRoleAdvance/ReadMe.txt
  SNRDevTools/CreateRoleAdvance/Resources/Pictures/icon.png
  SNRDevTools/CreateRoleAdvance/仕様書.txt
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/Roles/RoleHelper.cs
  SuperNewRoles/Roles/Sheriff.cs
  SuperNewRoles/obj/Debug/netstandard2.1/SuperNewRoles.GeneratedMSBuildEditorConfig.editorconfig
  SuperNewRoles/obj/Debug/netstandard2.1/SuperNewRoles.assets.cache
Labels: feature/新機能

#127 Fix/ykundes bepln ex
  READMEs/README_jp.md
  SNRDevTools/trans_00_en.txt
  SNRDevTools/trans_11_jp.txt
  SNRDevTools/transdate.txt
  SNRDevTools/translatedate.json
  SNRDevTools/transmoto.txt
  SuperNewRoles/MapOptions/MapOption.cs
  SuperNewRoles/MapOptions/ReatrictDevices/AdminPatch.cs
  SuperNewRoles/Resources/translatedate.json
  SuperNewRoles/obj/Debug/netstandard2.1/SuperNewRoles.GeneratedMSBuildEditorConfig.editorconfig
  SuperNewRoles/obj/Debug/netstandard2.1/SuperNewRoles.assets.cache
Labels: other/その他

#139 MadStuntman.csを削除
  SuperNewRoles/Roles/MadStuntMan.cs
Labels: other/その他

#141 C#のバージョン変更
  Directory.Build.props
Labels: emergency/緊急

#144 エアーシップにベントを追加
  Directory.build.props
  SNRDevTools/trans_00_en.txt
  SNRDevTools/trans_11_jp.txt
  SNRDevTools/transdate.txt
  SNRDevTools/translatedate.json
  SNRDevTools/transmoto.txt
  SuperNewRoles/MapOptions/MapOption.cs
  SuperNewRoles/MapRemodeling/AdditionalVent.cs
  SuperNewRoles/Resources/translatedate.json
  SuperNewRoles/Roles/RoleClass.cs
  SuperNewRoles/obj/Debug/netstandard2.1/SuperNewRoles.GeneratedMSBuildEditorConfig.editorconfig
  SuperNewRoles/obj/Debug/netstandard2.1/SuperNewRoles.assets.cache
Labels: feature/新機能

#130 機器制限諸々修正
  .vs/SuperNewRoles/v17/.suo
  SuperNewRoles/Helpers/CachedPlayer.cs
  SuperNewRoles/MapOptions/DeviceClass.cs
  SuperNewRoles/MapOptions/MapOption.cs
  SuperNewRoles/MapOptions/ReatrictDevices/AdminPatch.cs
  SuperNewRoles/MapOptions/ReatrictDevices/CameraPatch.cs
  SuperNewRoles/MapOptions/ReatrictDevices/VitalPatch.cs
Labels: bug/バグ修正, emergency/緊急

#131 ベントメーカーの未翻訳を修正
  SNRDevTools/trans_00_en.txt
  SNRDevTools/trans_11_jp.txt
  SNRDevTools/transdate.txt
  SNRDevTools/translatedate.json
  SNRDevTools/transmoto.txt
  SuperNewRoles/Resources/translatedate.json
Labels: bug/バグ修正

#153 ビルドできない問題を修正
  SuperNewRoles/SuperNewRoles.csproj
Labels: emergency/緊急

#150 ベントを追加・即開始
  SNRDevTools/trans_00_en.txt
  SNRDevTools/trans_11_jp.txt
  SNRDevTools/transdate.txt
  SNRDevTools/translatedate.json
  SNRDevTools/transmoto.txt
  SuperNewRoles/MapOptions/MapOption.cs
  SuperNewRoles/MapRemodeling/AdditionalVent.cs
  SuperNewRoles/Patch/GameStartPatch.cs
  SuperNewRoles/Resources/translatedate.json
Labels: feature/新機能

#160 CRAバグ修正
  SNRDevTools/CreateRoleAdvanced.py
Labels: bug/バグ修正, feature/新機能, emergency/緊急

#162 マグロ/Tuna
  SNRDevTools/trans_00_en.txt
  SNRDevTools/trans_11_jp.txt
  SNRDevTools/transdate.txt
  SNRDevTools/translatedate.json
  SNRDevTools/transmoto.txt
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/EndGame/CustomEndReason.cs
  SuperNewRoles/EndGame/EndGame.cs
  SuperNewRoles/Intro/IntroDate.cs
  SuperNewRoles/Patch/ChatHandler.cs
  SuperNewRoles/Resources/translatedate.json
  SuperNewRoles/Roles/RoleClass.cs
  SuperNewRoles/Roles/RoleHelper.cs
  SuperNewRoles/Roles/Tuna.cs
Labels: NewRole/新役職

#161 設定がオフでも適応される問題を修正
  SuperNewRoles/MapOptions/ReatrictDevices/AdminPatch.cs
  SuperNewRoles/MapOptions/ReatrictDevices/CameraPatch.cs
  SuperNewRoles/MapOptions/ReatrictDevices/VitalPatch.cs
  SuperNewRoles/MapOptions/SabotagePatch.cs
  SuperNewRoles/obj/Debug/netstandard2.1/SuperNewRoles.GeneratedMSBuildEditorConfig.editorconfig
  SuperNewRoles/obj/Debug/netstandard2.1/SuperNewRoles.assets.cache
Labels: bug/バグ修正

#171 黒猫
  SNRDevTools/trans_00_en.txt
  SNRDevTools/trans_11_jp.txt
  SNRDevTools/transdate.txt
  SNRDevTools/translatedate.json
  SNRDevTools/transmoto.txt
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/EndGame/EndGame.cs
  SuperNewRoles/Intro/IntroDate.cs
  SuperNewRoles/Intro/IntroPatch.cs
  SuperNewRoles/Mode/SuperHostRoles/FixedUpdate.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleChat.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleSelectHandler.cs
  SuperNewRoles/Mode/SuperHostRoles/Roles/Nekomata.cs
  SuperNewRoles/Mode/SuperHostRoles/SyncSetting.cs
  SuperNewRoles/Patch/SelectTask.cs
  SuperNewRoles/Patch/SetNames.cs
  SuperNewRoles/Resources/translatedate.json
  SuperNewRoles/Roles/BlackCat.cs
  SuperNewRoles/Roles/Clergyman.cs
  SuperNewRoles/Roles/CountChanger.cs
  SuperNewRoles/Roles/Madmate.cs
  SuperNewRoles/Roles/MeetingSheriff_Patch.cs
  SuperNewRoles/Roles/Nekomata.cs
  SuperNewRoles/Roles/RoleClass.cs
  SuperNewRoles/Roles/RoleHelper.cs
  SuperNewRoles/Roles/Sheriff.cs
Labels: NewRole/新役職

#168 TORとTORGMのハット追加
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/CustomCosmetics/CustomHats.cs
Labels: feature/新機能

#165 新役職「マフィア」
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/Helpers/CachedPlayer.cs
  SuperNewRoles/Helpers/DesyncHelpers.cs
  SuperNewRoles/Helpers/RPCHelper.cs
  SuperNewRoles/Intro/IntroDate.cs
  SuperNewRoles/Mode/BattleRoyal/main.cs
  SuperNewRoles/Mode/SuperHostRoles/FixedUpdate.cs
  SuperNewRoles/Mode/SuperHostRoles/MorePatch.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleSelectHandler.cs
  SuperNewRoles/Mode/SuperHostRoles/SyncSetting.cs
  SuperNewRoles/Patch/FixedUpdate.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Roles/Mafia.cs
  SuperNewRoles/Roles/RoleClass.cs
  SuperNewRoles/Roles/RoleHelper.cs
  SuperNewRoles/obj/Debug/netstandard2.1/SuperNewRoles.GeneratedMSBuildEditorConfig.editorconfig
Labels: NewRole/新役職

#173 バグ修正
  SuperNewRoles/AllRoleSetClass.cs
  SuperNewRoles/BotManager.cs
  SuperNewRoles/CustomCosmetics/CustomColors.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/EndGame/EndGame.cs
  SuperNewRoles/Helpers/RPCHelper.cs
  SuperNewRoles/MapOptions/MapOption.cs
  SuperNewRoles/Mode/BattleRoyal/main.cs
  SuperNewRoles/Mode/CopsRobbers/main.cs
  SuperNewRoles/Mode/NotImpostorCheck/main.cs
  SuperNewRoles/Mode/SuperHostRoles/EndGameCheck.cs
  SuperNewRoles/Mode/SuperHostRoles/RPCSetTask.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleSelectHandler.cs
  SuperNewRoles/Mode/SuperHostRoles/WrapUp.cs
  SuperNewRoles/Mode/Werewolf/RoleSelectHandler.cs
  SuperNewRoles/Mode/Werewolf/main.cs
  SuperNewRoles/Mode/Zombie/main.cs
  SuperNewRoles/Patch/MeetingHud.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
  SuperNewRoles/Roles/Arsonist.cs
  SuperNewRoles/Roles/CountChanger.cs
  SuperNewRoles/Roles/Demon.cs
  SuperNewRoles/Roles/FalseCharges.cs
  SuperNewRoles/Roles/Jackal.cs
  SuperNewRoles/Roles/JackalSeer.cs
  SuperNewRoles/Roles/RoleClass.cs
  SuperNewRoles/Roles/RoleHelper.cs
  SuperNewRoles/Roles/TeleportingJackal.cs
  SuperNewRoles/Sabotage/CognitiveDeficit/main.cs
Labels: bug/バグ修正

#190 Feature/KAIZOUDOShortcut
  Directory.Build.props
  Directory.build.props
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/Main.cs
  SuperNewRoles/MapOptions/AddVital.cs
  SuperNewRoles/MapOptions/MapOption.cs
  SuperNewRoles/MapOptions/ReatrictDevices/AdminPatch.cs
  SuperNewRoles/MapOptions/ReatrictDevices/CameraPatch.cs
  SuperNewRoles/MapOptions/ReatrictDevices/VitalPatch.cs
  SuperNewRoles/Patch/ControllerManagerPatch.cs
  SuperNewRoles/Patch/GameStartPatch.cs
  SuperNewRoles/Patch/LogoAndStamp.cs
  SuperNewRoles/SuperNewRoles.csproj
  SuperNewRoles/obj/Debug/netstandard2.1/SuperNewRoles.GeneratedMSBuildEditorConfig.editorconfig
  SuperNewRoles/packages.lock.json
Labels: feature/新機能

#191 Refa/isMadRole
  SuperNewRoles/Patch/FixedUpdate.cs
  SuperNewRoles/Roles/Fox.cs
  SuperNewRoles/Roles/Minimalist.cs
  SuperNewRoles/Roles/RoleHelper.cs
  SuperNewRoles/Roles/Sheriff.cs
Labels: Refactoring/リファクタリング

#188 v1.4.0.9
  SNRDevTools/trans_00_en.txt
  SNRDevTools/trans_11_jp.txt
  SNRDevTools/transdate.txt
  SNRDevTools/translatedate.json
  SNRDevTools/transmoto.txt
  SuperNewRoles/CustomCosmetics/CustomHats.cs
  SuperNewRoles/CustomOption/CustomOptionDate.cs
  SuperNewRoles/CustomRPC/CustomRPC.cs
  SuperNewRoles/EndGame/EndGame.cs
  SuperNewRoles/Main.cs
  SuperNewRoles/MapOptions/AddVital.cs
  SuperNewRoles/MapOptions/MapOption.cs
  SuperNewRoles/MapOptions/ReatrictDevices/AdminPatch.cs
  SuperNewRoles/MapOptions/ReatrictDevices/CameraPatch.cs
  SuperNewRoles/MapOptions/ReatrictDevices/VitalPatch.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Mode/NotImpostorCheck/NameSet.cs
  SuperNewRoles/Mode/NotImpostorCheck/SelectRolePatch.cs
  SuperNewRoles/Mode/SuperHostRoles/Chat.cs
  SuperNewRoles/Mode/SuperHostRoles/EndGameCheck.cs
  SuperNewRoles/Mode/SuperHostRoles/FixedUpdate.cs
  SuperNewRoles/Mode/Zombie/FixedUpdate.cs
  SuperNewRoles/Patch/ClientOptionsPatch.cs
  SuperNewRoles/Patch/DebugMode.cs
  SuperNewRoles/Patch/FixedUpdate.cs
  SuperNewRoles/Patch/SetNames.cs
  SuperNewRoles/Resources/translatedate.json
  SuperNewRoles/Roles/Fox.cs
  SuperNewRoles/Roles/Jackal.cs
  SuperNewRoles/Roles/JackalSeer.cs
  SuperNewRoles/Roles/Nekomata.cs
  SuperNewRoles/Roles/Pursuer.cs
  SuperNewRoles/Roles/Scientist.cs
  SuperNewRoles/Roles/SoothSayer_Patch.cs
  SuperNewRoles/Roles/TeleportingJackal.cs
Labels: Merge to master/マスターにマージ

#200 標本室にバイタル移動(ポーラス)
  README.md
  READMEs/README_jp.md
  SNRDevTools/trans_00_en.txt
  SNRDevTools/trans_11_jp.txt
  SNRDevTools/transdate.txt
  SNRDevTools/translatedate.json
  SNRDevTools/transmoto.txt
  SuperNewRoles/MapOptions/MapOption.cs
  SuperNewRoles/MapOptions/MapRemodeling/AdditionalVent.cs
  SuperNewRoles/MapOptions/MapRemodeling/SpecimenVital.cs
  SuperNewRoles/MapOptions/MapRemodeling/main.cs
  SuperNewRoles/Resources/translatedate.json
  SuperNewRoles/Roles/RoleClass.cs
Labels: feature/新機能

#204 マッドメーカーと村長が自爆でBANされる問題を修正
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Patch/PlayerControlPatch.cs
Labels: bug/バグ修正
