Repository SuperNewRoles/SuperNewRoles, pull requests merged in 2022-11, with the labels that each got.

#706 master => Develop_fix
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/CustomObject/BloodStain.cs
  SuperNewRoles/Main.cs
  SuperNewRoles/MapOptions/DeviceClass.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/IntroData.cs
  SuperNewRoles/Modules/ModTranslation.cs
  SuperNewRoles/Modules/SetNames.cs
  SuperNewRoles/Patches/DebugModePatch.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/FixedUpdatePatch.cs
  SuperNewRoles/Patches/IntroPatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/SelectTaskPatch.cs
  SuperNewRoles/Patches/ShipStatusPatch.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Resources/BloodStain.png
  SuperNewRoles/Resources/CreateMadmateButton.png
  SuperNewRoles/Resources/PenguinButton_1.png
  SuperNewRoles/Resources/PenguinButton_2.png
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Resources/VampireCreateDependentsButton.png
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/CrewMate/HamburgerShop.cs
  SuperNewRoles/Roles/Impostor/Nun.cs
  SuperNewRoles/Roles/Impostor/Penguin.cs
  SuperNewRoles/Roles/Impostor/Vampire.cs
  SuperNewRoles/Roles/Neutral/Cupid.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  SuperNewRoles/Roles/Role/SetTarget.cs
Labels: Merge to Dev/開発版にマージ

#713 ホーク3種と殺し屋のデフォルト値を調整
  SuperNewRoles/Modules/CustomOptionHolder.cs
Labels: Adjustment/調整

#709 眷属のタスククリア&ヴァンパイアと眷属のイントロを変更
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: Fix/バグ修正

#664 Refa/not used method
  SuperNewRoles/Buttons/OldModeButtons.cs
  SuperNewRoles/Helpers/EnumerationHelpers.cs
  SuperNewRoles/Mode/NotImpostorCheck/NotBlackOut.cs
  SuperNewRoles/Mode/SuperHostRoles/MorePatch.cs
  SuperNewRoles/Mode/SuperHostRoles/SyncSetting.cs
  SuperNewRoles/Modules/AutoUpdate.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/MeetingHudPatch.cs
Labels: Refactoring/リファクタリング

#607 Refa/end game patch
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Patches/EndGamePatch.cs
Labels: Refactoring/リファクタリング

#716 CheckMuderAttempt-->CheckMurderAttempt
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Roles/Impostor/Kunoichi.cs
Labels: Developmental/開発的

#717 CustomRPCにSetMapIdが重複していた為build不能だった問題を修正
  SuperNewRoles/Modules/CustomRPC.cs
Labels: Fix/バグ修正

#725 クルー勝利時に翻訳が正しく反映されていなかったのを修正
  SuperNewRoles/Patches/EndGamePatch.cs
Labels: Documentetion/文書の変更

#734 中身のないメソッドを削除
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/CustomCosmetics/CustomHats.cs
  SuperNewRoles/Patches/LogoAndStampPatch.cs
Labels: Refactoring/リファクタリング

#737 死因の未翻訳を修正
  SuperNewRoles/Resources/Translate.csv
Labels: Fix/バグ修正

#730 joystickkeyに問題があったボタンを修正
  SuperNewRoles/Buttons/Buttons.cs
Labels: Fix/バグ修正

#731 推奨拡張機能追加
  .vscode/extensions.json
Labels: Developmental/開発的

#722 シェリフ系役職が誤爆時対象を殺す設定を追加
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/CrewMate/MeetingSheriff_Patch.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
Labels: Fix/バグ修正, New feature/新機能

#742 Platform log
  SuperNewRoles/Main.cs
Labels: Developmental/開発的

#727 IsPlayerを削除
  SuperNewRoles/Mode/CopsRobbers/RoleSelectHandler.cs
  SuperNewRoles/Mode/CopsRobbers/main.cs
  SuperNewRoles/Mode/SuperHostRoles/FixedUpdate.cs
  SuperNewRoles/Mode/SuperHostRoles/Intro.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleSelectHandler.cs
  SuperNewRoles/Mode/SuperHostRoles/Roles/Nekomata.cs
  SuperNewRoles/Mode/SuperHostRoles/SyncSetting.cs
  SuperNewRoles/Modules/BotManager.cs
  SuperNewRoles/Patches/ChatHandlerPatch.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/MeetingHudPatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/TaskCountPatch.cs
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/CrewMate/MeetingSheriff_Patch.cs
  SuperNewRoles/Roles/Impostor/Mafia.cs
Labels: Refactoring/リファクタリング

#733 イビルハッカーがアドミン使用中に移動できる
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Patches/MapPatch.cs
  SuperNewRoles/Resources/Translate.csv
Labels: New feature/新機能

#735 Refa/ship status
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Buttons/VentAndSabo.cs
  SuperNewRoles/Helpers/MapUtilities.cs
  SuperNewRoles/Helpers/RPCHelper.cs
  SuperNewRoles/MapCustoms/00_AllMaps/AdditionalVent.cs
  SuperNewRoles/MapCustoms/4_Airship/AddWireTasks.cs
  SuperNewRoles/MapCustoms/4_Airship/SecretRoom.cs
  SuperNewRoles/MapCustoms/main.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Modules/PVCreator.cs
  SuperNewRoles/Modules/VentData.cs
  SuperNewRoles/Patches/ShipStatusPatch.cs
  SuperNewRoles/Patches/TaskCountPatch.cs
  SuperNewRoles/Roles/CrewMate/HamburgerShop.cs
  SuperNewRoles/Roles/CrewMate/SeeThroughPerson.cs
  SuperNewRoles/Roles/Neutral/Photographer.cs
  SuperNewRoles/Roles/Neutral/Revolutionist.cs
Labels: Refactoring/リファクタリング

#738 Submerged delete
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Buttons/VentAndSabo.cs
  SuperNewRoles/CustomObject/Beacon.cs
  SuperNewRoles/Main.cs
  SuperNewRoles/MapOptions/MapOption.cs
  SuperNewRoles/MapOptions/RandomMap.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/SubmergedCompatibility.cs
  SuperNewRoles/Patches/LogoAndStampPatch.cs
  SuperNewRoles/Patches/ShipStatusPatch.cs
  SuperNewRoles/Patches/TitleMenuPatch.cs
  SuperNewRoles/Resources/Translate.csv
Labels: Change/変更

#740 Fix/trans final results
  SuperNewRoles/Resources/Translate.csv
Labels: Fix/バグ修正

#732 HudManagerをFastDestroyableSingleton化
  SuperNewRoles/CustomObject/Beacon.cs
  SuperNewRoles/CustomObject/Footprint.cs
  SuperNewRoles/MapCustoms/4_Airship/SecretRoom.cs
  SuperNewRoles/Modules/CustomOverlay.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/Zoom.cs
  SuperNewRoles/Roles/Impostor/Kunoichi.cs
  SuperNewRoles/Roles/Impostor/Mafia.cs
Labels: Refactoring/リファクタリング

#756 新色「小豆」「雪」を追加
  SuperNewRoles/CustomCosmetics/CustomColors.cs
  SuperNewRoles/Resources/Translate.csv
Labels: Other/その他

#757 MODの設定のデフォルト設定を変更
  SuperNewRoles/MapOptions/MapOption.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
Labels: Adjustment/調整

#758 正常に自動アップデートが動作しなかった問題を修正
  SuperNewRoles/Modules/AutoUpdate.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: Fix/バグ修正

#761 シフトアクターが正常にアサインされない問題を修正
  SuperNewRoles/Roles/Impostor/ShiftActor.cs
Labels: Fix/バグ修正

#760 ペインター：足跡の大きさを変更
  SuperNewRoles/Roles/CrewMate/Painter.cs
Labels: Change/変更

#728 Change/rename local
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Roles/Neutral/Vulture.cs
Labels: Refactoring/リファクタリング

#741 Refa/controller manager
  SuperNewRoles/MapOptions/DeviceClass.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Patches/ControllerManagerPatch.cs
  SuperNewRoles/Patches/DebugModePatch.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/FixedUpdatePatch.cs
  SuperNewRoles/Patches/LogoAndStampPatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
Labels: Refactoring/リファクタリング

#584 馬ボタン変更
  SuperNewRoles/Resources/HorseModeButtonOff.png
Labels: Change/変更

#765 ドクターの設定の翻訳を変更
  SuperNewRoles/Resources/Translate.csv
Labels: Translation/翻訳

#768 会議判定が正常に動作していない問題を修正
  SuperNewRoles/Patches/WrapUpPatch.cs
Labels: Fix/バグ修正, EmergencyFix/緊急バグ修正

#775 not load custom cosmetics when debug mode
  SuperNewRoles/CustomCosmetics/CustomHats.cs
  SuperNewRoles/CustomCosmetics/CustomPlate.cs
  SuperNewRoles/CustomCosmetics/CustomVisor.cs
Labels: Developmental/開発的

#774 バニラの設定変更が正常に動作しない問題を修正
  SuperNewRoles/Modules/CustomOptionModel.cs
Labels: Fix/バグ修正

#773 聖職者で正常にクールタイムがリセットされない問題を修正
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Modules/CustomRPC.cs
Labels: Fix/バグ修正

#770 スラッガーが正常にアニメーションされない問題を修正
  SuperNewRoles/CustomObject/PlayerAnimation.cs
Labels: Fix/バグ修正

#767 Idが重複している問題を修正
  SuperNewRoles/Modules/CustomOptionHolder.cs
Labels: Fix/バグ修正

#766 Update for SChinese translation
  SuperNewRoles/Resources/Translate.csv
Labels: Translation/翻訳

#763 Refa/fast destroyable singleton
  SuperNewRoles/Patches/FreeNamePatch.cs
  SuperNewRoles/Patches/GameStartPatch.cs
  SuperNewRoles/Roles/Impostor/ShiftActor.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: Refactoring/リファクタリング

#762 Feature/airship anti task over wall
  SuperNewRoles/MapCustoms/MapCustom.cs
  SuperNewRoles/MapCustoms/main.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Resources/Translate.csv
Labels: New feature/新機能

#759 機器制限完成の巻
  SuperNewRoles/MapOptions/DeviceClass.cs
  SuperNewRoles/MapOptions/MapOption.cs
  SuperNewRoles/Mode/SuperHostRoles/FixedUpdate.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Resources/Translate.csv
Labels: New feature/新機能

#764 Developers update
  CreditsData.json
  READMEs/README_en.md
  READMEs/README_jp.md
Labels: Documentetion/文書の変更

#776 Version up 1.4.3.0
  SuperNewRoles/SuperNewRoles.csproj
Labels: Version upgrade/バージョンアップ

#781 CustomRPCにCommaが足りずbuildできない問題を修正
  SuperNewRoles/Modules/CustomRPC.cs
Labels: Fix/バグ修正

#782 developの修正を反映(buildできない問題を修正)
  SuperNewRoles/Modules/CustomRPC.cs
Labels: develop to master/マスターにマージ

#783 id修正(Ver1.4.3.0最終調整)
  SuperNewRoles/MapCustoms/MapCustom.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
Labels: Fix/バグ修正

#785 develop => Master (Ver1.4.3.0最終調整)
  SuperNewRoles/MapCustoms/MapCustom.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
Labels: develop to master/マスターにマージ

#787 develop => Develop_fix
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/CustomCosmetics/CustomColors.cs
  SuperNewRoles/MapCustoms/MapCustom.cs
  SuperNewRoles/MapCustoms/main.cs
  SuperNewRoles/MapOptions/DeviceClass.cs
  SuperNewRoles/MapOptions/MapOption.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/SetNames.cs
  SuperNewRoles/Patches/MapPatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/CrewMate/MeetingSheriff_Patch.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: develop to Dev_fix&fea/開発版の反映

#788 JackalとJackalSeerのボタンリセットを分離した&SKCoolを個別設定にした
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Roles/Neutral/Jackal.cs
  SuperNewRoles/Roles/Neutral/JackalSeer.cs
Labels: Fix/バグ修正

#789 機器の時間制限で死亡者も対象になってしまう問題を修正
  SuperNewRoles/MapOptions/DeviceClass.cs
Labels: Fix/バグ修正

#778 ShowFlashを最初にクローンし、SetActive(true/false)する形式に変更
  SuperNewRoles/Roles/CrewMate/Seer.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
Labels: Fix/バグ修正

#779 Fix/haison log and trans
  SuperNewRoles/Patches/ControllerManagerPatch.cs
  SuperNewRoles/Resources/Translate.csv
Labels: Developmental/開発的

#792 侍の修正_必殺技の回数制限を当初の仕様のはずの1回に修正&侍の必殺技対象にFinalStatusが出るよう修正
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Mode/SuperHostRoles/Roles/Samurai.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/Impostor/Samurai.cs
Labels: Fix/バグ修正

#793 中国語がないのにCommaがあった部分を修正
  SuperNewRoles/Resources/Translate.csv
Labels: Fix/バグ修正

#794 Develop_fix => Master(Ver.1.4.3.1準備)
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/MapCustoms/main.cs
  SuperNewRoles/MapOptions/DeviceClass.cs
  SuperNewRoles/Mode/SuperHostRoles/Roles/Samurai.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Patches/ControllerManagerPatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/CrewMate/Seer.cs
  SuperNewRoles/Roles/Impostor/Samurai.cs
  SuperNewRoles/Roles/Impostor/Vampire.cs
  SuperNewRoles/Roles/Neutral/Jackal.cs
  SuperNewRoles/Roles/Neutral/JackalSeer.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
Labels: Dev_fix&fea to develop/開発版にマージ

#795 VersionUp1431
  SuperNewRoles/SuperNewRoles.csproj
Labels: Version upgrade/バージョンアップ

#796 develop => Master(Ver.1.4.3.1)
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/MapCustoms/main.cs
  SuperNewRoles/MapOptions/DeviceClass.cs
  SuperNewRoles/Mode/SuperHostRoles/Roles/Samurai.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Patches/ControllerManagerPatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/CrewMate/Seer.cs
  SuperNewRoles/Roles/Impostor/Samurai.cs
  SuperNewRoles/Roles/Impostor/Vampire.cs
  SuperNewRoles/Roles/Neutral/Jackal.cs
  SuperNewRoles/Roles/Neutral/JackalSeer.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: develop to master/マスターにマージ

#799 Update for SChinese Translation
  SuperNewRoles/Resources/Translate.csv
Labels: Translation/翻訳

#800 master => develop (Ver_1.4.3.1_中国語翻訳対応)
  SuperNewRoles/Resources/Translate.csv
Labels: Dev_fix&fea to develop/開発版にマージ

#798 Master => Develop_fix(Ver.1.4.3.1)
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/SuperNewRoles.csproj
Labels: develop to Dev_fix&fea/開発版の反映

#797 Master => Develop_feature(Ver.1.4.3.1)
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/MapCustoms/main.cs
  SuperNewRoles/MapOptions/DeviceClass.cs
  SuperNewRoles/Mode/SuperHostRoles/Roles/Samurai.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Patches/ControllerManagerPatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/CrewMate/Seer.cs
  SuperNewRoles/Roles/Impostor/Samurai.cs
  SuperNewRoles/Roles/Impostor/Vampire.cs
  SuperNewRoles/Roles/Neutral/Jackal.cs
  SuperNewRoles/Roles/Neutral/JackalSeer.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: develop to Dev_fix&fea/開発版の反映

#687 Change/editorconfig
  .editorconfig
  SuperNewRoles/Buttons/OldModeButtons.cs
  SuperNewRoles/CustomCosmetics/CustomHats.cs
  SuperNewRoles/CustomCosmetics/CustomPlate.cs
  SuperNewRoles/CustomCosmetics/CustomVisor.cs
  SuperNewRoles/CustomObject/Footprint.cs
  SuperNewRoles/CustomObject/PlayerAnimation.cs
  SuperNewRoles/CustomObject/SluggerDeadbody.cs
  SuperNewRoles/CustomObject/WaveCannonObject.cs
  SuperNewRoles/Mode/CopsRobbers/CheckEndGame.cs
  SuperNewRoles/Mode/CopsRobbers/RoleSystem.cs
  SuperNewRoles/Mode/CopsRobbers/main.cs
  SuperNewRoles/Mode/Detective/WinCheckPatch.cs
  SuperNewRoles/Mode/HideAndSeek/main.cs
  SuperNewRoles/Mode/ModeHandler.cs
  SuperNewRoles/Mode/NotImpostorCheck/WinCheck.cs
  SuperNewRoles/Mode/RandomColor/main.cs
  SuperNewRoles/Mode/Werewolf/main.cs
  SuperNewRoles/Modules/ModTranslation.cs
  SuperNewRoles/Modules/PVCreator.cs
  SuperNewRoles/Patches/ClientOptionsPatch/ModOptions.cs
  SuperNewRoles/Patches/ClientOptionsPatch/VanillaOptions.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/SNROnlySearch.cs
  SuperNewRoles/Patches/SabotagePatch.cs
  SuperNewRoles/Patches/ShipStatusPatch.cs
  SuperNewRoles/Roles/Attribute/Guesser.cs
  SuperNewRoles/Roles/CrewMate/Clergyman.cs
  SuperNewRoles/Roles/CrewMate/Knight.cs
  SuperNewRoles/Roles/CrewMate/MeetingSheriff_Patch.cs
  SuperNewRoles/Roles/CrewMate/Sheriff.cs
  SuperNewRoles/Roles/Impostor/Camouflager.cs
  SuperNewRoles/Roles/Impostor/NekoKabocha.cs
  SuperNewRoles/Roles/Impostor/Nun.cs
  SuperNewRoles/Roles/Neutral/Jackal.cs
  SuperNewRoles/Roles/Neutral/WaveCannonJackal.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  SuperNewRoles/Sabotage/SabotageManager.cs
Labels: Refactoring/リファクタリング

#806 シーアの霊魂が追放者がいないと表示されない問題の修正
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Roles/CrewMate/Seer.cs
Labels: Fix/バグ修正

#809 refact CustomColors
  SuperNewRoles/CustomCosmetics/CustomColors.cs
  SuperNewRoles/Resources/Translate.csv
Labels: Refactoring/リファクタリング

#813 ヴァンパイアのWarpUpで追放者がいない場合ぬるぬるになっていた問題を修正
  SuperNewRoles/Patches/WrapUpPatch.cs
Labels: Fix/バグ修正

#817 master => Develop_fix(ver1.4.3.1)
  SuperNewRoles/CustomCosmetics/CustomColors.cs
Labels: develop to Dev_fix&fea/開発版の反映

#819 ボタンを非表示にするのを修正
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Resources/Translate.csv
Labels: Change/変更
