Repository SuperNewRoles/SuperNewRoles, pull requests merged in 2023-04, with the labels that each got.

#968 ボタンを自動で位置調整するように。ついでにボタンを震えさせる関数の追加
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Buttons/CustomButton.cs
  SuperNewRoles/Roles/CrewMate/Squid.cs
Labels: Add feature/既存の機能に追加

#1108 シェリフのキル能力のアウトラインを修正
  SuperNewRoles/Buttons/Buttons.cs
Labels: Fix/バグ修正

#1109 ゲッサーにクルーメイトを打てるかどうかの設定を追加
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/Attribute/Guesser.cs
Labels: Change/変更

#1110 Update for SChinese Translation
  SuperNewRoles/Resources/Translate.csv
Labels: Translation/翻訳

#1111 Update for TChinese Translation
  SuperNewRoles/Resources/Translate.csv
Labels: Translation/翻訳

#1105 master => Develop_feature [ver1.7.0.0]
  SuperNewRoles/Patches/HorseModePatch.cs
  SuperNewRoles/Patches/IntroPatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/Impostor/Matryoshka.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: master to Dev_fix&fea/リリース版の反映

#1107 master => develop [ver1.7.0.0]
  SuperNewRoles/Patches/HorseModePatch.cs
  SuperNewRoles/Patches/IntroPatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/Impostor/Matryoshka.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: master to Dev_fix&fea/リリース版の反映

#1113 妖狐に飽和勝利の設定を追加
  SuperNewRoles/Mode/CopsRobbers/CheckEndGame.cs
  SuperNewRoles/Mode/CopsRobbers/main.cs
  SuperNewRoles/Mode/SuperHostRoles/EndGameCheck.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Resources/Translate.csv
Labels: New feature/新機能, Add feature/既存の機能に追加

#1119 インポスターがスパイを確認できてしまう問題を修正
  SuperNewRoles/Patches/IntroPatch.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: Fix/バグ修正

#1121 スピーダーバグ修正
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Roles/Impostor/Speeder.cs
Labels: Fix/バグ修正

#1122 バイザーのプレビューが表示されない問題を修正
  SuperNewRoles/CustomCosmetics/CustomCosmeticsMenus/Patch/UpdatePatch.cs
Labels: Fix/バグ修正

#1123 /kcでキルクールタイムが正常に反映されない問題を修正
  SuperNewRoles/Helpers/RPCHelper.cs
Labels: Fix/バグ修正

#1124 サイエンティストで役職が変更された際、能力が継続してしまっている問題を修正
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: Fix/バグ修正

#1120 SHR対応していなかった[死亡者が全員の役職を確認できる]設定を対応
  SuperNewRoles/Mode/SuperHostRoles/FixedUpdate.cs
Labels: Fix/バグ修正, Support SHR/SHR対応

#1125 設定変更が反映されないことがある問題を修正
  SuperNewRoles/Patches/ControllerManagerPatch.cs
Labels: Fix/バグ修正

#1115 SHR🏇モードを封印していたコードを削除
  SuperNewRoles/Patches/HorseModePatch.cs
  SuperNewRoles/Patches/IntroPatch.cs
Labels: Adjustment/調整

#1126 SHRで夜行性が暗くなりすぎてしまう問題を修正
  SuperNewRoles/Patches/ShipStatusPatch.cs
Labels: Fix/バグ修正

#1129 バトロワで一部の設定が翻訳されていない問題を修正
  SuperNewRoles/Resources/Translate.csv
Labels: Fix/バグ修正

#1128 アドミンに近づいたまま会議に入った場合、会議中にもコミュサボが適用されてしまっている問題を修正
  SuperNewRoles/Mode/SuperHostRoles/BlockTool.cs
Labels: Fix/バグ修正

#1130 クリスマス以降限定コードを削除
  SuperNewRoles/Modules/CustomOptionModel.cs
Labels: Developmental/開発的, Adjustment/調整

#1127 天秤(Balancer)
  READMEs/README_en.md
  READMEs/README_jp.md
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/IntroData.cs
  SuperNewRoles/Patches/ControllerManagerPatch.cs
  SuperNewRoles/Patches/FixedUpdatePatch.cs
  SuperNewRoles/Patches/MeetingHudPatch.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Resources/Balancer/FlareEffect.png
  SuperNewRoles/Resources/Balancer/MeetingBack.png
  SuperNewRoles/Resources/Balancer/backsound.raw
  SuperNewRoles/Resources/Balancer/chain.raw
  SuperNewRoles/Resources/Balancer/chain/average_anim_chain_016.png
  SuperNewRoles/Resources/Balancer/chain/average_anim_chain_017.png
  SuperNewRoles/Resources/Balancer/chain/average_anim_chain_018.png
  SuperNewRoles/Resources/Balancer/chain/average_anim_chain_019.png
  SuperNewRoles/Resources/Balancer/chain/average_anim_chain_020.png
  SuperNewRoles/Resources/Balancer/chain/average_anim_chain_021.png
  SuperNewRoles/Resources/Balancer/chain/average_anim_chain_022.png
  SuperNewRoles/Resources/Balancer/chain/average_anim_chain_023.png
  SuperNewRoles/Resources/Balancer/chain/average_anim_chain_024.png
  SuperNewRoles/Resources/Balancer/chain/average_anim_chain_025.png
  SuperNewRoles/Resources/Balancer/chain/average_anim_chain_026.png
  SuperNewRoles/Resources/Balancer/chain/average_anim_chain_027.png
  SuperNewRoles/Resources/Balancer/chain/average_anim_chain_028.png
  SuperNewRoles/Resources/Balancer/chain/average_anim_chain_029.png
  SuperNewRoles/Resources/Balancer/chain/average_anim_chain_030.png
  SuperNewRoles/Resources/Balancer/chain/average_anim_chain_031.png
  SuperNewRoles/Resources/Balancer/eye-of-horus.png
  SuperNewRoles/Resources/Balancer/eye-of-horus_parts.png
  SuperNewRoles/Resources/Balancer/icon_average.png
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/CrewMate/Bakery.cs
  SuperNewRoles/Roles/CrewMate/Balancer.cs
  SuperNewRoles/Roles/CrewMate/WiseMan.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: New Role/新役職

#1118 リモートシェリフやGMなど修正
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: Fix/バグ修正

#1132 cだったのを修正。草。
  SuperNewRoles/Modules/IntroData.cs
Labels: Developmental/開発的, Adjustment/調整

#1131 聖職者の能力が会議後にリセットされない問題を修正
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Roles/CrewMate/Clergyman.cs
Labels: Fix/バグ修正

#1133 バージョン変更
  SuperNewRoles/SuperNewRoles.csproj
Labels: Version upgrade/バージョンアップ

#1134 master<=Develop fix
  README.md
  READMEs/README_en.md
  READMEs/README_jp.md
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Buttons/CustomButton.cs
  SuperNewRoles/CustomCosmetics/CustomCosmeticsMenus/Patch/UpdatePatch.cs
  SuperNewRoles/Helpers/RPCHelper.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Mode/SuperHostRoles/BlockTool.cs
  SuperNewRoles/Mode/SuperHostRoles/FixedUpdate.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomOptionModel.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/IntroData.cs
  SuperNewRoles/Patches/ControllerManagerPatch.cs
  SuperNewRoles/Patches/FixedUpdatePatch.cs
  SuperNewRoles/Patches/HorseModePatch.cs
  SuperNewRoles/Patches/IntroPatch.cs
  SuperNewRoles/Patches/MeetingHudPatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/ShipStatusPatch.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Resources/Balancer/FlareEffect.png
  SuperNewRoles/Resources/Balancer/MeetingBack.png
  SuperNewRoles/Resources/Balancer/backsound.raw
  SuperNewRoles/Resources/Balancer/chain.raw
  SuperNewRoles/Resources/Balancer/chain/average_anim_chain_016.png
  SuperNewRoles/Resources/Balancer/chain/average_anim_chain_017.png
  SuperNewRoles/Resources/Balancer/chain/average_anim_chain_018.png
  SuperNewRoles/Resources/Balancer/chain/average_anim_chain_019.png
  SuperNewRoles/Resources/Balancer/chain/average_anim_chain_020.png
  SuperNewRoles/Resources/Balancer/chain/average_anim_chain_021.png
  SuperNewRoles/Resources/Balancer/chain/average_anim_chain_022.png
  SuperNewRoles/Resources/Balancer/chain/average_anim_chain_023.png
  SuperNewRoles/Resources/Balancer/chain/average_anim_chain_024.png
  SuperNewRoles/Resources/Balancer/chain/average_anim_chain_025.png
  SuperNewRoles/Resources/Balancer/chain/average_anim_chain_026.png
  SuperNewRoles/Resources/Balancer/chain/average_anim_chain_027.png
  SuperNewRoles/Resources/Balancer/chain/average_anim_chain_028.png
  SuperNewRoles/Resources/Balancer/chain/average_anim_chain_029.png
  SuperNewRoles/Resources/Balancer/chain/average_anim_chain_030.png
  SuperNewRoles/Resources/Balancer/chain/average_anim_chain_031.png
  SuperNewRoles/Resources/Balancer/eye-of-horus.png
  SuperNewRoles/Resources/Balancer/eye-of-horus_parts.png
  SuperNewRoles/Resources/Balancer/icon_average.png
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/Attribute/Guesser.cs
  SuperNewRoles/Roles/CrewMate/Bakery.cs
  SuperNewRoles/Roles/CrewMate/Balancer.cs
  SuperNewRoles/Roles/CrewMate/Clergyman.cs
  SuperNewRoles/Roles/CrewMate/Squid.cs
  SuperNewRoles/Roles/CrewMate/WiseMan.cs
  SuperNewRoles/Roles/Impostor/Speeder.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: develop to master/マスターにマージ

#1139 Fix/anaurl
  SuperNewRoles/Modules/Analytics.cs
Labels: Change/変更, Developmental/開発的

#1140 いろいろずれが気になったのでdotnet format使用
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Buttons/CustomButton.cs
  SuperNewRoles/Buttons/OldModeButtons.cs
  SuperNewRoles/CustomObject/WaveCannonObject.cs
  SuperNewRoles/Main.cs
  SuperNewRoles/Modules/AssetLoader.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/IntroData.cs
  SuperNewRoles/Patches/IntroPatch.cs
  SuperNewRoles/Patches/LogoAndStampPatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Roles/Attribute/Guesser.cs
  SuperNewRoles/Roles/CrewMate/Bakery.cs
  SuperNewRoles/Roles/CrewMate/Balancer.cs
  SuperNewRoles/Roles/CrewMate/Clergyman.cs
  SuperNewRoles/Roles/CrewMate/Seer.cs
  SuperNewRoles/Roles/Impostor/Matryoshka.cs
  SuperNewRoles/Roles/Impostor/Penguin.cs
  SuperNewRoles/Roles/Impostor/Speeder.cs
  SuperNewRoles/Roles/Impostor/Teleporter.cs
  SuperNewRoles/Roles/Neutral/Jackal.cs
  SuperNewRoles/Roles/Neutral/JackalSeer.cs
  SuperNewRoles/Roles/Neutral/OrientalShaman.cs
  SuperNewRoles/Roles/Neutral/TheThreeLittlePigs.cs
  SuperNewRoles/Roles/Neutral/WaveCannonJackal.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  SuperNewRoles/Roles/RoleBases/RoleBase.cs
  SuperNewRoles/Roles/RoleBases/RoleBaseHelper.cs
  SuperNewRoles/Sabotage/FixSabotage.cs
Labels: Developmental/開発的, Adjustment/調整

#1142 Update for TChinese Translation
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Buttons/CustomButton.cs
  SuperNewRoles/Buttons/OldModeButtons.cs
  SuperNewRoles/CustomObject/WaveCannonObject.cs
  SuperNewRoles/Main.cs
  SuperNewRoles/Modules/Analytics.cs
  SuperNewRoles/Modules/AssetLoader.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/IntroData.cs
  SuperNewRoles/Patches/IntroPatch.cs
  SuperNewRoles/Patches/LogoAndStampPatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/Attribute/Guesser.cs
  SuperNewRoles/Roles/CrewMate/Bakery.cs
  SuperNewRoles/Roles/CrewMate/Balancer.cs
  SuperNewRoles/Roles/CrewMate/Clergyman.cs
  SuperNewRoles/Roles/CrewMate/Seer.cs
  SuperNewRoles/Roles/Impostor/Matryoshka.cs
  SuperNewRoles/Roles/Impostor/Penguin.cs
  SuperNewRoles/Roles/Impostor/Speeder.cs
  SuperNewRoles/Roles/Impostor/Teleporter.cs
  SuperNewRoles/Roles/Neutral/Jackal.cs
  SuperNewRoles/Roles/Neutral/JackalSeer.cs
  SuperNewRoles/Roles/Neutral/OrientalShaman.cs
  SuperNewRoles/Roles/Neutral/TheThreeLittlePigs.cs
  SuperNewRoles/Roles/Neutral/WaveCannonJackal.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  SuperNewRoles/Roles/RoleBases/RoleBase.cs
  SuperNewRoles/Roles/RoleBases/RoleBaseHelper.cs
  SuperNewRoles/Sabotage/FixSabotage.cs
Labels: Translation/翻訳
