Repository SuperNewRoles/SuperNewRoles, pull requests merged in 2023-10, with the labels that each got.

#1275 Update for TChinese translation
  SuperNewRoles/Resources/Translate.csv
Labels: Translation/翻訳

#1277 editorconfigの改行コードをCRLFからLFに変更
  .editorconfig
Labels: Change/変更, Developmental/開発的

#1280 イビルハッカーの会議中のアドミンに現在位置マークが出ないのを修正
  SuperNewRoles/Patches/MapPatch.cs
Labels: Add feature/既存の機能に追加

#1284 Update for TChinese translation
  SuperNewRoles/Resources/Translate.csv
Labels: Translation/翻訳

#1286 Update for SChinese Tranlslation
  SuperNewRoles/Resources/Translate.csv
Labels: Translation/翻訳

#1287 開発版反映
  SuperNewRoles/Main.cs
  SuperNewRoles/MapCustoms/4_Airship/RandomSpawn.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: Dev_fix&fea to develop/開発版にマージ

#1288 master <= Develop(2.0.4.2)
  SuperNewRoles/Main.cs
  SuperNewRoles/MapCustoms/4_Airship/RandomSpawn.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/SuperNewRoles.csproj
Labels: develop to master/マスターにマージ

#1289 Leak filling
  SuperNewRoles/Resources/Translate.csv
Labels: Translation/翻訳

#1291 Master <= Develop (2.0.4.3)
  .github/ISSUE_TEMPLATE/リリースタスクリスト.md
  SuperNewRoles/Buttons/VentAndSabo.cs
  SuperNewRoles/MapCustoms/4_Airship/RandomSpawn.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Mode/BattleRoyal/SyncBattleOptions.cs
  SuperNewRoles/Mode/CopsRobbers/RoleSystem.cs
  SuperNewRoles/Mode/SuperHostRoles/ChangeName.cs
  SuperNewRoles/Mode/SuperHostRoles/EndGameCheck.cs
  SuperNewRoles/Mode/SuperHostRoles/FixedUpdate.cs
  SuperNewRoles/Mode/SuperHostRoles/MorePatch.cs
  SuperNewRoles/Mode/SuperHostRoles/MurderPlayer.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleSelectHandler.cs
  SuperNewRoles/Mode/SuperHostRoles/SyncSetting.cs
  SuperNewRoles/Mode/SuperHostRoles/WrapUp.cs
  SuperNewRoles/Mode/SuperHostRoles/main.cs
  SuperNewRoles/Mode/Zombie/ZombieOptions.cs
  SuperNewRoles/Mode/Zombie/main.cs
  SuperNewRoles/Modules/ChacheManager.cs
  SuperNewRoles/Modules/DebugModeManager.cs
  SuperNewRoles/Modules/DefaultNameSaver.cs
  SuperNewRoles/Patches/ChatPatch.cs
  SuperNewRoles/Patches/CursedTasks/CursedDressUpTask.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/IntroPatch.cs
  SuperNewRoles/Patches/KillPatch.cs
  SuperNewRoles/Patches/MeetingHudPatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/SelectTaskPatch.cs
  SuperNewRoles/Patches/ShapeshiftPatch.cs
  SuperNewRoles/Patches/ShipStatusPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/Attribute/Guesser.cs
  SuperNewRoles/Roles/CrewMate/Balancer.cs
  SuperNewRoles/Roles/CrewMate/Doorr.cs
  SuperNewRoles/Roles/CrewMate/Knight.cs
  SuperNewRoles/Roles/CrewMate/MeetingSheriff_Patch.cs
  SuperNewRoles/Roles/CrewMate/PoliceSurgeon.cs
  SuperNewRoles/Roles/CrewMate/RedRidingHood.cs
  SuperNewRoles/Roles/CrewMate/SoothSayer_Patch.cs
  SuperNewRoles/Roles/Impostor/Assassin.cs
  SuperNewRoles/Roles/Impostor/Camouflager.cs
  SuperNewRoles/Roles/Impostor/MadRole/Madmate.cs
  SuperNewRoles/Roles/Neutral/Crook.cs
  SuperNewRoles/Roles/Neutral/FriendsRole/JackalFriends.cs
  SuperNewRoles/Roles/Neutral/Revolutionist.cs
  SuperNewRoles/Roles/Role/IntroHandler.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  SuperNewRoles/SuperNewRoles.csproj
  SuperNewRoles/SuperNewRolesWeb/AccountLoginMenu.cs
Labels: develop to master/マスターにマージ

#1312 Update for TChinese translation and the missing translations
  SuperNewRoles/Resources/Translate.csv
Labels: Translation/翻訳

#1314 Develop(2.1.1.2) => master
  SuperNewRoles/CustomCosmetics/CustomColors.cs
  SuperNewRoles/Main.cs
  SuperNewRoles/MapCustoms/5_TheFungle/AdditionalElectrical.cs
  SuperNewRoles/MapCustoms/5_TheFungle/FungleHandler.cs
  SuperNewRoles/MapCustoms/5_TheFungle/HideSporeMask.cs
  SuperNewRoles/MapCustoms/5_TheFungle/RandomSpawn.cs
  SuperNewRoles/MapCustoms/5_TheFungle/SelectSpawn.cs
  SuperNewRoles/MapCustoms/MapCustom.cs
  SuperNewRoles/MapCustoms/main.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Resources/FungleSelectSpawn/Cafeteria.png
  SuperNewRoles/Resources/FungleSelectSpawn/Campfire.png
  SuperNewRoles/Resources/FungleSelectSpawn/Comms.png
  SuperNewRoles/Resources/FungleSelectSpawn/Dropship.png
  SuperNewRoles/Resources/FungleSelectSpawn/Hotroom.png
  SuperNewRoles/Resources/FungleSelectSpawn/Kitchen.png
  SuperNewRoles/Resources/FungleSelectSpawn/UpperEngine.png
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/SuperNewRoles.csproj
Labels: develop to master/マスターにマージ
