Repository SuperNewRoles/SuperNewRoles, pull requests merged in 2023-01, with the labels that each got.

#919 Fix/camo sidekick
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: Fix/バグ修正

#920 PlayerAnimationがプレイヤーの子オブジェクトではなかった問題を修正
  SuperNewRoles/CustomObject/PlayerAnimation.cs
Labels: Fix/バグ修正

#892 ハンバーガー屋をSHR対応
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
Labels: Support SHR/SHR対応

#909 試合終了画面を整理
  SuperNewRoles/Patches/EndGamePatch.cs
Labels: Change/変更, Adjustment/調整

#921 Update for SChinese Translation
  SuperNewRoles/Resources/Translate.csv
Labels: Translation/翻訳

#917 金庫破り
  READMEs/README_en.md
  READMEs/README_jp.md
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/IntroData.cs
  SuperNewRoles/Modules/SetNames.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/MeetingHudPatch.cs
  SuperNewRoles/Patches/SelectTaskPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/CrewMate/HamburgerShop.cs
  SuperNewRoles/Roles/Impostor/EvilEraser.cs
  SuperNewRoles/Roles/Neutral/Safecracker.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: New Role/新役職

#918 ファストメーカーとリモートシェリフのボタンを修正
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Buttons/NormalButtonDestroy.cs
  SuperNewRoles/Mode/SuperHostRoles/FixedUpdate.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Roles/CrewMate/Sheriff.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
Labels: Fix/バグ修正, Change/変更

#916 新役職[崇拝者]_[SHR対応]
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Mode/SuperHostRoles/CoEnterVent.cs
  SuperNewRoles/Mode/SuperHostRoles/MorePatch.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleHelper.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleSelectHandler.cs
  SuperNewRoles/Mode/SuperHostRoles/SyncSetting.cs
  SuperNewRoles/Mode/SuperHostRoles/WrapUp.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/FinalStatus.cs
  SuperNewRoles/Modules/IntroData.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/IntroPatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/SelectTaskPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/CrewMate/Clergyman.cs
  SuperNewRoles/Roles/Impostor/MadRole/Madmate.cs
  SuperNewRoles/Roles/Impostor/MadRole/Worshiper.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: New Role/新役職

#922 SHRでジャッカルフレンズを作成時守護天使になって死んでしまう問題を修正(ResetAndSetRoleからSHR時守護天使にするコードを削除)
  SuperNewRoles/Helpers/RPCHelper.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
Labels: Fix/バグ修正

#923 役職カラー一部修正
  SuperNewRoles/Roles/Role/RoleClass.cs
Labels: Adjustment/調整

#925 イビルシーアがマッドシーアの死の点滅の設定を取得していた問題を修正
  SuperNewRoles/Roles/CrewMate/Seer.cs
Labels: Fix/バグ修正

#926 ReadMeの編集(公式情報源についてや「初めに読む場所」を追加)
  README.md
  READMEs/README_en.md
  READMEs/README_jp.md
  SuperNewRoles/Main.cs
Labels: Documentetion/文書の変更

#927 SHRのシーアズをいろいろ修正
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Mode/SuperHostRoles/CoEnterVent.cs
  SuperNewRoles/Mode/SuperHostRoles/FixedUpdate.cs
  SuperNewRoles/Mode/SuperHostRoles/MurderPlayer.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleSelectHandler.cs
  SuperNewRoles/Mode/SuperHostRoles/SyncSetting.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/CrewMate/Seer.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
Labels: Fix/バグ修正, Change/変更

#929 SHRにおいてマッドがベント移動できない設定およびベントアニメーション無効化設定が反映されている問題を修正
  SuperNewRoles/Buttons/VentAndSabo.cs
  SuperNewRoles/MapOption/MapOption.cs
Labels: Fix/バグ修正

#895 バグ#ticket-0093、0094、他 SHRスパイの不具合対応
  SuperNewRoles/Mode/SuperHostRoles/Intro.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleSelectHandler.cs
  SuperNewRoles/Patches/FixedUpdatePatch.cs
Labels: Fix/バグ修正

#928 めめ村ハットを追加
  SuperNewRoles / CustomCosmetics /CustomHats.cs
Labels: Other/その他

#941 ;不足でbuild不能問題修正
  SuperNewRoles/Patches/WrapUpPatch.cs
Labels: Fix/バグ修正

#940 CustomHats.csのパスがInnerSlothフォルダに移動していた為buildできなかった問題を修正
  SuperNewRoles/CustomCosmetics/CustomHats.cs
Labels: Fix/バグ修正

#930 Pythonやらの修正
  SNRDevTools/CreateRoleAdvanced.py
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/IntroData.cs
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: Python

#942 忘却者：正常に役職がセットされない問題を修正
  SuperNewRoles/Patches/PlayerControlPatch.cs
Labels: Fix/バグ修正

#952 ハリセンの位置を修正
  SuperNewRoles/CustomObject/PlayerAnimation.cs
Labels: Fix/バグ修正

#935 SuperNewRoles解析
  SuperNewRoles/Modules/Analytics.cs
  SuperNewRoles/Modules/Config.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Patches/ClientOptionsPatch/ModOptions.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/SNROnlySearch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/AllRoleSetClass.cs
Labels: Fix/バグ修正, New feature/新機能

#907 デバッグ用役職「デバッガー」
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Buttons/CustomButton.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/SetNames.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/Attribute/Debugger.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
Labels: New feature/新機能, Developmental/開発的

#946 //ロールチェックで重複している役職を削除(DarkKiller増殖しすぎ())
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: Fix/バグ修正

#948 ヴァルチャーが勝利できない問題及び能力使用後のクールリセットがない問題を修正
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Roles/Neutral/Vulture.cs
Labels: Fix/バグ修正

#954 SNRの公開投票修正&死亡後の公開投票の設定&アサシンとマーリンに公開投票の設定&Marlinの誤字を修正
  READMEs/README_en.md
  SuperNewRoles/Mode/SuperHostRoles/FixedUpdate.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleSelectHandler.cs
  SuperNewRoles/Mode/SuperHostRoles/SyncSetting.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/IntroData.cs
  SuperNewRoles/Modules/SetNames.cs
  SuperNewRoles/Patches/MeetingHudPatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/Attribute/Guesser.cs
  SuperNewRoles/Roles/CrewMate/Bakery.cs
  SuperNewRoles/Roles/CrewMate/MeetingSheriff_Patch.cs
  SuperNewRoles/Roles/Impostor/Assassin.cs
  SuperNewRoles/Roles/Impostor/ShiftActor.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: Fix/バグ修正, Add feature/既存の機能に追加

#955 マッドてるてるに狂信能力追加
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Patches/SelectTaskPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/Role/RoleClass.cs
Labels: Add feature/既存の機能に追加

#957 logに記載したくないRPCを辞書型で判定し記載しないようにした
  SuperNewRoles/Modules/CustomRPC.cs
Labels: Change/変更, Developmental/開発的

#956 イントロの再生サウンドを変更可能に。ついでにちらつき修正
  SNRDevTools/CreateRoleAdvanced.py
  SuperNewRoles/Mode/BattleRoyal/Intro.cs
  SuperNewRoles/Mode/ModeHandler.cs
  SuperNewRoles/Mode/SuperHostRoles/Intro.cs
  SuperNewRoles/Modules/IntroData.cs
  SuperNewRoles/Patches/IntroPatch.cs
Labels: Add feature/既存の機能に追加

#947 スターに、タスクフェイズ中キルクールタイムが経過する毎に全員の画面を光らせる設定を追加した。
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Patches/MeetingHudPatch.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/CrewMate/Celebrity.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
Labels: Add feature/既存の機能に追加

#894 バグ#ticket-0089 /wコマンドの勝利陣営
  SuperNewRoles/Patches/EndGamePatch.cs
Labels: Fix/バグ修正

#959 id重複を修正
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
Labels: Fix/バグ修正, EmergencyFix/緊急バグ修正

#962 カモの経過時間を個別処理に変更
  SuperNewRoles/Buttons/ButtonTime.cs
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Roles/Impostor/Camouflager.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
Labels: Fix/バグ修正

#960 SetRoomTimerRPCとSetDeviceTimeも記載しないようにした
  SuperNewRoles/Modules/CustomRPC.cs
Labels: Change/変更, Developmental/開発的

#944 新役職 : 炎狐
  READMEs/README_en.md
  READMEs/README_jp.md
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Buttons/NormalButtonDestroy.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/IntroData.cs
  SuperNewRoles/Modules/SetNames.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/IntroPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/Neutral/FireFox.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: New Role/新役職

#893 ファインダーをSHR対応
  SuperNewRoles/Mode/SuperHostRoles/FixedUpdate.cs
  SuperNewRoles/Mode/SuperHostRoles/MurderPlayer.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
Labels: Support SHR/SHR対応

#961 死後の公開投票を任意設定を反映させた後、上書きして匿名投票にしていた問題の修正
  SuperNewRoles/Mode/SuperHostRoles/SyncSetting.cs
Labels: Fix/バグ修正

#951 新役職 : イカ
  READMEs/README_en.md
  READMEs/README_jp.md
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/IntroData.cs
  SuperNewRoles/Patches/FixedUpdatePatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/ShipStatusPatch.cs
  SuperNewRoles/Resources/SquidButton.png
  SuperNewRoles/Resources/SquidInk.png
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/CrewMate/Squid.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: New Role/新役職

#958 新役職 : 遺言伝達者
  READMEs/README_en.md
  READMEs/README_jp.md
  SuperNewRoles/Modules/Config.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/IntroData.cs
  SuperNewRoles/Patches/ClientOptionsPatch/ModOptions.cs
  SuperNewRoles/Patches/MeetingHudPatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/CrewMate/DyingMessenger.cs
  SuperNewRoles/Roles/Neutral/FireFox.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: New Role/新役職
