Repository SuperNewRoles/SuperNewRoles, pull requests merged in 2023-05, with the labels that each got.

#1143 Update for SChinese Translation
  SuperNewRoles/Resources/Translate.csv
Labels: Translation/翻訳

#1151 master(v1.7.1.2) => develop
  SuperNewRoles/Helpers/RPCHelper.cs
  SuperNewRoles/Mode/SuperHostRoles/FixedUpdate.cs
  SuperNewRoles/Mode/SuperHostRoles/SyncSetting.cs
  SuperNewRoles/Modules/SetNames.cs
  SuperNewRoles/Patches/ChatCommandPatch.cs
  SuperNewRoles/Patches/ControllerManagerPatch.cs
  SuperNewRoles/Patches/MeetingHudPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/CrewMate/Balancer.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: master to Dev_fix&fea/リリース版の反映

#1155 CustomOverlayの修正と機能追加を行った。
  README.md
  READMEs/README_en.md
  READMEs/README_jp.md
  SuperNewRoles/Main.cs
  SuperNewRoles/Modules/CustomOptionModel.cs
  SuperNewRoles/Modules/CustomOverlay.cs
  SuperNewRoles/Modules/IntroData.cs
  SuperNewRoles/Patches/ChatCommandPatch.cs
  SuperNewRoles/Patches/ChatHandlerPatch.cs
  SuperNewRoles/Patches/IntroPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: Fix/バグ修正, New feature/新機能, Change/変更, Developmental/開発的, Add feature/既存の機能に追加

#1157 死亡時役職を確認できる設定が正常に動いていない問題を修正 ( 設定方法の変更によるバグ修正 )
  SuperNewRoles/Mode/PlusMode/PlusGameOptions.cs
  SuperNewRoles/Modules/SetNames.cs
  SuperNewRoles/Resources/Translate.csv
Labels: Fix/バグ修正, Change/変更

#1156 炎狐がアーソニストに燃やされないように修正
  SuperNewRoles/Roles/Neutral/Arsonist.cs
Labels: Fix/バグ修正

#1159 1.7.2.0に変更
  SuperNewRoles/SuperNewRoles.csproj
Labels: Version upgrade/バージョンアップ

#1158 一部役職の死因とDescription追加 & 崇拝者のDescriptionを修正
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Mode/SuperHostRoles/Roles/Jester.cs
  SuperNewRoles/Mode/SuperHostRoles/WrapUp.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/FinalStatus.cs
  SuperNewRoles/Modules/IntroData.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/Impostor/SerialKiller.cs
  SuperNewRoles/Roles/Impostor/Vampire.cs
Labels: Documentetion/文書の変更

#1160 Develop fix => master
  README.md
  READMEs/README_en.md
  READMEs/README_jp.md
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Main.cs
  SuperNewRoles/Mode/PlusMode/PlusGameOptions.cs
  SuperNewRoles/Mode/SuperHostRoles/Roles/Jester.cs
  SuperNewRoles/Mode/SuperHostRoles/WrapUp.cs
  SuperNewRoles/Modules/CustomOptionModel.cs
  SuperNewRoles/Modules/CustomOverlay.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/FinalStatus.cs
  SuperNewRoles/Modules/IntroData.cs
  SuperNewRoles/Modules/SetNames.cs
  SuperNewRoles/Patches/ChatCommandPatch.cs
  SuperNewRoles/Patches/ChatHandlerPatch.cs
  SuperNewRoles/Patches/IntroPatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/Impostor/SerialKiller.cs
  SuperNewRoles/Roles/Impostor/Vampire.cs
  SuperNewRoles/Roles/Neutral/Arsonist.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: develop to master/マスターにマージ

#1162 master => develop
  README.md
  READMEs/README_en.md
  READMEs/README_jp.md
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Main.cs
  SuperNewRoles/Mode/PlusMode/PlusGameOptions.cs
  SuperNewRoles/Mode/SuperHostRoles/Roles/Jester.cs
  SuperNewRoles/Mode/SuperHostRoles/WrapUp.cs
  SuperNewRoles/Modules/CustomOptionModel.cs
  SuperNewRoles/Modules/CustomOverlay.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/FinalStatus.cs
  SuperNewRoles/Modules/IntroData.cs
  SuperNewRoles/Modules/SetNames.cs
  SuperNewRoles/Patches/ChatCommandPatch.cs
  SuperNewRoles/Patches/ChatHandlerPatch.cs
  SuperNewRoles/Patches/IntroPatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/Impostor/SerialKiller.cs
  SuperNewRoles/Roles/Impostor/Vampire.cs
  SuperNewRoles/Roles/Neutral/Arsonist.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: master to Dev_fix&fea/リリース版の反映

#1163 Update for TChinese translation
  SuperNewRoles/Resources/Translate.csv
Labels: Translation/翻訳
