Repository SuperNewRoles/SuperNewRoles, pull requests merged in 2023-09, with the labels that each got.

#1243 [新機能] : SHRモードの初回会議時やホストがコマンドを発動させた時に, 役職情報をチャットに送る機能
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Modules/CustomOverlay.cs
  SuperNewRoles/Modules/MatchMaker.cs
  SuperNewRoles/Modules/ModTranslation.cs
  SuperNewRoles/Patches/ChatCommandPatch.cs
  SuperNewRoles/Patches/ChatHandlerPatch.cs
  SuperNewRoles/Patches/IntroPatch.cs
  SuperNewRoles/Patches/MeetingHudPatch.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/Neutral/Tuna.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
Labels: New feature/新機能, Change/変更

#1261 Update for TChinese translation
  SuperNewRoles/Resources/Translate.csv
Labels: Translation/翻訳

#1266 Dev_master (2.0.0.3) => master
  SuperNewRoles/Mode/PantsRoyal/UpdateHandler.cs
  SuperNewRoles/Patches/TaskCountPatch.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: develop to master/マスターにマージ
