Repository SuperNewRoles/SuperNewRoles, pull requests merged in 2023-07, with the labels that each got.

#1192 ベントを修正
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
Labels: Fix/バグ修正

#1191 hostモードを使用不可能にした&v1.8.0.0番台では使用できない旨の説明をいれ詳細のURLを押し付けるようにした
  SuperNewRoles/Patches/GameStartPatch.cs
  SuperNewRoles/Patches/ShareGameVersionPatch.cs
  SuperNewRoles/Resources/Translate.csv
Labels: Change/変更

#1189 公式SNRTwitterが旧アカウントだった為新アカウントに変更
  README.md
  READMEs/README_en.md
  READMEs/README_jp.md
  SuperNewRoles/Main.cs
  SuperNewRoles/Resources/Translate.csv
Labels: Documentetion/文書の変更, Change/変更

#1193 VersionUp 1.8.1.1
  SuperNewRoles/SuperNewRoles.csproj
Labels: Version upgrade/バージョンアップ

#1194 Develop_fix => master (1.8.1.1)
  README.md
  READMEs/README_en.md
  READMEs/README_jp.md
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Main.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Patches/GameStartPatch.cs
  SuperNewRoles/Patches/ShareGameVersionPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: develop to master/マスターにマージ

#1198 デバッグモードの取得方法を間違えていた問題を修正
  SuperNewRoles/Patches/GameStartPatch.cs
  SuperNewRoles/Patches/ShareGameVersionPatch.cs
Labels: Fix/バグ修正, EmergencyFix/緊急バグ修正

#1199 VersionUp 1.8.1.2
  SuperNewRoles/SuperNewRoles.csproj
Labels: Version upgrade/バージョンアップ

#1200 dev_fix => mas (1.8.1.2)
  SuperNewRoles/Patches/GameStartPatch.cs
  SuperNewRoles/Patches/ShareGameVersionPatch.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: develop to master/マスターにマージ

#1201 mas => dev_fea(1.8.1.2)
  README.md
  READMEs/README_en.md
  READMEs/README_jp.md
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/CustomCosmetics/CustomCosmeticsData/CustomHatData.cs
  SuperNewRoles/CustomCosmetics/CustomCosmeticsData/CustomPlateData.cs
  SuperNewRoles/CustomCosmetics/CustomCosmeticsData/CustomVisorData.cs
  SuperNewRoles/CustomCosmetics/CustomHats.cs
  SuperNewRoles/Main.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Patches/GameStartPatch.cs
  SuperNewRoles/Patches/ShareGameVersionPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: master to Dev_fix&fea/リリース版の反映

#1203 VersionUp 1.8.1.3
  SuperNewRoles/SuperNewRoles.csproj
Labels: Version upgrade/バージョンアップ

#1202 サーバに対し[ver2023.3.28]と偽装する機能作成
  SuperNewRoles/Main.cs
  SuperNewRoles/Patches/GameStartPatch.cs
  SuperNewRoles/Resources/Translate.csv
Labels: New feature/新機能, Adjustment/調整

#1204 Develop fix => master (1.8.1.3)
  SuperNewRoles/Main.cs
  SuperNewRoles/Patches/GameStartPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/SuperNewRoles.csproj
Labels: develop to master/マスターにマージ

#1205 SHRModeで開始不可能にしていたコードを削除
  SuperNewRoles/Patches/GameStartPatch.cs
  SuperNewRoles/Patches/ShareGameVersionPatch.cs
  SuperNewRoles/Resources/Translate.csv
Labels: Adjustment/調整

#1206 Develop fix => master (1.8.1.3up)
  SuperNewRoles/Patches/GameStartPatch.cs
  SuperNewRoles/Patches/ShareGameVersionPatch.cs
  SuperNewRoles/Resources/Translate.csv
Labels: develop to master/マスターにマージ

#1207 Support new game version 2023.7.11
  SuperNewRoles/Main.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleChat.cs
  SuperNewRoles/Modules/CustomOverlay.cs
  SuperNewRoles/Patches/ChatCommandPatch.cs
  SuperNewRoles/Patches/ChatPastePatch.cs
Labels: Support new game version/最新版対応

#1208 サーバ偽装をrevert&透視者を非表示に変更
  SuperNewRoles/Main.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomOptionModel.cs
  SuperNewRoles/Patches/GameStartPatch.cs
  SuperNewRoles/Resources/Translate.csv
Labels: Change/変更, Developmental/開発的

#1209 ClientMode以外開始不可能のコードを消去したコミットをリバート
  SuperNewRoles/Patches/GameStartPatch.cs
  SuperNewRoles/Patches/ShareGameVersionPatch.cs
  SuperNewRoles/Resources/Translate.csv
Labels: Change/変更

#1211 Version Up 1.9.0.0
  SuperNewRoles/SuperNewRoles.csproj
Labels: Version upgrade/バージョンアップ

#1212 2023.7.11版偽装コードに変更&HostModeの封印解除
  SuperNewRoles/Main.cs
  SuperNewRoles/Patches/GameStartPatch.cs
  SuperNewRoles/Patches/ShareGameVersionPatch.cs
  SuperNewRoles/Resources/Translate.csv
Labels: Change/変更, Developmental/開発的

#1215 設定画面が裏に表示される問題を修正
  SuperNewRoles/Patches/ClientOptionsPatch/ModOptions.cs
  SuperNewRoles/Patches/ClientOptionsPatch/VanillaOptions.cs
Labels: Fix/バグ修正

#1214 VersionUp 1.9.0.1
  SuperNewRoles/SuperNewRoles.csproj
Labels: Version upgrade/バージョンアップ

#1213 公開部屋使用不可を解除 & ローカルが使用できない, カスタムサーバに影響が出ている問題を修正
  README.md
  SuperNewRoles/Main.cs
  SuperNewRoles/Patches/GameStartPatch.cs
  SuperNewRoles/Resources/Translate.csv
Labels: Fix/バグ修正, Change/変更

#1217 master => Develop_feature (1.9.0.1)
  README.md
  SuperNewRoles/Main.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleChat.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomOptionModel.cs
  SuperNewRoles/Modules/CustomOverlay.cs
  SuperNewRoles/Patches/ChatCommandPatch.cs
  SuperNewRoles/Patches/ChatPastePatch.cs
  SuperNewRoles/Patches/ClientOptionsPatch/ModOptions.cs
  SuperNewRoles/Patches/ClientOptionsPatch/VanillaOptions.cs
  SuperNewRoles/Patches/GameStartPatch.cs
  SuperNewRoles/Patches/ShareGameVersionPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/SuperNewRoles.csproj
Labels: master to Dev_fix&fea/リリース版の反映

#1219 Feature/match maker
  SuperNewRoles/MapCustoms/main.cs
  SuperNewRoles/Modules/Analytics.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomOptionModel.cs
  SuperNewRoles/Modules/MatchMaker.cs
  SuperNewRoles/Patches/GameStartPatch.cs
Labels: New feature/新機能

#1220 VersionUp 1.9.1.0
  README.md
  SuperNewRoles/SuperNewRoles.csproj
Labels: Documentetion/文書の変更, Version upgrade/バージョンアップ

#1221 Develop_fix => master (1.9.1,0)
  README.md
  SuperNewRoles/MapCustoms/main.cs
  SuperNewRoles/Modules/Analytics.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomOptionModel.cs
  SuperNewRoles/Modules/MatchMaker.cs
  SuperNewRoles/Patches/GameStartPatch.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: develop to master/マスターにマージ

#1224 切断会議バグ修正
  SuperNewRoles/Modules/CustomOptionModel.cs
  SuperNewRoles/Modules/MatchMaker.cs
  SuperNewRoles/Patches/GameStartPatch.cs
Labels: Fix/バグ修正

#1225 バージョン変更
  SuperNewRoles/SuperNewRoles.csproj
Labels: Version upgrade/バージョンアップ

#1226 master <= Develop fix
  SuperNewRoles/Modules/CustomOptionModel.cs
  SuperNewRoles/Modules/MatchMaker.cs
  SuperNewRoles/Patches/GameStartPatch.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: develop to master/マスターにマージ

#1227 fixed-Starterror
  SuperNewRoles/Modules/CustomOptionModel.cs
Labels: Fix/バグ修正

#1228 master <= Develop fix
  SuperNewRoles/Modules/CustomOptionModel.cs
Labels: develop to master/マスターにマージ

#1222 master (1.9.1.1) => Develop_feature
  README.md
  SuperNewRoles/MapCustoms/main.cs
  SuperNewRoles/Modules/Analytics.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomOptionModel.cs
  SuperNewRoles/Modules/MatchMaker.cs
  SuperNewRoles/Patches/GameStartPatch.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: master to Dev_fix&fea/リリース版の反映

#1231 ラバーズが相方を連れて逝かない問題を修正
  SuperNewRoles/Patches/PlayerControlPatch.cs
Labels: Fix/バグ修正

#1230 [新機能] : マッチメイキングタグ
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomOptionModel.cs
  SuperNewRoles/Modules/CustomOverlay.cs
  SuperNewRoles/Modules/MatchMaker.cs
  SuperNewRoles/Modules/ModTranslation.cs
  SuperNewRoles/Patches/ChatHandlerPatch.cs
  SuperNewRoles/Patches/GameStartPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/Role/RoleClass.cs
Labels: New feature/新機能

#1236 master(BlackList) => Develop_fix
  SuperNewRoles/Modules/Blacklist.cs
  SuperNewRoles/Patches/ControllerManagerPatch.cs
  SuperNewRoles/Patches/LogoAndStampPatch.cs
Labels: Dev_fix&fea to develop/開発版にマージ

#1237 タグの情報を送信していなかった問題を修正&部屋作成と設定更新時で動くメソッドを分けた
  SuperNewRoles/Modules/MatchMaker.cs
  SuperNewRoles/Patches/GameStartPatch.cs
Labels: Fix/バグ修正

#1238 data["type"] = "updatetags";
  SuperNewRoles/Modules/MatchMaker.cs
Labels: Fix/バグ修正
