Repository SuperNewRoles/SuperNewRoles, pull requests merged in 2023-03, with the labels that each got.

#1054 Update for SChinese Translation
  SuperNewRoles/Resources/Translate.csv
Labels: Translation/翻訳

#1052 陰陽師のちょこっと変更
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Roles/Neutral/OrientalShaman.cs
Labels: Fix/バグ修正, Tested&OK/テスト済修正OK

#1051 仔豚の修正とか
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/FixedUpdatePatch.cs
  SuperNewRoles/Roles/Neutral/TheThreeLittlePigs.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: Fix/バグ修正, Tested&OK/テスト済修正OK

#1055 シェイプシフター系が死亡時Impostorghostに変更するコード削除
  SuperNewRoles/Helpers/RPCHelper.cs
  SuperNewRoles/Mode/SuperHostRoles/WrapUp.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: Adjustment/調整

#1053 [/MyRole]コマンド作成 & [/SL]コマンドをゲーム中使用できなかった問題修正
  SuperNewRoles/Patches/ChatCommandPatch.cs
  SuperNewRoles/Patches/ChatHandlerPatch.cs
  SuperNewRoles/Resources/Translate.csv
Labels: Fix/バグ修正, New feature/新機能

#1056 バージョン変更(=> 1.6.0.0)
  SuperNewRoles/SuperNewRoles.csproj
Labels: Version upgrade/バージョンアップ

#1059 Develop => master(1.6.0.0)
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Buttons/CustomButton.cs
  SuperNewRoles/Buttons/OldModeButtons.cs
  SuperNewRoles/CustomCosmetics/CustomColors.cs
  SuperNewRoles/CustomCosmetics/DownLoadCustomPlate.cs
  SuperNewRoles/CustomCosmetics/DownLoadCustomVisor.cs
  SuperNewRoles/Helpers/RPCHelper.cs
  SuperNewRoles/MapOption/DeviceClass.cs
  SuperNewRoles/Mode/SuperHostRoles/Roles/Fox.cs
  SuperNewRoles/Mode/SuperHostRoles/Roles/Minimalist.cs
  SuperNewRoles/Mode/SuperHostRoles/Roles/Samurai.cs
  SuperNewRoles/Mode/SuperHostRoles/WrapUp.cs
  SuperNewRoles/Modules/AutoUpdate.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Patches/ChatCommandPatch.cs
  SuperNewRoles/Patches/ChatHandlerPatch.cs
  SuperNewRoles/Patches/ClientOptionsPatch/ModOptions.cs
  SuperNewRoles/Patches/ClientOptionsPatch/VanillaOptions.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/FixedUpdatePatch.cs
  SuperNewRoles/Patches/LogoAndStampPatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/SNROnlySearch.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/CrewMate/Squid.cs
  SuperNewRoles/Roles/Neutral/Hitman.cs
  SuperNewRoles/Roles/Neutral/OrientalShaman.cs
  SuperNewRoles/Roles/Neutral/TheThreeLittlePigs.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: Version upgrade/バージョンアップ

#1060 master(1.6.0.0) => Develop_feature
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Buttons/CustomButton.cs
  SuperNewRoles/Buttons/OldModeButtons.cs
  SuperNewRoles/CustomCosmetics/CustomColors.cs
  SuperNewRoles/CustomCosmetics/DownLoadCustomPlate.cs
  SuperNewRoles/CustomCosmetics/DownLoadCustomVisor.cs
  SuperNewRoles/Helpers/RPCHelper.cs
  SuperNewRoles/MapOption/DeviceClass.cs
  SuperNewRoles/Mode/SuperHostRoles/Roles/Fox.cs
  SuperNewRoles/Mode/SuperHostRoles/Roles/Minimalist.cs
  SuperNewRoles/Mode/SuperHostRoles/Roles/Samurai.cs
  SuperNewRoles/Mode/SuperHostRoles/WrapUp.cs
  SuperNewRoles/Modules/AutoUpdate.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Patches/ChatCommandPatch.cs
  SuperNewRoles/Patches/ChatHandlerPatch.cs
  SuperNewRoles/Patches/ClientOptionsPatch/ModOptions.cs
  SuperNewRoles/Patches/ClientOptionsPatch/VanillaOptions.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/FixedUpdatePatch.cs
  SuperNewRoles/Patches/LogoAndStampPatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/SNROnlySearch.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/CrewMate/Squid.cs
  SuperNewRoles/Roles/Neutral/Hitman.cs
  SuperNewRoles/Roles/Neutral/OrientalShaman.cs
  SuperNewRoles/Roles/Neutral/TheThreeLittlePigs.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: master to Dev_fix&fea/リリース版の反映

#1065 ゲッサーが正常に動作しない問題を修正
  SuperNewRoles/Roles/Attribute/Guesser.cs
Labels: Fix/バグ修正

#1064 ろーーーーーーーーーーーーるべーーーーーーーーーーーーす ( RoleBase の作成)
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Patches/FixedUpdatePatch.cs
  SuperNewRoles/Patches/MeetingHudPatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleTemplate.cs
  SuperNewRoles/Roles/RoleBases/CustomRoles.cs
  SuperNewRoles/Roles/RoleBases/RoleBase.cs
  SuperNewRoles/Roles/RoleBases/RoleBaseHelper.cs
Labels: New feature/新機能, Developmental/開発的

#1066 設定変更時の通信量を大幅に削減
  SuperNewRoles/Modules/CustomOptionModel.cs
Labels: Refactoring/リファクタリング, Adjustment/調整

#1071 崇拝者RoleBase化
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Mode/SuperHostRoles/CoEnterVent.cs
  SuperNewRoles/Mode/SuperHostRoles/FixedUpdate.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleHelper.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleSelectHandler.cs
  SuperNewRoles/Mode/SuperHostRoles/SyncSetting.cs
  SuperNewRoles/Mode/SuperHostRoles/WrapUp.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/IntroData.cs
  SuperNewRoles/Modules/SetNames.cs
  SuperNewRoles/Patches/ControllerManagerPatch.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/IntroPatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/CrewMate/SoothSayer.cs
  SuperNewRoles/Roles/CrewMate/SoothSayer_Patch.cs
  SuperNewRoles/Roles/Impostor/MadRole/Madmate.cs
  SuperNewRoles/Roles/Impostor/MadRole/Worshiper.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  SuperNewRoles/Roles/RoleBases/RoleBaseHelper.cs
Labels: Change/変更, Developmental/開発的

#1063 アーソニストの勝利順位を修正 & クラードが自殺時勝利できないように変更 & 最終生存しているのに死因が記載される問題の修正
  READMEs/README_en.md
  READMEs/README_jp.md
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/Neutral/Arsonist.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
Labels: Change/変更, Adjustment/調整

#1080 アドミンの人数が一部2倍になる問題の修正
  SuperNewRoles/MapOption/DeviceClass.cs
Labels: Fix/バグ修正

#1082 繁体中国語対応
  SuperNewRoles/Modules/ModTranslation.cs
  SuperNewRoles/Resources/Translate.csv
Labels: New feature/新機能

#1083 警告を修正
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Roles/CrewMate/NiceMechanic.cs
  SuperNewRoles/Roles/CrewMate/WiseMan.cs
Labels: Developmental/開発的

#1084 ペンギンのバグ修正
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/Impostor/Penguin.cs
Labels: Fix/バグ修正

#1088 SidekickPromotesに存在した無駄なカスタムRPCで飛ばす内容を削除
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Roles/Neutral/Jackal.cs
  SuperNewRoles/Roles/Neutral/JackalSeer.cs
  SuperNewRoles/Roles/Neutral/WaveCannonJackal.cs
Labels: Developmental/開発的

#1087 新設定 [波動砲ジャッカル] のサイドキック[サイドキック(波動砲)]
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/CustomObject/WaveCannonObject.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/IntroData.cs
  SuperNewRoles/Modules/SetNames.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/FixedUpdatePatch.cs
  SuperNewRoles/Patches/Harmony/ExileController.cs
  SuperNewRoles/Patches/Harmony/PlayerControl.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/Attribute/Guesser.cs
  SuperNewRoles/Roles/Impostor/EvilEraser.cs
  SuperNewRoles/Roles/Neutral/Jackal.cs
  SuperNewRoles/Roles/Neutral/JackalSeer.cs
  SuperNewRoles/Roles/Neutral/SidekickWaveCannon.cs
  SuperNewRoles/Roles/Neutral/WaveCannonJackal.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  SuperNewRoles/Roles/RoleBases/RoleBase.cs
  SuperNewRoles/Roles/RoleBases/RoleBaseHelper.cs
Labels: New Role/新役職, Add feature/既存の機能に追加

#1092 Versionup 1.6.0.0 =>1.6.1.0
  SuperNewRoles/Roles/Neutral/WaveCannonJackal.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: Version upgrade/バージョンアップ

#1096 Update for SChinese translation
  SuperNewRoles/Resources/Translate.csv
Labels: Translation/翻訳

#1098 対応完了
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Roles/Impostor/Matryoshka.cs
Labels: Support new game version/最新版対応

#1100 SHRモードを一時封印
  SuperNewRoles/Patches/HorseModePatch.cs
  SuperNewRoles/Patches/IntroPatch.cs
Labels: Other/その他
