Repository SuperNewRoles/SuperNewRoles, pull requests merged in 2023-02, with the labels that each got.

#965 ファインダーがSHRでクライアントのみ動作しない問題を修正
  SuperNewRoles/Mode/SuperHostRoles/MurderPlayer.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
Labels: Fix/バグ修正

#967 シェイプシフター置き換え役職を死後Impostorghostにするようにした(シェイプ置き換え役職配役時のタスク勝利問題修正)
  SuperNewRoles/Helpers/RPCHelper.cs
  SuperNewRoles/Mode/SuperHostRoles/WrapUp.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: Fix/バグ修正

#970 半角カンマが使用されていて翻訳がずれている問題を修正
  SuperNewRoles/Resources/Translate.csv
Labels: Fix/バグ修正

#977 master=>develop(v1.5.3.0_ChineseTranslate)
  SuperNewRoles/Resources/Translate.csv
Labels: master to Dev_fix&fea/リリース版の反映

#997 master <= Develop fix
  SuperNewRoles/Buttons/ButtonTime.cs
  SuperNewRoles/Helpers/RPCHelper.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleSelectHandler.cs
  SuperNewRoles/Modules/Analytics.cs
  SuperNewRoles/Modules/IntroData.cs
  SuperNewRoles/Modules/SetNames.cs
  SuperNewRoles/Patches/IntroPatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/Attribute/Jumbo.cs
  SuperNewRoles/Roles/CrewMate/Scientist.cs
  SuperNewRoles/Roles/CrewMate/Shielder.cs
  SuperNewRoles/Roles/Impostor/Teleporter.cs
  SuperNewRoles/Roles/Neutral/Arsonist.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: develop to master/マスターにマージ

#998 Develop_feature <= master
  SuperNewRoles/Buttons/ButtonTime.cs
  SuperNewRoles/Helpers/RPCHelper.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleSelectHandler.cs
  SuperNewRoles/Modules/Analytics.cs
  SuperNewRoles/Modules/IntroData.cs
  SuperNewRoles/Modules/SetNames.cs
  SuperNewRoles/Patches/IntroPatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/Attribute/Jumbo.cs
  SuperNewRoles/Roles/CrewMate/Scientist.cs
  SuperNewRoles/Roles/CrewMate/Shielder.cs
  SuperNewRoles/Roles/Impostor/Teleporter.cs
  SuperNewRoles/Roles/Neutral/Arsonist.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: Dev_fix&fea to develop/開発版にマージ

#999 develop <= master
  SuperNewRoles/Buttons/ButtonTime.cs
  SuperNewRoles/Helpers/RPCHelper.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleSelectHandler.cs
  SuperNewRoles/Modules/Analytics.cs
  SuperNewRoles/Modules/IntroData.cs
  SuperNewRoles/Modules/SetNames.cs
  SuperNewRoles/Patches/IntroPatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/Attribute/Jumbo.cs
  SuperNewRoles/Roles/CrewMate/Scientist.cs
  SuperNewRoles/Roles/CrewMate/Shielder.cs
  SuperNewRoles/Roles/Impostor/Teleporter.cs
  SuperNewRoles/Roles/Neutral/Arsonist.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: Dev_fix&fea to develop/開発版にマージ

#1006 炎狐が勝利できない問題の修正
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Roles/Impostor/EvilEraser.cs
Labels: Fix/バグ修正

#1007 遺言伝達者が能力を発動した際に、遺言伝達者目線生き返る問題の修正
  SuperNewRoles/Modules/CustomRPC.cs
Labels: Fix/バグ修正

#1008 master->Develop_fix(masterマージしてしまった為)
  SuperNewRoles/Modules/CustomRPC.cs
Labels: master to Dev_fix&fea/リリース版の反映

#1010 キルガードされた際、それ以降その人をキルできなくなる問題の修正(遺言伝達者の死亡時刻保存重複の修正)
  SuperNewRoles/Patches/PlayerControlPatch.cs
Labels: Fix/バグ修正

#1001 master branchでない時やDebugModeの時は解析を送らないようにした(自分で切ればいい?面倒くさいねん())
  SuperNewRoles/Patches/EndGamePatch.cs
Labels: Change/変更, Developmental/開発的

#1003 ShowFlashのnull問題をローカル変数randererをprivate変数に変える事で対処した
  SuperNewRoles/Mode/SuperHostRoles/MurderPlayer.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Roles/CrewMate/Seer.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
Labels: Fix/バグ修正, Change/変更, Developmental/開発的

#1002 ベータ版の場合WelcomeMessageとしてバージョン情報が出るようにした&/vをHostが使用した場合全体送信になるように変更した。
  SuperNewRoles/Patches/ChatHandlerPatch.cs
Labels: Change/変更

#1011 崇拝者がベント設定と視界設定が入れ替わって変数に代入されていた問題を修正
  SuperNewRoles/Roles/Impostor/MadRole/Worshiper.cs
Labels: Fix/バグ修正

#1009 サボタージュ修理画面を開けなくするプログラムを追加
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Sabotage/FixSabotage.cs
Labels: New feature/新機能, Add feature/既存の機能に追加

#1017 キルボタンの名前にFinalStatusKillを使っている物を純正の翻訳に変更&サイドキック能力を適切な翻訳に変更
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Resources/Translate.csv
Labels: Documentetion/文書の変更

#1018 PlayerControlHeplerをPlayerControlHelperに修正
  SuperNewRoles/Helpers/PlayerControlHelper.cs
  SuperNewRoles/Mode/ModeHandler.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Patches/IntroPatch.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: Documentetion/文書の変更

#1016 ジャッカルとジャッカルシーアのSK能力にあった不要な、変数とGetBool();を削除した
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
Labels: Refactoring/リファクタリング

#1020 インポ役職の最大設定数を15にした
  SuperNewRoles/Modules/CustomOptionHolder.cs
Labels: Change/変更

#1022 Update for SChinese Translation
  SuperNewRoles/Resources/Translate.csv
Labels: Translation/翻訳

#1019 新色5色を追加
  SuperNewRoles/CustomCosmetics/CustomColors.cs
  SuperNewRoles/Resources/Translate.csv
Labels: Adjustment/調整

#1013 シェリフ系役職のキル可能か判定するコードをすべて纏めた&誤射に巻き込まれたクルーの死因を変更した
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/FinalStatus.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/CrewMate/MeetingSheriff_Patch.cs
  SuperNewRoles/Roles/CrewMate/Sheriff.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
Labels: Fix/バグ修正, Refactoring/リファクタリング, Developmental/開発的

#1021 Is陣営関数の整理 (タスククリアやクルー勝利除外を陣営単位管理に変更 & IsKiller関数作成)
  SNRDevTools/CreateRole.py
  SNRDevTools/CreateRoleAdvance/ReadMe.txt
  SNRDevTools/CreateRoleAdvanced.py
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Roles/Neutral/FireFox.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: Fix/バグ修正, Change/変更, Developmental/開発的

#1014 新役職 : 3匹の仔豚 (#1021の後にマージ)
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/FinalStatus.cs
  SuperNewRoles/Modules/IntroData.cs
  SuperNewRoles/Modules/SetNames.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/FixedUpdatePatch.cs
  SuperNewRoles/Patches/IntroPatch.cs
  SuperNewRoles/Patches/MeetingHudPatch.cs
  SuperNewRoles/Patches/SelectTaskPatch.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/CrewMate/Celebrity.cs
  SuperNewRoles/Roles/Neutral/TheThreeLittlePigs.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: New Role/新役職

#1025 SHRでサボタージュ修復封じ(使用キーの封印)が聞かないように変更
  SuperNewRoles/Sabotage/FixSabotage.cs
Labels: Fix/バグ修正

#1027 新役職 : 陰陽師
  SNRDevTools/CreateRoleAdvanced.py
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Buttons/VentAndSabo.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/IntroData.cs
  SuperNewRoles/Modules/OutfitManager.cs
  SuperNewRoles/Modules/SetNames.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/FixedUpdatePatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/SelectTaskPatch.cs
  SuperNewRoles/Resources/OrientalShamanButton.png
  SuperNewRoles/Resources/ShermansServantButton.png
  SuperNewRoles/Resources/ShermansServantSuicideButton.png
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/CrewMate/SoothSayer_Patch.cs
  SuperNewRoles/Roles/Neutral/OrientalShaman.cs
  SuperNewRoles/Roles/Neutral/Vulture.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  SuperNewRoles/Sabotage/FixSabotage.cs
Labels: New Role/新役職

#1024 New role/mechanic
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/Buttons/VentAndSabo.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/IntroData.cs
  SuperNewRoles/Patches/FixedUpdatePatch.cs
  SuperNewRoles/Patches/MeetingHudPatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Resources/MechanicButton_Evil.png
  SuperNewRoles/Resources/MechanicButton_Nice.png
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/CrewMate/NiceMechanic.cs
  SuperNewRoles/Roles/CrewMate/Scientist.cs
  SuperNewRoles/Roles/Impostor/EvilMechanic.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: New Role/新役職

#1026 新役職[賢者]
  SuperNewRoles/Buttons/Buttons.cs
  SuperNewRoles/CustomObject/WaveCannonObject.cs
  SuperNewRoles/Modules/AssetLoader.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/IntroData.cs
  SuperNewRoles/Patches/ControllerManagerPatch.cs
  SuperNewRoles/Patches/FixedUpdatePatch.cs
  SuperNewRoles/Patches/MeetingHudPatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Resources/WaveCannon/Shoot_0001.png
  SuperNewRoles/Resources/WaveCannon/Shoot_0002.png
  SuperNewRoles/Resources/WaveCannon/Shoot_0003.png
  SuperNewRoles/Resources/WaveCannon/Shoot_0004.png
  SuperNewRoles/Resources/WaveCannon/Shoot_0005.png
  SuperNewRoles/Resources/WaveCannon/Shoot_0006.png
  SuperNewRoles/Resources/WaveCannon/Shoot_0007.png
  SuperNewRoles/Resources/WaveCannon/Shoot_0008.png
  SuperNewRoles/Resources/WaveCannon/Shoot_0009.png
  SuperNewRoles/Resources/WaveCannon/Shoot_0010.png
  SuperNewRoles/Resources/WaveCannon/Shoot_0011.png
  SuperNewRoles/Resources/WaveCannon/Shoot_0012.png
  SuperNewRoles/Resources/WaveCannon/WaveCannonEffects.bundle
  SuperNewRoles/Resources/WiseManButton.png
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/CrewMate/WiseMan.cs
  SuperNewRoles/Roles/Impostor/Penguin.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: New Role/新役職

#1031 役職のアサインが正常に行われない問題の修正
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: Fix/バグ修正, EmergencyFix/緊急バグ修正

#1032 Develop fix => develop (ver1.5.4.1)
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: Version upgrade/バージョンアップ, Dev_fix&fea to develop/開発版にマージ

#1034 master (ver1.5.4.1) => Develop_feature
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: master to Dev_fix&fea/リリース版の反映

#1035 master (ver1.5.4.1) => Develop_fix
  SuperNewRoles/SuperNewRoles.csproj
Labels: master to Dev_fix&fea/リリース版の反映

#1036 うまく動かない　陣営Playerをコメントアウトし、勝利除外を個別記載した
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: Fix/バグ修正

#1038 バージョン変更(=> 1.5.4.2)
  SuperNewRoles/SuperNewRoles.csproj
Labels: Version upgrade/バージョンアップ

#1039 Develop_fix => develop
  SuperNewRoles/Modules/CustomOptionModel.cs
  SuperNewRoles/Patches/ControllerManagerPatch.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: Dev_fix&fea to develop/開発版にマージ

#1040 develop => master(ver.1.5.4.2)
  SuperNewRoles/Modules/CustomOptionModel.cs
  SuperNewRoles/Patches/ControllerManagerPatch.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: develop to master/マスターにマージ

#1042 master(1.5.4.2) => Develop_feature
  SuperNewRoles/Modules/CustomOptionModel.cs
  SuperNewRoles/Patches/ControllerManagerPatch.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: master to Dev_fix&fea/リリース版の反映

#1041 master(1.5.4.2) => Develop_fix
  SuperNewRoles/SuperNewRoles.csproj
Labels: master to Dev_fix&fea/リリース版の反映

#1043 殺し屋のターゲットの矢印色が分かりづらかったので赤色に変更
  SuperNewRoles/Roles/Neutral/Hitman.cs
Labels: Adjustment/調整

#1045 シールダーバグ修正
  SuperNewRoles/Buttons/Buttons.cs
Labels: Fix/バグ修正

#1047 軽いリファクタ
  SuperNewRoles/Buttons/CustomButton.cs
  SuperNewRoles/CustomCosmetics/CustomColors.cs
  SuperNewRoles/CustomCosmetics/DownLoadCustomPlate.cs
  SuperNewRoles/CustomCosmetics/DownLoadCustomVisor.cs
  SuperNewRoles/Patches/LogoAndStampPatch.cs
Labels: Refactoring/リファクタリング

#1048 CurrentButtonsへの修正不足によるbuildエラー修正
  SuperNewRoles/Roles/CrewMate/Squid.cs
Labels: Fix/バグ修正, EmergencyFix/緊急バグ修正
