Repository SuperNewRoles/SuperNewRoles, pull requests merged in 2024-03, with the labels that each got.

#1346 開発版の反映 2.2.0.0
  SuperNewRoles/CustomCosmetics/CustomCosmeticsData/CustomHatData.cs
  SuperNewRoles/CustomCosmetics/CustomCosmeticsData/CustomVisorData.cs
  SuperNewRoles/CustomCosmetics/CustomCosmeticsMenus/Patch/UpdatePatch.cs
  SuperNewRoles/CustomCosmetics/CustomVisor.cs
  SuperNewRoles/Helpers/RPCHelper.cs
  SuperNewRoles/Mode/SuperHostRoles/SyncSetting.cs
  SuperNewRoles/Modules/Blacklist.cs
  SuperNewRoles/Modules/Config.cs
  SuperNewRoles/Patches/BanParticularPlayerPatch.cs
  SuperNewRoles/Patches/HorseModePatch.cs
  SuperNewRoles/Patches/IntroPatch.cs
  SuperNewRoles/Patches/KillOverlayPatch.cs
  SuperNewRoles/Patches/TitleMenuPatch.cs
  SuperNewRoles/Patches/TrickOrTreat.cs
  SuperNewRoles/Replay/ReplayFileWriter.cs
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  SuperNewRoles/Roles/RoleBases/CustomButtonInfo.cs
  SuperNewRoles/Roles/RoleBases/Interfaces/ISupportSHR.cs
  SuperNewRoles/Roles/RoleBases/Interfaces/ITaskHolder.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: Dev_fix&fea to develop/開発版にマージ

#1347 master <= Develop 2.2.0.0
  SuperNewRoles/CustomCosmetics/CustomCosmeticsData/CustomHatData.cs
  SuperNewRoles/CustomCosmetics/CustomCosmeticsData/CustomVisorData.cs
  SuperNewRoles/CustomCosmetics/CustomCosmeticsMenus/Patch/UpdatePatch.cs
  SuperNewRoles/CustomCosmetics/CustomVisor.cs
  SuperNewRoles/Helpers/RPCHelper.cs
  SuperNewRoles/Mode/SuperHostRoles/SyncSetting.cs
  SuperNewRoles/Modules/Blacklist.cs
  SuperNewRoles/Modules/Config.cs
  SuperNewRoles/Patches/BanParticularPlayerPatch.cs
  SuperNewRoles/Patches/HorseModePatch.cs
  SuperNewRoles/Patches/IntroPatch.cs
  SuperNewRoles/Patches/KillOverlayPatch.cs
  SuperNewRoles/Patches/TitleMenuPatch.cs
  SuperNewRoles/Patches/TrickOrTreat.cs
  SuperNewRoles/Replay/ReplayFileWriter.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  SuperNewRoles/Roles/RoleBases/CustomButtonInfo.cs
  SuperNewRoles/Roles/RoleBases/Interfaces/ISupportSHR.cs
  SuperNewRoles/Roles/RoleBases/Interfaces/ITaskHolder.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: develop to master/マスターにマージ

#1350 Develop_Dev(2.2.0.0) => Develop_public
  SuperNewRoles/Buttons/VentAndSabo.cs
  SuperNewRoles/CustomObject/PlayerAnimation.cs
  SuperNewRoles/CustomObject/RocketDeadbody.cs
  SuperNewRoles/CustomObject/SluggerDeadbody.cs
  SuperNewRoles/Main.cs
  SuperNewRoles/MapOption/LadderZiplineCool.cs
  SuperNewRoles/MapOption/MapOption.cs
  SuperNewRoles/Mode/ModeHandler.cs
  SuperNewRoles/Mode/PlusMode/PlusGameOptions.cs
  SuperNewRoles/Mode/SuperHostRoles/ReportDeadBody.cs
  SuperNewRoles/Mode/SuperHostRoles/SyncSetting.cs
  SuperNewRoles/Modules/Analytics.cs
  SuperNewRoles/Modules/Blacklist.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomOptionModel.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/IntroData.cs
  SuperNewRoles/Patches/ChatHandlerPatch.cs
  SuperNewRoles/Patches/ControllerManagerPatch.cs
  SuperNewRoles/Patches/EmergencyMinigamePatch.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/GameStartPatch.cs
  SuperNewRoles/Patches/HostManagedChatCommandPatch.cs
  SuperNewRoles/Patches/KillPatch.cs
  SuperNewRoles/Patches/MeetingHudPatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/CrewMate/Balancer.cs
  SuperNewRoles/Roles/CrewMate/Observer.cs
  SuperNewRoles/Roles/CrewMate/PoliceSurgeon.cs
  SuperNewRoles/Roles/Neutral/Crook.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  SuperNewRoles/Roles/Role/RoleInfo.cs
  SuperNewRoles/Roles/RoleBases/CustomRoles.cs
  SuperNewRoles/Roles/RoleBases/Interfaces/IMeetingHandler.cs
  SuperNewRoles/Roles/RoleBases/OptionInfo.cs
  SuperNewRoles/Sabotage/Patch.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: Dev_fix&fea to develop/開発版にマージ

#1351 Develop(2.2.0.0) => master
  SuperNewRoles/Buttons/VentAndSabo.cs
  SuperNewRoles/CustomObject/PlayerAnimation.cs
  SuperNewRoles/CustomObject/RocketDeadbody.cs
  SuperNewRoles/CustomObject/SluggerDeadbody.cs
  SuperNewRoles/Main.cs
  SuperNewRoles/MapOption/LadderZiplineCool.cs
  SuperNewRoles/MapOption/MapOption.cs
  SuperNewRoles/Mode/ModeHandler.cs
  SuperNewRoles/Mode/PlusMode/PlusGameOptions.cs
  SuperNewRoles/Mode/SuperHostRoles/ReportDeadBody.cs
  SuperNewRoles/Mode/SuperHostRoles/SyncSetting.cs
  SuperNewRoles/Modules/Analytics.cs
  SuperNewRoles/Modules/Blacklist.cs
  SuperNewRoles/Modules/BotManager.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomOptionModel.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/IntroData.cs
  SuperNewRoles/Patches/ChatHandlerPatch.cs
  SuperNewRoles/Patches/ControllerManagerPatch.cs
  SuperNewRoles/Patches/EmergencyMinigamePatch.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/GameStartPatch.cs
  SuperNewRoles/Patches/HostManagedChatCommandPatch.cs
  SuperNewRoles/Patches/KillPatch.cs
  SuperNewRoles/Patches/MeetingHudPatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/WrapUpPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/CrewMate/Balancer.cs
  SuperNewRoles/Roles/CrewMate/Observer.cs
  SuperNewRoles/Roles/CrewMate/PoliceSurgeon.cs
  SuperNewRoles/Roles/Neutral/Crook.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
  SuperNewRoles/Roles/Role/RoleInfo.cs
  SuperNewRoles/Roles/RoleBases/CustomRoles.cs
  SuperNewRoles/Roles/RoleBases/Interfaces/IMeetingHandler.cs
  SuperNewRoles/Roles/RoleBases/OptionInfo.cs
  SuperNewRoles/Sabotage/Patch.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: develop to master/マスターにマージ

#1353 イビルハッカーに通信サボタージュ中にアドミンを使用できるオプションを追加
  SuperNewRoles/MapOption/DeviceClass.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/Impostor/EvilHacker.cs
Labels: New Role/新役職

#1352 イビルハッカーのサボタージュマップの色の調整
  SuperNewRoles/Patches/MapPatch.cs
Labels: Adjustment/調整
