Repository SuperNewRoles/SuperNewRoles, pull requests merged in 2024-07, with the labels that each got.

#1381 ModHelpers.Csの改良
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Patches/ProtectPatch.cs
Labels: Developmental/開発的, Adjustment/調整

#1382 Typo修正とか
  SuperNewRoles/Main.cs
  SuperNewRoles/ModHelpers.cs
  SuperNewRoles/Mode/BattleRoyal/BattleRole/KingPoster.cs
  SuperNewRoles/Mode/CopsRobbers/RoleSystem.cs
  SuperNewRoles/Mode/ModeHandler.cs
  SuperNewRoles/Mode/SuperHostRoles/RoleSelectHandler.cs
  SuperNewRoles/Modules/CacheManager.cs
  SuperNewRoles/Modules/ChacheManager.cs
  SuperNewRoles/Modules/CustomRPC.cs
  SuperNewRoles/Modules/LegacyOptionDataMigration.cs
  SuperNewRoles/Patches/LadderDeadPatch.cs
  SuperNewRoles/Patches/MeetingHudPatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/AllRoleSetClass.cs
  SuperNewRoles/Roles/Attribute/HauntedWolf.cs
  SuperNewRoles/Roles/Attribute/Lovers.cs
  SuperNewRoles/Roles/CrewMate/Bakery.cs
  SuperNewRoles/Roles/CrewMate/JumpDancer.cs
  SuperNewRoles/Roles/Impostor/Assassin.cs
  SuperNewRoles/Roles/Impostor/Rocket.cs
  SuperNewRoles/Roles/Impostor/ShiftActor.cs
  SuperNewRoles/Roles/Neutral/Jackal.cs
  SuperNewRoles/Roles/Neutral/Spelunker.cs
  SuperNewRoles/Roles/Neutral/WaveCannonJackal.cs
  SuperNewRoles/Roles/Role/RoleClass.cs
  SuperNewRoles/Roles/Role/RoleHelper.cs
Labels: Developmental/開発的, Adjustment/調整

#1387 Update for TChinese translation
  SuperNewRoles/Resources/Translate.csv
Labels: Translation/翻訳

#1391 Dev_Develop(2.3.1.2) => Develop
  .gitignore
  SuperNewRoles/Mode/SuperHostRoles/AntiBlackOut.cs
  SuperNewRoles/Mode/SuperHostRoles/Helpers.cs
  SuperNewRoles/Mode/SuperHostRoles/HideChat.cs
  SuperNewRoles/Mode/SuperHostRoles/OneClickShapeshift.cs
  SuperNewRoles/Mode/SuperHostRoles/ReportDeadBody.cs
  SuperNewRoles/Mode/SuperHostRoles/SyncSetting.cs
  SuperNewRoles/Modules/Config.cs
  SuperNewRoles/Modules/CustomOptionHolder.cs
  SuperNewRoles/Modules/CustomOverlay.cs
  SuperNewRoles/Modules/LoggerPlus.cs
  SuperNewRoles/Patches/ChatHandlerPatch.cs
  SuperNewRoles/Patches/ClientOptionsPatch/ModOptions.cs
  SuperNewRoles/Patches/ControllerManagerPatch.cs
  SuperNewRoles/Patches/EndGamePatch.cs
  SuperNewRoles/Patches/IntroPatch.cs
  SuperNewRoles/Patches/PlayerControlPatch.cs
  SuperNewRoles/Patches/SendChatPatch.cs
  SuperNewRoles/Patches/ShapeshiftPatch.cs
  SuperNewRoles/Resources/Translate.csv
  SuperNewRoles/Roles/CrewMate/Ubiquitous.cs
  SuperNewRoles/Roles/Neutral/Crook.cs
  SuperNewRoles/SuperNewRoles.csproj
Labels: Dev_fix&fea to develop/開発版にマージ

#1395 Update for SChinese Translation
  SuperNewRoles/Resources/Translate.csv
Labels: Translation/翻訳
